### ISSUE TITLE
KPU output array

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#100]
Is there any sequence to KPU output arrays? The first is the output of Keras/tensorflow - I would like to have the same order of outputs when accessing the output array in K210, the KPU output is jumbled, is there any sequence to it or is it random?

```

separable_conv2d_15 (SeparableC (None, 8, 10, 18)    6912        separable_conv2d_14[0][0]        
__________________________________________________________________________________________________
separable_conv2d_12 (SeparableC (None, 15, 20, 18)   2432        separable_conv2d_11[0][0]        
__________________________________________________________________________________________________
separable_conv2d_8 (SeparableCo (None, 30, 40, 18)   1216        separable_conv2d_7[0][0]  
```

```
SUMMARY
INPUTS
0       Input_0 1x3x240x320
OUTPUTS
0       Identity        1x18x15x20
1       Identity_1      1x18x8x10
2       Identity_2      1x18x30x40
```

**Comment by sunnycase** [comment]
The order is the same as tflite's output nodes list.

**Comment by krishnak** [comment]
ok there is some issue with tflite_convert. when it is converting the keras model to tflite its changing the order of output. This is not a nncase issue.
