### ISSUE TITLE
Not supported tflite opcode: CUSTOM

### ISSUE THREAD

**Issue by Lyan200** [kendryte/nncase#101]
When I  trying to convert the tflite to kmodel using the command below , the error occurs:Not supported tflite opcode: CUSTOM
#!bin/sh
 ./ncc/ncc compile detect.tflite  detect.kmodel -i tflite

**Comment by tjmc** [comment]
Can you attach the model? CUSTOM ops are likely not supported unless you port them.

**Comment by sunnycase** [comment]
See https://github.com/kendryte/nncase/blob/master/docs/tflite_ops.md
