### ISSUE TITLE
转换tflite模型失败，提示：Shapes must be same, but got [1x200x1428] and [200x1428]

### ISSUE THREAD

**Issue by BKB23** [kendryte/nncase#1022]
工具版本：NNCase v0.2.0 Beta4。tensorflow=2.7,python=3.8
我的模型输入形状为[1,200,1600,1]，输出形状为[1,200,1428]。

我一开始进行转换tflite模型时提示：
Fatal: Not supported tflite opcode: SHAPE
根据[#213 ](url) 问题的解决方法我将keras模型转换为tflite模型的代码修改为：
```
model = tf.keras.models.load_model(h5_name)
for i in range(len(model.inputs)):
    print("i=", i)
    model.inputs[i].set_shape([1, 1600, 200, 1])  # Replace with your input shape
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
converter = tf.lite.TFLiteConverter.from_concrete_functions([full_model])
tflite_model = converter.convert()
open(tflite_name, "wb").write(tflite_model)
```
然后再次运行终端命令：./ncc compile tflite/SpeechModel.tflite model.kmodel -i tflite -o kmodel -t k210 --inference-type float
没有再提示上面的报错，但是提示了新的错误：
Fatal: Shapes must be same, but got [1x200x1428] and [200x1428]

我虽然也在issues中找到了相似的问题[#43 ](url)，但是时间比较早，没有头绪应该怎么解决，希望有人解答我的问题，万分感谢！
以下是我的h5和tflite模型文件：
[speechmodel.zip](https://github.com/kendryte/nncase/files/12159704/speechmodel.zip)

**Comment by BKB23** [comment]
上面打错了，输入形状是[1,1600,200,1]

**Comment by curioyang** [comment]
@BKB23 0.2 版本可能存在BUG，用1.0以上的新版本试试

**Comment by BKB23** [comment]
@curioyang  我使用的是sipeed开发板，他目前固件最高只支持kmodel v4，所以只能使用0.2版本的nncase进行转换...
我也尝试了CanMV，貌似他不能识别到我的开发板
那请问是否还有其他方法？

**Comment by curioyang** [comment]
@BKB23 CanMV的问题可以在QQ群里咨询 sundaycase

**Comment by BKB23** [comment]
> @BKB23 CanMV的问题可以在QQ群里咨询 sundaycase

感谢解答，我更新了固件后CanMV已经能连接到开发板了
我再研究下将我的模型转换为kmodel v5，再使用CanMV进行应用

**Comment by curioyang** [comment]
先行关闭了，如果再有什么问题可以reopen
