### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by TianLiJun** [kendryte/nncase#108]
clock.cc:(.text.unlikely+0x30): undefined reference to `absl::base_internal::SpinLock::SlowLock()'
clock.cc:(.text.unlikely+0x63): undefined reference to `absl::base_internal::UnscaledCycleClock::Now()'
clock.cc:(.text.unlikely+0xa3): undefined reference to `absl::raw_logging_internal::RawLog(absl::LogSeverity, char const*, int, char const*, ...)'
clock.cc:(.text.unlikely+0xb2): undefined reference to `absl::base_internal::UnscaledCycleClock::Now()'
clock.cc:(.text.unlikely+0x3a8): undefined reference to `absl::base_internal::SpinLock::SlowUnlock(unsigned int)'

所有absl都是undefined

**Comment by sunnycase** [comment]
Install conan==1.21.1.
