### ISSUE TITLE
pre-built binary for macOS?

### ISSUE THREAD

**Issue by dongzhixia** [kendryte/nncase#11]
Hi, is there any plan for supporting macOS? Thx

**Comment by sunnycase** [comment]
You can try the nightly-build https://ci.appveyor.com/project/sunnycase/nncase/build/artifacts

**Comment by dongzhixia** [comment]
@sunnycase Thanks!

**Comment by andriyadi** [comment]
I can see there’s no macOS version there https://ci.appveyor.com/project/sunnycase/nncase/build/artifacts 
It is used to be there. Or am I mistaken? Please advice.

**Comment by sunnycase** [comment]
@andriyadi now macOS version is back. https://dev.azure.com/sunnycase/nncase/_build?definitionId=1
