### ISSUE TITLE
.tflite to .kmodel Layer PACK is not supported

### ISSUE THREAD

**Issue by stnridy** [kendryte/nncase#1109]
Hi. I am trying to convert .tflite model to .kmodel to flash into a Maixduino. I refer to the tutorial in this page --> https://courses.cs.washington.edu/courses/cse475/19au/labs/yolo2_tutorial.html

However, I am seeing this error below when trying to run this command 
" **./tflite2kmodel.sh detect.tflite** "

<img width="740" alt="image" src="https://github.com/kendryte/nncase/assets/137426283/d172829d-9bf1-448e-9eb4-3c2e13650e64">

I would appreciate if anyone can help show/guide me on how I can convert .tflite to .kmodel.

***Also, I am wondering if we can directly flash .tflite into a Maixduino. Anyone know?

**Comment by sunnycase** [comment]
As it said, tflite `PACK` operator is not supported.
