### ISSUE TITLE
Which method is recommended for downsample?

### ISSUE THREAD

**Issue by PureHing** [kendryte/nncase#112]
May I ask how much slower roughly on k210 to use conv (stride = 1) + maxpooling (stride = 2) than conv (stride = 2)?

**Comment by sunnycase** [comment]
Both are same fast on k210, but you should use symmetric paddings when doing stride=2, See https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md.

**Comment by PureHing** [comment]
Thanks.
