### ISSUE TITLE
K210 Convert Fault

### ISSUE THREAD

**Issue by MegaPandas** [kendryte/nncase#1129]
**Describe the bug**
Convert float32 tflite to K210 kmodel Fault

```
1. Import graph...
Segmentation fault
```

**To Reproduce**
Command line or scripts to reproduce the behavior:

```
import nncase

def read_model_file(model_file):
    with open(model_file, 'rb') as f:
        model_content = f.read()
    return model_content

def main():
    model='model/unet_version1.tflite'
    target = 'k210'

    # compile_options
    compile_options = nncase.CompileOptions()
    compile_options.target = target
    compile_options.dump_ir = True
    compile_options.dump_asm = True
    compile_options.dump_dir = 'tmp'

    # compiler
    compiler = nncase.Compiler(compile_options)

    # import_options
    import_options = nncase.ImportOptions()

    # import
    model_content = read_model_file(model)
    compiler.import_tflite(model_content, import_options)

    # compile
    compiler.compile()

    # kmodel
    kmodel = compiler.gencode_tobytes()
    with open('test.kmodel', 'wb') as f:
        f.write(kmodel)

if __name__ == '__main__':
    main()
```

**Expected behavior**
Convert model to kmodel

**Origin model and code**
[model.zip](https://github.com/kendryte/nncase/files/13386332/model.zip)

**Environment (please complete the following information):**
 - Os: Windows 11  WSL2 Ubuntu 20.04 LST
 - nncase version [v1.9.0.20230322]
 - DL Framework [TensorFlow 2.13.1 cuda 11.8 cudnn 8.6.0]
 - Python 3.10.13

**Additional context**

**Comment by curioyang** [comment]
@MegaPandas Your model has been quantized. You'd better use a pure float model to convert. If have other fault with float model, put error here again.
