### ISSUE TITLE
Huge difference between the output from tflite model and kmodel

### ISSUE THREAD

**Issue by zye1996** [kendryte/nncase#114]
Hi,

I am trying to convert a tflite model to kmodel but during testing the output from both models, I found a huge difference after conversion. 

Here is my tflite model and converted kmodel.
[Archive.zip](https://github.com/kendryte/nncase/files/4490325/Archive.zip)
I used command 
```ncc compile model.tflite model.kmodel -i tflite -o kmodel -t k210 --inference-type uint8 --dataset images  --input-mean 0.5 --input-std 0.5``` for the conversion.

And my input range originally being [-1, 1]

Also I tried float inference and the result is the same. The output from kmodel is of range 10^2 while the output from tflite model is 10^-2

**Comment by sunnycase** [comment]
Have you tested with the CI version?

**Comment by zye1996** [comment]
> Have you tested with the CI version?

I tried all the versions under release built for macOS but none of them works for me. Is there another version available or I have to build from source?

**Comment by sunnycase** [comment]
CI from master
https://dev.azure.com/sunnycase/nncase/_build/results?buildId=156&view=artifacts&type=publishedArtifacts

**Comment by zye1996** [comment]
> CI from master
> https://dev.azure.com/sunnycase/nncase/_build/results?buildId=156&view=artifacts&type=publishedArtifacts

I tested with the CI verision and the compiled model works fine. However when I did the compilation, it throws out warning:
```WARN: Conv2D_1 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_3 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_5 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_13 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_21 Fallback to float conv2d due to weights divergence.
```

I would assume it will degrade the performance of using kpu, is there any solution to this?

**Comment by zye1996** [comment]
Figured out with option --weights-quantize-threshold
