### ISSUE TITLE
fix some caffe op

### ISSUE THREAD

**Issue by corleonechensiyu** [kendryte/nncase#115]
caffe卷积转kmodel时，如没有pad_h()和pad_w()时，只能根据param.pad(0)来取pad的值，stride和dilation类似。如
`if(param.has_pad_w() && param.has_pad_h())
    {
        pad_h = (int32_t)get_or_default(std::bind(arr_func_t(&ConvolutionParameter::pad), &param, _1), param.pad_size(), 0, param.pad_h());
        pad_w = (int32_t)get_or_default(std::bind(arr_func_t(&ConvolutionParameter::pad), &param, _1), param.pad_size(), 1, param.pad_w());
        
    }
    else
    { 
        pad_h = (int32_t)get_or_default(std::bind(arr_func_t(&ConvolutionParameter::pad), &param, _1), 0, 0, param.pad_size() != 0 ? param.pad(0) : 0);
        pad_w = (int32_t)get_or_default(std::bind(arr_func_t(&ConvolutionParameter::pad), &param, _1), 0, 1, param.pad_size() != 0 ? param.pad(0) : 0);

    }
    auto groups = param.group();
    
    if(param.has_stride_w() && param.has_stride_h())
    {
        stride_h = get_or_default(std::bind(arr_func_t(&ConvolutionParameter::stride), &param, _1), param.stride_size(), 0, param.stride_h());
        stride_w = get_or_default(std::bind(arr_func_t(&ConvolutionParameter::stride), &param, _1), param.stride_size(), 1, param.stride_w());

    }
    else
    {
        stride_h = get_or_default(std::bind(arr_func_t(&ConvolutionParameter::stride), &param, _1), 0, 0, param.stride_size() != 0 ? param.stride(0) : 1);
        stride_w = get_or_default(std::bind(arr_func_t(&ConvolutionParameter::stride), &param, _1), 0, 1, param.stride_size() != 0 ? param.stride(0) : 1);
        
    }`

**Comment by corleonechensiyu** [comment]
![捕获](https://user-images.githubusercontent.com/39826330/79575712-c133e280-80f4-11ea-8255-3586df078bd3.PNG)
![捕获1](https://user-images.githubusercontent.com/39826330/79575732-c6912d00-80f4-11ea-870b-b57ee79ed89a.PNG)

**Comment by corleonechensiyu** [comment]
### caffe中MAX pooling池化。
这样写是否有问题。
`auto dilation_h = 1;`
`auto dilation_w = 1;`
`float init_value =std::numeric_limits<float>::lowest();`
` auto node = graph_.emplace<reduce_window2d>(reduce_max, input.shape(), init_value, f_h, f_w, padding { pad_h, pad_h }, padding { pad_w, pad_w },stride_h, stride_w, dilation_h, dilation_w,value_range<float>::full());`
`input_tensors_.emplace(&node->input(), op.bottom(0));
    output_tensors_.emplace(op.top(0), &node->output());`

**Comment by corleonechensiyu** [comment]
### 全连接层InnerProduct
`DEFINE_CAFFE_LOWER(InnerProduct)
{
    auto &input = *output_tensors_.at(op.bottom(0));
    auto &param = op.inner_product_param();
    
    auto bias = load_tensor<1>(op.blobs(1));

    auto &buffer = op.blobs(0).data();
    auto shape = get_shape(op.blobs(0).shape());

    
    auto weights =graph_.emplace<constant>(dt_float32,std::move(shape),*buffer.data());
    auto input_b_trans = graph_.emplace<transpose>(dt_float32, weights->output().shape(), axis_t { 1, 0 });
    input_b_trans->input().connect(weights->output());
    auto fc = graph_.emplace<matmul>(input.shape(), input_b_trans->output().shape(), std::move(bias),
        value_range<float>::full());

    fc->input_b().connect(input_b_trans->output());
    input_tensors_.emplace(&fc->input_a(), op.bottom(0));
    output_tensors_.emplace(op.top(0), &fc->output());
    
}`
默认全连接层输入维度已经是2维，这样写是否正确

**Comment by sunnycase** [comment]
`auto weights = graph_.emplace<constant>(dt_float32,std::move(shape),*buffer.data());`
改为
`auto weights = graph_.emplace<constant>(dt_float32, std::move(shape), buffer.begin(), buffer.end());`

**Comment by corleonechensiyu** [comment]
@sunnycase 好的，谢谢
