### ISSUE TITLE
ncc windows application for converting MLIR based tflite models to kmodel

### ISSUE THREAD

**Issue by chinya07** [kendryte/nncase#1177]
Hello,
Is there an "ncc" Windows application available to convert the models trained with Tensorflow 2.x (ultimately converted to TFLite with MLIR support) to convert TFLite models to kmodel? I am trying to convert the `mobilenetv1` model trained with TF 2.x using ncc v0.2 to kmodel but getting **"Fallback to float weights divergence"** warnings for the initial few Conv2D layers. Also, I am not sure if TF 2.x TFLite models are supported for Kendryte K210 (as per docs in the main branch it's not).

**Comment by curioyang** [comment]
@chinya07
Unfortunately,  `ncc` does not support TF2.0, especially `MLIR`.
'ncc' can no longer keep up with the latest technology, you can use it to convert older versions of TF such as TF1.x.
