### ISSUE TITLE
When I used the nncase to convert tflite model to kmodel ,it hints invalid tflite model

### ISSUE THREAD

**Issue by Karley-Liu** [kendryte/nncase#1178]
Fatal: Invalid tflite model
![image](https://github.com/kendryte/nncase/assets/54927031/0bc340c2-52c3-43b6-9b3c-3ae262854e2c)

**Comment by Karley-Liu** [comment]
and,when i convert other tflite,nothing wrong hints happen but it was just stop.
![image](https://github.com/kendryte/nncase/assets/54927031/0d0eeb68-26f2-449d-838e-8d92dd384e8c)

**Comment by curioyang** [comment]
@Karley-Liu  Maybe your TFLite model needs a downgrade. You'd better use TF1.x to generate your model.
