### ISSUE TITLE
type UINT8 is not supported

### ISSUE THREAD

**Issue by onionstack** [kendryte/nncase#118]
Error at runtime:

Fatal: Tensor (MobilenetV1/MobilenetV1/Conv2d_0/weights_quant/FakeQuantWithMinMaxVars) of type UINT8 is not supported

**Comment by zye1996** [comment]
> Error at runtime:
> 
> Fatal: Tensor (MobilenetV1/MobilenetV1/Conv2d_0/weights_quant/FakeQuantWithMinMaxVars) of type UINT8 is not supported

You are using a quant-aware training model? nncase support only float model conversion

**Comment by sunnycase** [comment]
You should use float model.
