### ISSUE TITLE
The kernel broke as soon as i generate the kmodel.

### ISSUE THREAD

**Issue by LinYeeGiong** [kendryte/nncase#1190]
[https://github.com/kendryte/nncase/tree/master/examples/user_guide](url)
I used the code in the link above to generate the kmodel, but **the kernel broke as soon as it ran up**.

![issue](https://github.com/kendryte/nncase/assets/129134694/a570ec18-bed0-4bc7-9b09-59667a3d903f)

**Comment by curioyang** [comment]
Increase your memory or virtual memory. @LinYeeGiong
