### ISSUE TITLE
Fatal: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by xiaogangLi** [kendryte/nncase#12]
Hi,  when I converted TFLite model(mobilenet_ssd) to K210 model, I got an error:Fatal: Index was outside the bounds of the array. What may lead  to this error? thanks!

**Comment by mushroom-x** [comment]
me too 
![index-out-of-boundary](https://user-images.githubusercontent.com/13478703/57120611-191eef80-6da5-11e9-9a66-e51424cc19f1.png)

**Comment by sunnycase** [comment]
Quantized tflite model is not supported yet.

**Comment by mushroom-x** [comment]
My tflite model is  not a quantized tflite model, just a simple neural network.

tflite model visualization (by netron)
![tflite_model](https://user-images.githubusercontent.com/13478703/57352947-911c5980-7199-11e9-9df9-afd174e4a0a6.png)

**Comment by marcel12bell** [comment]
@sunnycase same here... any news on this?

**Comment by sunnycase** [comment]
@marcel12bell Can you upload or send the .tflite to me for debugging?

**Comment by marcel12bell** [comment]
@sunnycase It's not my own... used this h5: https://github.com/marcogdepinto/Emotion-Classification-Ravdess and converted it to .tfite...

**Comment by sunnycase** [comment]
@marcel12bell At this moment, Conv1D is not supported. You can see the full supported layers list: https://github.com/kendryte/nncase#supported-layers
