### ISSUE TITLE
Latest master fails to build on Xubuntu LTS 18.04

### ISSUE THREAD

**Issue by sheref-sidarous** [kendryte/nncase#120]
Latest master fails to build on Xubuntu LTS 18.04, attached build output.

[config_output.txt](https://github.com/kendryte/nncase/files/4534647/config_output.txt)
[build_output.txt](https://github.com/kendryte/nncase/files/4534677/build_output.txt)

Thanks

**Comment by sunnycase** [comment]
install conan==1.21.1

**Comment by sheref-sidarous** [comment]
this fixed it, FYI build fails on more recent versions of conan.
