### ISSUE TITLE
转换ConvNext预训练模型时，提前退出，无报错信息

### ISSUE THREAD

**Issue by ssyj911** [kendryte/nncase#1200]
**Describe the bug**
将ConvNext预训练模型转kmodel时，nncase 编译器输出："2.Optimize target independent..." 后退出。无任何其他提示

**To Reproduce**
预训练模型可以在以下地址获取：
https://dl.fbaipublicfiles.com/convnext/convnext_tiny_1k_224_ema.pth

**Origin model and code**
按照 nncase 提供的 编译float32 onnx模型 代码进行 kmodel 进行转换

**Environment (please complete the following information):**
 - OS: [ Ubuntu20.04]
 - nncase version 1.9.0-3473131
 - DL Framework [python 3.8]

**Additional context**
尝试将nncase安装包中的 nncase-1.9.0/examples/yolox/model/yolox_nano_224.onnx 进行转换，未发现问题

**Comment by curioyang** [comment]
@ssyj911 请直接提供onnx模型

**Comment by ssyj911** [comment]
> @ssyj911 请直接提供onnx模型

这个太大了，上传到百度云盘啦：链接: https://pan.baidu.com/s/1MEIbKCnJama3k1AjjSn4uw?pwd=ymgf 提取码: ymgf

**Comment by curioyang** [comment]
@ssyj911  If you can modify this model, here is a simple way to solve this issue. Just swap A and B of this binary_mul. Let A be the input tensor, and B be constant.
![image](https://github.com/kendryte/nncase/assets/39184746/e854c544-dda5-46ef-b60b-ff06c97b33d5)

Otherwise, you need to download the new Python whl and runtime after my commit.

**Comment by curioyang** [comment]
@ssyj911 编译的问题已经修复了，但是这个模型里有大量的CPU算子layernorm，在实际推理的时候速度很慢，且510 在设计上存在一定的精度损失。
如果在510上部署实际项目，建议更换模型
或者可以尝试在230上部署，int16量化，230对部分CPU算子是有V扩展优化的，且不太容易出现精度损失

**Comment by ssyj911** [comment]
非常感谢您的帮助



---原始邮件---
发件人: "Curio ***@***.***&gt;
发送时间: 2024年5月14日(周二) 上午9:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kendryte/nncase] 转换ConvNext预训练模型时，提前退出，无报错信息 (Issue #1200)




 
@ssyj911 编译的问题已经修复了，但是这个模型里有大量的CPU算子layernorm，在实际推理的时候速度很慢，且510 在设计上存在一定的精度损失。
 如果在510上部署实际项目，建议更换模型
 或者可以尝试在230上部署，int16量化，230对部分CPU算子是有V扩展优化的，且不太容易出现精度损失
