### ISSUE TITLE
Speed up calibration step

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#122]
./ncc compile mymodel.tflite mymodel.kmodel -i tflite --dataset ./imagefolder/ 
1. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...

I have a image folder with 15000 images, when I give this folder as dataset folder  for ncc compile, it takes ages to complete, its done only 15% in 20 minutes.

I am running it on a 8 Core machine with 24GB RAM. Is there a way to speed things up.

Edit: CPU usage is very low its using only a single core and that too around 25% of it

**Comment by sunnycase** [comment]
You don't have to use that many images to do calibration. Hundreds of images are enough.

**Comment by krishnak** [comment]
Thanks for the input
