### ISSUE TITLE
yolov8 模型 -->.onnx-->kmodel在01Sudio部署时识别效果差

### ISSUE THREAD

**Issue by Javachenlianghong** [kendryte/nncase#1249]
[nncase.zip](https://github.com/user-attachments/files/17054865/nncase.zip)

开发环境：python3.7 nncase 2.9
![image](https://github.com/user-attachments/assets/f02006cc-c4aa-4eb2-9a8e-5a587bfeb8b0)

1.如果使用demo转换的可以在PC端进行模拟
![f34f0196b0b0880f5d3b14459f978ebf](https://github.com/user-attachments/assets/68cda832-2749-42c8-a613-51dabfe8aea6)
但是部署到板子上啥都识别不出来
2.使用YOLOV8的转换代码也是啥都识别不出来，calibration datase我试过（100，2000）张图片效果还是一样的甚至在PC端都无法模拟
![image](https://github.com/user-attachments/assets/41189818-2262-499f-a6b4-6700fe771994)
3.onnx的推理在PC端的推理结果不错
![image](https://github.com/user-attachments/assets/de864ee9-6202-4b88-ac8a-842509e7c20b)

4.图片
[images.zip](https://github.com/user-attachments/files/17054767/images.zip)
5.detect_kmodel.py就是在k230的推理代码，PC_detect.py就是第二点报错的代码

**Comment by curioyang** [comment]
我这边跑没问题啊，PC_detec 里面我不确定你的路径文件是否存在，试一下新的
```
# run kmodel(simulate)
import os
import nncase
from nncase_base_func import *
import numpy as np
kmodel_path = "tmp/test.kmodel"
input_data = [np.random.rand(1, 3, 640, 640).astype(np.uint8)]
dump_path='./tmp/'
result = run_kmodel(kmodel_path, input_data)
for idx, i in enumerate(result):
    print(i.shape)
    i.tofile(os.path.join(dump_path,"nncase_result_{}.bin".format(idx)))
    
import onnxruntime as rt
model_path='./best.onnx'
onnx_model = model_simplify(model_path)
onnx_model = model_path
_, input_info = parse_model_input_output(model_path)
onnx_sess = rt.InferenceSession(onnx_model)

input_dict = {}
for i, info in enumerate(input_info):
    print(info['shape'])
    input_dict[info["name"]] = input_data[i].astype(np.float32)/255.0

onnx_results = onnx_sess.run(None, input_dict)
for index, (i, j) in enumerate(zip(onnx_results, result)):
    print("result {} cosine = ".format(index), get_cosine(i, j))    
```
