### ISSUE TITLE
How to simulate the loading of the kmodel version 3 on the PC

### ISSUE THREAD

**Issue by onionstack** [kendryte/nncase#125]
How to simulate the loading of the kmodel version 3 on the PC, the 0.1.0 version of the nncase command does not have an infer command.
Why mobileNet version 3 and version 4 output different feature tensors when recognizing the same picture?

**Comment by sunnycase** [comment]
Please refer to https://github.com/kendryte/nncase/tree/f92c085ec6355ae04258df5b76ec7570f784129d
