### ISSUE TITLE
pip install nncase-kpu无法安装

### ISSUE THREAD

**Issue by Waterium** [kendryte/nncase#1250]
![360截图20240921232719885](https://github.com/user-attachments/assets/6bb4bc18-1f7b-4464-b5a7-45e01fef6dc8)
![捕获](https://github.com/user-attachments/assets/803b502e-9424-4878-8a13-d0c2b09fe568)
![捕获2](https://github.com/user-attachments/assets/2808026a-5083-4137-8031-4b8c59c609ab)
使用pip install nncase-kpu无法安装

**Comment by sunnycase** [comment]
`pip install nncase-kpu` currently support linux platform only.
