### ISSUE TITLE
DLL load failed while importing _nncase: 找不到指定的模块。

### ISSUE THREAD

**Issue by Waterium** [kendryte/nncase#1251]
点击运行后报错
![image](https://github.com/user-attachments/assets/365ad192-77f1-484c-8585-40561e475fe8)
![image](https://github.com/user-attachments/assets/9eb88309-d015-415f-8b5a-c594df86ca96)
Python版本3.8
Windows
pip版本24
nncase-kpu版本2.9.0

**Comment by sunnycase** [comment]
Please refer to https://github.com/kendryte/nncase/issues/451
