### ISSUE TITLE
k210onnx-->kmodel转换时出错

### ISSUE THREAD

**Issue by 17168220609** [kendryte/nncase#1253]
---

### 环境信息

- **Python 版本**: Python 3.10.14
- **芯片**: k210
- **nncase 版本**: 1.9

### 使用代码

```python
import nncase
import numpy as np

def main():
    # 模型文件路径
    onnx_model_path = 'face.onnx'
    kmodel_output_path = 'face.kmodel'
    
    # 创建编译选项
    compile_options = nncase.CompileOptions()
    compile_options.target = 'k210'  # 设置目标为 k210
    compile_options.input_type = 'float32'  # 假设输入数据类型为 float32
    compile_options.output_type = 'float32'  # 假设输出数据类型也为 float32
    compile_options.input_layout = 'NHWC'  # 根据模型的输入布局设置
    compile_options.output_layout = 'NC'  # 根据模型的输出布局设置

    # 创建导入选项
    import_options = nncase.ImportOptions()
    import_options.output_arrays = ['fc1']  # 设置模型的实际输出节点名称

    # 创建编译器实例
    compiler = nncase.Compiler(compile_options)

    # 读取 ONNX 模型文件内容
    with open(onnx_model_path, 'rb') as f:
        model_content = f.read()

    # 导入 ONNX 模型
    compiler.import_onnx(model_content, import_options)

    # 编译模型
    compiler.compile()

    # 生成 kmodel 字节流
    kmodel = compiler.gencode_tobytes()

    # 将 kmodel 写入文件
    with open(kmodel_output_path, 'wb') as f:
        f.write(kmodel)

if __name__ == '__main__':
    main()
```

### 遇到的错误

```
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: _nncase.ImportOptions, arg0: std::span<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,-1>) -> None

Invoked with: <_nncase.ImportOptions object at 0x0000026FB320BB30>, ['otuput']

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

### face.onnx 模型结构

- **OpSet**: , Version: 12
- **模型的输入信息**:
  - **Name**: data
  - **Type**: tensor_type {
    - elem_type: 1
    - shape {
      - dim {
        - dim_param: "None"
        }
      - dim {
        - dim_value: 3
        }
      - dim {
        - dim_value: 96
        }
      - dim {
        - dim_value: 96
        }
      }
    }
  - **Shape**: [0, 3, 96, 96]

- **模型的输出信息**:
  - **Name**: fc1
  - **Type**: tensor_type {
    - elem_type: 1
    - shape {
      - dim {
        - dim_value: 1
        }
      - dim {
        - dim_value: 3
        }
      }
    }
  - **Shape**: [1, 3]

### 问题描述

在使用 nncase 1.9 版本将 face.onnx 模型转换为适用于 k210 芯片的 kmodel 时，遇到了 TypeError。尝试了多种方法设置 `import_options.output_arrays`，但均未成功。希望得到解决这个问题的帮助。

---

**Comment by curioyang** [comment]
compile_options.input_layout = 'NHWC'  # 根据模型的输入布局设置
    compile_options.output_layout = 'NC'  # 根据模型的输出布局设置
    import_options.output_arrays = ['fc1']  # 设置模型的实际输出节点名称
不需要配置的

**Comment by curioyang** [comment]
用户已解决
