### ISSUE TITLE
Acceleration of activation functions / quantization

### ISSUE THREAD

**Issue by janhildebrand** [kendryte/nncase#126]
Hello,

the FAQ is a bit unclear to me regarding the activation functions and quantization.

- Are the elementwise activations (ReLu, ReLu6, LeakyRelu, Sigmoid...) fully accelerated by the KPU or not?

- Is the KPU accelerating nothing at if float is set as inference type or is it still accelerating some ops?

Thank you very much for your help
Jan Hildebrand

**Comment by sunnycase** [comment]
1. Yes if they are fused into kpu conv2d.
2. KPU cannot accelerate float ops.

**Comment by janhildebrand** [comment]
Perfect, thanks for the quick help!
