### ISSUE TITLE
Disparity between KModel inference via PC and K210

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#127]
@sunnycase I am using ncc version 0.2 Beta 2

Can you confirm whether by design ncc infer and k210 are supposed to produce identical numerical values when the same image is infered using kmodel  on PC and K210.

If they are supposed to be then there is a potential issue as they are not .

I have attached the model and image files that I have used to test.

There appears to be a datashift of 1 row between the position of the object detected on K210 and ncc infer on PC.

Let me explain, assume a yolo detector with a grid size of  14x20 = 280 grid positions.

I have an image and I use it to run the inference on PC using ncc infer. I use the bin file to find out the box co-ordinates and the index of  the grid position where the object's center is located.

This comes out as 13

Next I run the same model on K210 using the same image, the detector detects the same object at  index 34 = 13+21 (almost one row down)

I choose another image where the detection happens on a 28x40 grid.

In this the ncc infer on PC detects on grid 340
K210 detects the same object on grid 380

again 1 row down 340+40 =380

The actual issue is the objectness score and x,y,w,h prediction between PC and K210 varies, however sigmoid function approximates x,y,w,h on both PC and K210 to similar values.

However objectness score has a large variance and this results in objects NOT detected on K210.

Can you have a look at raw data produced by the models against these images and let me know how to resolve it.

Is the row shift experienced in K210 detections cause for the variance?

ncc infer and tensorflow inference detect the objects at the same location on the grid.

[images.zip](https://github.com/kendryte/nncase/files/4580533/images.zip)
[binaryinference.zip](https://github.com/kendryte/nncase/files/4580538/binaryinference.zip)
[model.zip](https://github.com/kendryte/nncase/files/4580544/model.zip)

**Comment by krishnak** [comment]
@sunnycase 

How to infer a image using nncase which is stored as a uint8 array? i.e is there a way to use --data-format raw 

Currently nncase is converting a JPG or PNG using opencv(?)  for inference. The output resolution of this could be different from the uint8 array which is produced by image2c.py. so the current comparison may not be involving same set of data.

**Comment by sunnycase** [comment]
> 
> 
> @sunnycase
> 
> How to infer a image using nncase which is stored as a uint8 array? i.e is there a way to use --data-format raw
> 
> Currently nncase is converting a JPG or PNG using opencv(?) for inference. The output resolution of this could be different from the uint8 array which is produced by image2c.py. so the current comparison may not be involving same set of data.
Using uint8 array as input is supported for `--data-format raw`.

**Comment by krishnak** [comment]
@sunnycase 

I converted a image to the model input size and then saved it as UINT8 array using the following code but I get the error as below

```
Image.open(infile) as im
imagearray = np.array(im, dtype='uint8')
img = np.transpose(imagearray, [2,0,1])
np.save('imgasnparray',img.flatten())

```
```
~/nncase/ncc infer mymodel.kmodel . --dataset ./imgasnparray.npy --dataset-format raw
Fatal: Invalid dataset, file size should be 215040B, but got 215168B
```

**Comment by krishnak** [comment]
@sunnycase just to confirm I have printed the array size before it gets saved, the array size is equal to 215040B, however the npy array file size is 215168B,  the 128 extra bytes is numpy header, what format does ncc expect the raw file  to be in?, I tried CSV format, that  has more bytes than numpy. It still complains. Please advise

**Comment by sunnycase** [comment]
> 
> 
> @sunnycase just to confirm I have printed the array size before it gets saved, the array size is equal to 215040B, however the npy array file size is 215168B, the 128 extra bytes is numpy header, what format does ncc expect the raw file to be in?, I tried CSV format, that has more bytes than numpy. It still complains. Please advise

Raw binary file. Use `numpy.ndarray.tofile`

**Comment by krishnak** [comment]
@sunnycase 
I have managed to execute ncc inference with raw data, the results vary between ncc and k210, the image 
[imasbin.zip](https://github.com/kendryte/nncase/files/4611406/imasbin.zip)

array is attached for you to test it out, the model is attached in the previous message

**Comment by AIWintermuteAI** [comment]
@sunnycase I am experiencing a problem when trying to calibrate with dataset in raw format saved with numpy.ndarray.tofile.
numpy.ndarray.tofile doesn't allow appending to file - so it works great with one data point.
Unfortunately when I add more data points with following code
```
        with open("temp.bin", "ba+") as f:
            for filename in image_files_list[:num_imgs]:
                image = cv2.imread(filename)
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image = cv2.resize(image, (self._img_size[0], self._img_size[1]))
                data = np.array(backend.normalize(image), dtype=np.float32)
                data = np.expand_dims(data, 0)
                data = np.transpose(data, [0, 3, 1, 2])
                data.tofile(f)
```
I get this error on calibration step
Fatal: Invalid dataset, file size should be 196608B, but got 983040B

How does nncase determine the file size given that there is no header?

**Comment by AIWintermuteAI** [comment]
For other people having similar problem - every data point should be saved as separate .bin file in folder, then you provide the folder name to converter.
Example:
https://github.com/AIWintermuteAI/aXeleRate/blob/master/axelerate/networks/common_utils/convert.py
@sunnycase I think you can close the issue :)

**Comment by krishnak** [comment]
> For other people having similar problem - every data point should be saved as separate .bin file in folder, then you provide the folder name to converter.
> Example:
> https://github.com/AIWintermuteAI/aXeleRate/blob/master/axelerate/networks/common_utils/convert.py
> @sunnycase I think you can close the issue :)

Sorry I was away from this AI world for some time, can you let me know whether this issue has been resolved ?
