### ISSUE TITLE
转换onnx模型到k230为目标的kmodel时误差极大

### ISSUE THREAD

**Issue by ge90114b** [kendryte/nncase#1279]
**Describe the bug**
使用win11与nncase尝试转换onnx到k230用kmodel，发现余弦值为-0.06，经过官方人员的帮助，在他的环境下目标为cpu时余弦值为1，但是目标为k230时余弦值为0.2

**Origin model and code**
原模型：https://github.com/Project-Babble/ProjectBabble/tree/main/BabbleApp/Models/3MEFFB0E7MSE/onnx
编译用代码：https://p.sorasakihina.love/nncase1.py
校正集预处理：https://p.sorasakihina.love/readv.py
校正集：https://p.sorasakihina.love/output_data.txt
**Environment:**
Windows11 
nncase2.9.0
python3.10

**Comment by ge90114b** [comment]
所以在原模型不动的情况下量化模型就只能这个输出了吗？

**Comment by curioyang** [comment]
大概率是需要重训练的，尽可能在模型中增加一些BN层来约束数据范围
