### ISSUE TITLE
Face-detect with different kmodel

### ISSUE THREAD

**Issue by simonemachetti** [kendryte/nncase#128]
@sunnycase 

Hello,

I am trying to run the face-detect application, present in the kendryte/kendryte-freertos-demo repository, with a different kmodel but no one, except the existing kmodel, seams to work properly. All models are correctly loaded but than the function kpu_run() never returns.

The kmodel that I am using is a very simple model with a single convolutional layer with padding (32x32x1 input -> 32x32x1 output). The model has been generated using the Kendryte ncc tool present in the kendryte/nncase repository.

I can also confirm that the model works perfectly using the KPU functions of the kendryte/tensorflow-workshop repository.

Do you have any suggestion?

I am using a Sipeed MAix BiT board with Kendryte K210.

Thank you very much!

**Comment by sunnycase** [comment]
Can you upload your model?
