### ISSUE TITLE
Float model complains about out of memory

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#129]
I have compiled this model using nncase, which after compilation printed out   
`Main memory usage: 7741440 B`

The model is compiled with inference type float
[newfloat.kmodel.gz](https://github.com/kendryte/nncase/files/4594821/newfloat.kmodel.gz)

When I try to load the model on K210 using incbin, I get an outof memory error, the model is 1.6MB, what is the reason for the out of memory error

```
printf("\n Going to load model\n");

    // init kpu
    if (kpu_load_kmodel(&task, model_data) != 0)
    {
        printf("\nmodel init error\n");
        while (1)
            ;
    }

```
```
Going to load model
E (491383676) SYSCALL: Out of memory
```

**Comment by tjmc** [comment]
> Why I got "Out of memory" when running the model?
> 
> When you compile models, nncase will print the main memory usage which is the working memory needed to run the model. Often the model is loaded to 6MB RAM, so the total main memory usage is the working memory + size of your model.

https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md

**Comment by krishnak** [comment]
@tjmc 

Thank you for trying to help, I have read the FAQ several times

The model size is only 1.7MB and the total memory required as per ncc is below the available memory, so why does it show the error at the time of loading the model.

There are larger sized models i.e yolo20class model is around 2.7MB and it gets loaded without issues.

Hence my question is, what needs to be done specifically to load models compiled with inference-type is float. As it is unclear why it would throw an outof memory error when ncc is not complaining about lack of memory.

`    if (kpu_load_kmodel(&task, model_data) != 0)`

where is model_data defined and what is the type of it it?

**Comment by krishnak** [comment]
@sunnycase 

Currently nncase at the time of model creation prints out Main memory usage:7MB

Can you confirm whether this 7MB is including the model file size or is it excluding that?

In the FAQ as pointed out above, it says total main memory usage = working memory+model size

is there a confusion between usage of words to describe this equation?

If ncc prints main memory usage as 7MB and my model is 1.7MB  

working memory = 7MB -1.7MB

Can you confirm what ever ncc is outputs is total memory usage including model size or is it excluding model size.

**Comment by zye1996** [comment]
https://github.com/kendryte/nncase/tree/master/examples/iris this example uses float inference.
I think 7 MB includes model size. Probably float inference cannot use KPU memory for feature map storage and you have large feature map input/output?

**Comment by sunnycase** [comment]
> 
> 
> @sunnycase
> 
> Currently nncase at the time of model creation prints out Main memory usage:7MB
> 
> Can you confirm whether this 7MB is including the model file size or is it excluding that?
> 
> In the FAQ as pointed out above, it says total main memory usage = working memory+model size
> 
> is there a confusion between usage of words to describe this equation?
> 
> If ncc prints main memory usage as 7MB and my model is 1.7MB
> 
> working memory = 7MB -1.7MB
> 
> Can you confirm what ever ncc outputs as total memory usage, is it including model size or is it excluding model size.

ncc prints out working memory usage, it doesn't include model size. I will change the text to make it more clear.
