### ISSUE TITLE
Question: How can I use kmodel of cpu version?

### ISSUE THREAD

**Issue by THiyama** [kendryte/nncase#130]
Document says "-t, --target option is used to set your desired target device to run the model. cpu is the most general target that almost every platform should support.".

I consider to use this cpu target in Pytorch, Tensorflowlite or Micropython for M5stack.
I want to know whether kmodel of cpu version can do it.

And if no, where can I use this kmodel of this version?

Thank you so much.

**Comment by sunnycase** [comment]
cpu target only use standard c++ 17 and no dedicated hardwares are needed, so almost every platform should support.

**Comment by THiyama** [comment]
Thank you for your kind answering.

I want to ask you how to use this kmodel of cpu version on C++. 
If you have some idea, would you give me that.

**Comment by sunnycase** [comment]
Use it as same as kpu version.
