### ISSUE TITLE
Cannot convert 240x320 input resolution mobilenet to .kmodel

### ISSUE THREAD

**Issue by AIWintermuteAI** [kendryte/nncase#131]
Before I only worked with image inputs of same width-height, but now I'm adding support for different width-height to my model training framework, https://github.com/AIWintermuteAI/aXeleRate . 
When trying to convert MobileNet (alpha = 0.75) model with input resolution 240x320 to .kmodel with nncase 0.2.0beta2 I encounter the following error:
![IMG_20200511_165118](https://user-images.githubusercontent.com/32562299/81716991-9bf48300-94ac-11ea-989b-db3dab6b6cda.jpg)
But converting the same architecture model with input size 320x240 is successful! Plus, converting MobileNet (alpha = 0.5) model with input resolution 240x320 to .kmodel is also successful...

@sunnycase  Are you familiar with the said problem? If you need the materials to reproduce the problem, I can provide you with .tflite and .h5 files.

**Comment by sunnycase** [comment]
Please refer to https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md

**Comment by AIWintermuteAI** [comment]
Well, that doesn't really explain why MobileNet (alpha = 0.5) model with input resolution 240x320 to .kmodel is successful. 
![Capture](https://user-images.githubusercontent.com/32562299/81768276-2371de80-950d-11ea-8922-edf62b429cbe.PNG)
It is actually directly contradicts this statement in the documentation. Apart from my own project, the company I work for also uses K210 and the camera is installed in device at 90 degree angle - so this is why being able to process 240x320 images is important feature for us. 

Is there anything that can be done about this, except for reducing the size of the model? Is this a hard-coded restriction(being able to process 320x240, but not able to process 240x320 images makes me think it's a hard-coded restriction in nncase....)

**Comment by sunnycase** [comment]
It's a hardware restriction.

**Comment by sunnycase** [comment]
You can refer to
>Why I got "KPU allocator cannot allocate more memory"?
As said in the chapter "K210 and KPU", Your model's input and output featuremaps are stored at 2MB KPU RAM. Every single layer cannot exceed the limit. You can try to reduce the size of the feature maps.

**Comment by AIWintermuteAI** [comment]
Oh, well, I'll be closing this issue then and looking for a workaround.
