### ISSUE TITLE
Linking failure with conan>1.21

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#133]
I suffer some strange linking error in the final stage of nncase building, here's a gist with the log of the errors: https://gist.github.com/aclex/1ba63d75a47d0f0d7ee7d3599eeb41c1. I've experimented a little bit with it and found, that it happens with conan of versions 1.22 and upper, and the problem is caused by some `absl` library, which appears to be some OpenCV dependency. Probably that's the upstream bug and there's nothing to do with it in the nncase itself, but just to have it mentioned here in case anyone would face it in future. The only workaround I've found is to downgrade canon to version 1.21.

**Comment by sunnycase** [comment]
Linking to abseil relies on the surrounding `-Wl,--start-group` `-Wl,--end-group` with abseil libs. But conan may reorder the libs list it doesn't recongnize.
https://github.com/conan-io/conan/issues/4928

**Comment by aclex** [comment]
Yes, indeed very familiar problem. I'm just sticking with version 1.21 for now, it works fine.

**Comment by sunnycase** [comment]
Fixed in features/upgrade.
