### ISSUE TITLE
No response about kpu_run_kmodel function

### ISSUE THREAD

**Issue by PureHing** [kendryte/nncase#135]
[source_model.zip](https://github.com/kendryte/nncase/files/4694793/source_model.zip)

This is a lightly model with yolo2.
According to the modification of the official website's tiny yolo2 demo, the execution program is stuck in the function kpu_run_kmodel after loading 'source.kmodel', no response and no memory problems were reported.
source.kmodel:Main memory usage 1536000 B

Can u give me some advices?Thanks

Convert kmodel log:
./ncc compile source.tflite source.kmodel -i tflite -o kmodel --dataset calib/
1. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...
  [==================================================] 100% 18.178s
  4.5. Quantize graph...
5. Lowering...
6. Optimize Pass 3...
7. Generate code...
  Plan buffers...
  Emit code...
Main memory usage: 1536000 B

SUMMARY
INPUTS
0	Input_0	1x3x240x320
OUTPUTS
0	Identity	1x85x15x20

**Comment by yub1ng** [comment]
Hi, can I ask you how you solved this problem? I encountered the same problem.

https://github.com/kendryte/nncase/issues/154#issuecomment-667977309
