### ISSUE TITLE
RestNet is slow ?

### ISSUE THREAD

**Issue by liushuan** [kendryte/nncase#148]
I used mobilenetV1 and mobilenetV2  ，V1 interface time is:30ms but V2 interface time is 200ms. why?

**Comment by sunnycase** [comment]
`Add` can't be accelerated by KPU. See https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md#k210-and-kpu

**Comment by liushuan** [comment]
对于 深的网络无法使用ResNet结构，很难收敛，这个问题你们如何解决呢？
