### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by CVYang** [kendryte/nncase#149]
facedetect_landmark_example/image_process.c:18:10: fatal error: iomem.h: No such file or directory
 #include "iomem.h"

please!!! where and what it is?

**Comment by PureHing** [comment]
Update to the latest SDK

**Comment by CVYang** [comment]
I use the 0.5.6 SDK, But there is also error when link the target. The error is cant link hard float modules with soft float modules！！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;PureHing&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月19日(星期天) 下午5:26
收件人:&nbsp;&quot;kendryte/nncase&quot;<nncase@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVYang&quot;<401506102@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kendryte/nncase] make error (#149)

**Comment by PureHing** [comment]
[develop branch is latest](https://github.com/kendryte/kendryte-standalone-sdk)
