### ISSUE TITLE
model run error!

### ISSUE THREAD

**Issue by Russius** [kendryte/nncase#15]
我将如下模型转换为KMODEL后成功运行，如图中所示，该模型有两个输出层，尺寸分别为21x10x7=1470和21x20x14=5880。但KMODEL显示两个输出层的尺寸分别为5880和23520，请问这是为什么呢？

![模型](https://user-images.githubusercontent.com/48740672/57195839-bdfa2200-6f89-11e9-85d8-adfa60fd54d5.png)
![QQ图片20190424234831](https://user-images.githubusercontent.com/48740672/57195904-1e895f00-6f8a-11e9-9c10-f4a2b07c4a18.png)

**Comment by sunnycase** [comment]
size 的单位是字节。

**Comment by sunnycase** [comment]
Solved.
