### ISSUE TITLE
Does it support tf.nn.rnn_cell.LSTMCell on TFLite?

### ISSUE THREAD

**Issue by noahzhy** [kendryte/nncase#150]
Does it support tf.nn.rnn_cell.LSTMCell on TFLite?

**Comment by sunnycase** [comment]
LSTM is currently not supported.

**Comment by noahzhy** [comment]
Does LSTM support in the future?

**Comment by sunnycase** [comment]
> 
> 
> Does LSTM support in the future?

Yes. It's on the roadmap.
