### ISSUE TITLE
Confusion about image resolution

### ISSUE THREAD

**Issue by PureHing** [kendryte/nncase#151]
What is the maximum resolution that k210 can accept without considering KPU full acceleration? What is the root reason of the limited image size on k210.

**Comment by sunnycase** [comment]
256x512(HxW) is the hardware restriction of KPU.

**Comment by sunnycase** [comment]
If you don't need KPU acceleration, there is no limit.

**Comment by PureHing** [comment]
Got it.
Thanks.
