### ISSUE TITLE
onnx to kmodel failed: Fatal: Can't find initializer for weight input

### ISSUE THREAD

**Issue by ZhaoFour** [kendryte/nncase#156]
when i use nncase transfering models from onnx to kmodel,i occured this error: 
1.Import graph...
Fatal: Can't find initializer for weight input

**Comment by zhangyang2057** [comment]
Please use features/upgrade branch to try again.

**Comment by sunnycase** [comment]
Can your provide the onnx model?

**Comment by zhangyang2057** [comment]
No reply for a long time. 
Close it. 
If you still have a similar issue, please provide with your model file.
