### ISSUE TITLE
v0.2 compile problem

### ISSUE THREAD

**Issue by miniblob** [kendryte/nncase#158]
I use keras(tensorflow-gpu2.3.0) on ubuntu18.04,and trun to tflite,when I use nncase command like this,and then the summary only inputs and output.
![P_20200805_230312_1_1](https://user-images.githubusercontent.com/69253238/89431538-aacc9800-d772-11ea-93d3-5dee75133f41.jpg)

**Comment by sunnycase** [comment]
It's intended. https://github.com/kendryte/nncase/issues/154#issuecomment-668410166
