### ISSUE TITLE
添加prelu后，可成功转kmodel；但是在设置input-mean和input-std后，转换错误

### ISSUE THREAD

**Issue by sun-xuefei** [kendryte/nncase#159]
添加的prelu如下：
void onnx_importer::convert_op_PRelu(const NodeProto &node)
{
    assert(node.output().size() == 1);

    const auto &input { node.input()[0] };
    const auto &output { node.output()[0] };
    const auto &slope { node.input()[1] };
    std::cout << "input_name: " << input << " output_name: " << output << " slope_name: " << slope << std::endl;
    auto &&in_shape = get_shape(input);
    auto &&slope_shape { get_shape(slope) };
    const auto initializer_value = get_initializer(slope);
    xt::xarray<float> &&slope_value { xt::zeros<float>(slope_shape) };
    slope_value = to<xt::xarray<float>>(initializer_value.value());
    const auto &alpha { graph_.emplace<constant>(get_datatype<float>(), slope_shape, span_from(slope_value)) };
    xt::xarray<float> &&zero_value { xt::zeros<float>(in_shape) };

    auto zero { graph_.emplace<constant>(get_datatype<float>(), in_shape, span_from(zero_value)) };

    auto max = graph_.emplace<binary>(binary_max, in_shape, zero->output().shape(), value_range<float>::full());
    auto mul = graph_.emplace<binary>(binary_mul, slope_shape, max->output().shape(), value_range<float>::full());

    max->input_b().connect(zero->output());
    mul->input_b().connect(max->output());
    input_tensors_.emplace(&max->input_a(), input);
    input_tensors_.emplace(&mul->input_a(), slope);
    output_tensors_.emplace(output, &max->output());
}
转换错误：
[图片]

**Comment by sun-xuefei** [comment]
错误提示：
4.5. Quantize graph...
Fatal: _Map_base::at

**Comment by sun-xuefei** [comment]
void onnx_importer::convert_op_Gemm(const NodeProto &node)
{
    assert(node.input().size() >= 2 && node.input().size() <= 3);
    assert(node.output().size() > 0 && node.output().size() <= 5);

    const auto alpha_attr { get_attribute<float>(node, "alpha") };
    const float alpha { alpha_attr ? alpha_attr.value() : 1.0f };

    const auto beta_attr { get_attribute<float>(node, "beta") };
    const float beta { beta_attr ? beta_attr.value() : 1.0f };

    const auto transA_attr { get_attribute<int>(node, "transA") };
    const bool transA { transA_attr ? static_cast<bool>(transA_attr.value()) : false };

    const auto transB_attr { get_attribute<int>(node, "transB") };
    const bool transB { transB_attr ? static_cast<bool>(transB_attr.value()) : false };

    const auto &input_A { node.input()[0] };
    const auto &input_B { node.input()[1] };
    const auto input_B_type { get_datatype(input_B).value() };

    const auto &output { node.output()[0] };

    const auto &add_transpose {
        [this](const auto &input) {
            const auto input_type { get_datatype(input).value() };
            const auto &input_shape { get_shape(input) };

            axis_t perm(input_shape.size());
            std::iota(begin(perm), end(perm), 0);
            std::reverse(begin(perm), end(perm));

            return graph_.emplace<transpose>(input_type, input_shape, perm);
        }
    };

    auto transA_op { transA ? add_transpose(input_A) : nullptr };
    auto transB_op { transB ? add_transpose(input_B) : nullptr };

    const auto &As_shape { transA ? transA_op->output().shape() : get_shape(input_A) };
    const auto &Bs_shape { transB ? transB_op->output().shape() : get_shape(input_B) };

    const auto &bias(xt::zeros<float>({ As_shape.back() }));

    auto alpha_constant { graph_.emplace<constant>(alpha) };
    auto alpha_A_op { graph_.emplace<binary>(binary_mul, alpha_constant->output().shape(), As_shape, value_range<float>::full()) };
    auto A_B_op { graph_.emplace<matmul>(alpha_A_op->output().shape(), Bs_shape, bias, value_range<float>::full()) };

    if (node.input().size() > 2)
    {
        const auto &input_C { node.input()[2] };
        auto beta_constant { graph_.emplace<constant>(beta) };
        auto beta_C_op { graph_.emplace<binary>(binary_mul, beta_constant->output().shape(), get_shape(input_C), value_range<float>::full()) };
        auto A_B_C_op { graph_.emplace<binary>(binary_add, A_B_op->output().shape(), beta_C_op->output().shape(), value_range<float>::full()) };

        beta_C_op->input_a().connect(beta_constant->output());
        A_B_C_op->input_a().connect(A_B_op->output());
        A_B_C_op->input_b().connect(beta_C_op->output());

        input_tensors_.emplace(&beta_C_op->input_b(), input_C);

        output_tensors_.emplace(output, &A_B_C_op->output());
    }
    else
    {
        output_tensors_.emplace(output, &A_B_op->output());
    }

    alpha_A_op->input_a().connect(alpha_constant->output());
    A_B_op->input_a().connect(alpha_A_op->output());

    if (transA)
    {
        alpha_A_op->input_b().connect(transA_op->output());
        input_tensors_.emplace(&transA_op->input(), input_A);
    }
    else
    {
        input_tensors_.emplace(&alpha_A_op->input_b(), input_A);
    }

    if (transB)
    {
        A_B_op->input_b().connect(transB_op->output());
        input_tensors_.emplace(&transB_op->input(), input_B);
    }
    else
    {
        input_tensors_.emplace(&A_B_op->input_b(), input_B);
    }
}

**Comment by sunnycase** [comment]
Please try the latest nncase.
