### ISSUE TITLE
model output error

### ISSUE THREAD

**Issue by Russius** [kendryte/nncase#16]
您好，我改变输入，但模型的输出始终没有变化, 是否我的模型转换为KMODEL后有问题？
![4HLDXFLK6VMTX59P)_%H(RN](https://user-images.githubusercontent.com/48740672/57565264-30855a80-73ed-11e9-8969-49eb79db0aad.png)
![VYHZL`2_79O5V28)29IQ9@Q](https://user-images.githubusercontent.com/48740672/57565275-6296bc80-73ed-11e9-9f52-6aab19c1210a.png)
![模型](https://user-images.githubusercontent.com/48740672/57565266-3844ff00-73ed-11e9-85b5-acf3c69cb01b.png)

**Comment by sunnycase** [comment]
模型经过训练了吗？使用什么数据做 ncc 的 dataset 参数？

**Comment by Russius** [comment]
> 模型经过训练了吗？使用什么数据做 ncc 的 dataset 参数？

模型转换前在PC上运行正常。用resize后的训练集图片做dataset

**Comment by sunnycase** [comment]
你说的没有变化指的是对比了每一个字节？

**Comment by Russius** [comment]
> 你说的没有变化指的是对比了每一个字节？

抱歉是我的问题，还是有变化的，只不过二者的输出都有大量重复数据，比如我截选的这一部分，0.066519 出现了很多次，变更输入后新的输出也有大量重复的0.066519
![image](https://user-images.githubusercontent.com/48740672/57666191-c14c7800-7631-11e9-832b-1731abe0780d.png)

**Comment by sunnycase** [comment]
对比这个没有意义，跑完 yolo 层再做比较吧

**Comment by sunnycase** [comment]
If you have any questions, please reopen.
