### ISSUE TITLE
how to build kmodel v3

### ISSUE THREAD

**Issue by pvqthang** [kendryte/nncase#167]
Hi friends,
I try to build a kmodel v3 because that's the only way I can load a big model according to this instruction :
https://github.com/sipeed/MaixPy_scripts/tree/master/machine_vision/load_big_model
But eventually this error message displayed:
ValueError: [MAIXPY]kpu: load_flash error:2002, ERR_KMODEL_VERSION: only support kmodel V3/V4 now
How can I generate kmodel v3 using ncc compiler?

**Comment by shanejohnpaul** [comment]
You have to use the previous release of nncase (v0.1.0 RC5 will give a v3 kmodel).

**Comment by pvqthang** [comment]
> You have to use the previous release of nncase (v0.1.0 RC5 will give you a v3 kmodel).

@shanejohnpaul Thanks alot for your reply!!
