### ISSUE TITLE
Fatal: Data type of input "102" is not supported

### ISSUE THREAD

**Issue by pvqthang** [kendryte/nncase#169]
I try to re-train this example (https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB) with my test dataset. After that I convert it into onnx format , then simplfy the onnx model. Then i use nncase to compile kmodel but it failed like this . I think this type of error alot people encountered before. Please help! Thanks
1. Import graph...
input base_net.0.1.running_mean target shape: [ 16 1 1]
input base_net.0.1.running_var target shape: [ 16 1 1]
input base_net.0.1.weight target shape: [ 16 1 1]
input base_net.0.1.bias target shape: [ 16 1 1]
input base_net.1.1.running_mean target shape: [ 16 1 1]
input base_net.1.1.running_var target shape: [ 16 1 1]
input base_net.1.1.weight target shape: [ 16 1 1]
input base_net.1.1.bias target shape: [ 16 1 1]
input base_net.1.4.running_mean target shape: [ 32 1 1]
input base_net.1.4.running_var target shape: [ 32 1 1]
input base_net.1.4.weight target shape: [ 32 1 1]
input base_net.1.4.bias target shape: [ 32 1 1]
input base_net.2.1.running_mean target shape: [ 32 1 1]
input base_net.2.1.running_var target shape: [ 32 1 1]
input base_net.2.1.weight target shape: [ 32 1 1]
input base_net.2.1.bias target shape: [ 32 1 1]
input base_net.2.4.running_mean target shape: [ 32 1 1]
input base_net.2.4.running_var target shape: [ 32 1 1]
input base_net.2.4.weight target shape: [ 32 1 1]
input base_net.2.4.bias target shape: [ 32 1 1]
input base_net.3.1.running_mean target shape: [ 32 1 1]
input base_net.3.1.running_var target shape: [ 32 1 1]
input base_net.3.1.weight target shape: [ 32 1 1]
input base_net.3.1.bias target shape: [ 32 1 1]
input base_net.3.4.running_mean target shape: [ 32 1 1]
input base_net.3.4.running_var target shape: [ 32 1 1]
input base_net.3.4.weight target shape: [ 32 1 1]
input base_net.3.4.bias target shape: [ 32 1 1]
input base_net.4.1.running_mean target shape: [ 32 1 1]
input base_net.4.1.running_var target shape: [ 32 1 1]
input base_net.4.1.weight target shape: [ 32 1 1]
input base_net.4.1.bias target shape: [ 32 1 1]
input base_net.4.4.running_mean target shape: [ 64 1 1]
input base_net.4.4.running_var target shape: [ 64 1 1]
input base_net.4.4.weight target shape: [ 64 1 1]
input base_net.4.4.bias target shape: [ 64 1 1]
input base_net.5.1.running_mean target shape: [ 64 1 1]
input base_net.5.1.running_var target shape: [ 64 1 1]
input base_net.5.1.weight target shape: [ 64 1 1]
input base_net.5.1.bias target shape: [ 64 1 1]
input base_net.5.4.running_mean target shape: [ 64 1 1]
input base_net.5.4.running_var target shape: [ 64 1 1]
input base_net.5.4.weight target shape: [ 64 1 1]
input base_net.5.4.bias target shape: [ 64 1 1]
input base_net.6.1.running_mean target shape: [ 64 1 1]
input base_net.6.1.running_var target shape: [ 64 1 1]
input base_net.6.1.weight target shape: [ 64 1 1]
input base_net.6.1.bias target shape: [ 64 1 1]
input base_net.6.4.running_mean target shape: [ 64 1 1]
input base_net.6.4.running_var target shape: [ 64 1 1]
input base_net.6.4.weight target shape: [ 64 1 1]
input base_net.6.4.bias target shape: [ 64 1 1]
input base_net.7.1.running_mean target shape: [ 64 1 1]
input base_net.7.1.running_var target shape: [ 64 1 1]
input base_net.7.1.weight target shape: [ 64 1 1]
input base_net.7.1.bias target shape: [ 64 1 1]
input base_net.7.4.running_mean target shape: [ 64 1 1]
input base_net.7.4.running_var target shape: [ 64 1 1]
input base_net.7.4.weight target shape: [ 64 1 1]
input base_net.7.4.bias target shape: [ 64 1 1]
input base_net.8.1.running_mean target shape: [ 64 1 1]
input base_net.8.1.running_var target shape: [ 64 1 1]
input base_net.8.1.weight target shape: [ 64 1 1]
input base_net.8.1.bias target shape: [ 64 1 1]
input base_net.8.4.running_mean target shape: [ 128 1 1]
input base_net.8.4.running_var target shape: [ 128 1 1]
input base_net.8.4.weight target shape: [ 128 1 1]
input base_net.8.4.bias target shape: [ 128 1 1]
input base_net.9.1.running_mean target shape: [ 128 1 1]
input base_net.9.1.running_var target shape: [ 128 1 1]
input base_net.9.1.weight target shape: [ 128 1 1]
input base_net.9.1.bias target shape: [ 128 1 1]
input base_net.9.4.running_mean target shape: [ 128 1 1]
input base_net.9.4.running_var target shape: [ 128 1 1]
input base_net.9.4.weight target shape: [ 128 1 1]
input base_net.9.4.bias target shape: [ 128 1 1]
input base_net.10.1.running_mean target shape: [ 128 1 1]
input base_net.10.1.running_var target shape: [ 128 1 1]
input base_net.10.1.weight target shape: [ 128 1 1]
input base_net.10.1.bias target shape: [ 128 1 1]
input base_net.10.4.running_mean target shape: [ 128 1 1]
input base_net.10.4.running_var target shape: [ 128 1 1]
input base_net.10.4.weight target shape: [ 128 1 1]
input base_net.10.4.bias target shape: [ 128 1 1]
input base_net.11.1.running_mean target shape: [ 128 1 1]
input base_net.11.1.running_var target shape: [ 128 1 1]
input base_net.11.1.weight target shape: [ 128 1 1]
input base_net.11.1.bias target shape: [ 128 1 1]
input base_net.11.4.running_mean target shape: [ 256 1 1]
input base_net.11.4.running_var target shape: [ 256 1 1]
input base_net.11.4.weight target shape: [ 256 1 1]
input base_net.11.4.bias target shape: [ 256 1 1]
input base_net.12.1.running_mean target shape: [ 256 1 1]
input base_net.12.1.running_var target shape: [ 256 1 1]
input base_net.12.1.weight target shape: [ 256 1 1]
input base_net.12.1.bias target shape: [ 256 1 1]
input base_net.12.4.running_mean target shape: [ 256 1 1]
input base_net.12.4.running_var target shape: [ 256 1 1]
input base_net.12.4.weight target shape: [ 256 1 1]
input base_net.12.4.bias target shape: [ 256 1 1]
Fatal: Data type of input "242" is not supported

**Comment by xiaxinkai** [comment]
how do you solved it?

**Comment by wei8171023** [comment]
how do you solved it?
