### ISSUE TITLE
--dataset Dataset path,  when the output format is k210model

### ISSUE THREAD

**Issue by carry-xz** [kendryte/nncase#17]
nice work，thanks！
Why do we need to set up dataset for k210 model?  Is it to set the size of network entrance?
What should I do when I take pictures directly from the camera as input ？

**Comment by Russius** [comment]
是为了模型量化时辅助nncase进行动态范围估计
放一些训练或测试的图片

**Comment by sunnycase** [comment]
These images are used for quantizing activations. You can pick tens ~ hundreds of training images to form this dataset.
