### ISSUE TITLE
tflite2kmodel.sh: line 5: ./ncc/ncc: Permission denied（when I convert tflite to kmodel)

### ISSUE THREAD

**Issue by agenthong** [kendryte/nncase#173]
tflite2kmodel.sh: line 5: ./ncc/ncc: Permission denied

It happens when I convert tflite to kmodel. How can I solve it

**Comment by shanejohnpaul** [comment]
Is that all the error that you get? Also, check if ncc is present inside the ncc folder.

**Comment by sunnycase** [comment]
Please report it to Sipeed.

**Comment by iGangao** [comment]
I also met this problem。you can amend the file of get_nncase.sh and run it.
Edit this to,
#!/bin/bash
mkdir -p ncc
mkdir -p workspace
mkdir -p images
mkdir -p log
cd ncc
wget https://github.com/kendryte/nncase/releases/download/v0.1.0-rc5/ncc-linux-x86_64.tar.xz
tar -Jxf ncc-linux-x86_64.tar.xz
rm ncc-linux-x86_64.tar.xz
echo "download nncase ok!"
then you can try again。
like this `bash tflite2kmodel.sh workspace/m.tflite`
