### ISSUE TITLE
Confused about input-std and input-mean

### ISSUE THREAD

**Issue by shanejohnpaul** [kendryte/nncase#174]
According to the table [here](https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md), the defaults are 1 and 0 for input-std and input input-mean. And the table says the input range is [0,1]. 

I'm using MaixPy, which in turn uses OpenMV. I think, here RGB images have a range from 0 to 255. And my neural network requires the input to be in the same range (0-255). So does this mean I have to set input-std and input-mean as 0.0039216 and 0 respectively? 
If this is the case, what's reason behind the default values? And if the input type is uint8 (which is the case mostly) the preprocessing doesn't make sense. Can someone clarify this?

Another doubt:
Which is better - training the network with a rescale layer to normalize the inputs or train it with normalized inputs without the rescale layer? And does the preprocessing has something to do with the second case? If so how to use it? For example, while training, if I normalized the inputs between [-1, 1] how to use this preprocessing option?

**Comment by michaelteo** [comment]
Just recently got into k210, so don't know too much as well. But I believe you need to set input-std as 0.0039216 ( note this value is ~1/255) and input-mean as 0.

Based on the doc - https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md

_"...nncase will use opencv to read your images and autoscale to the desired input size of your model. If the input has 3 channels, ncc will convert images to RGB float tensors [0,1] in NCHW layout."_

So the inputs will now be between [0-1] vs original [0-255] range. Based on the docs  input-std and input-mean are used to renormalize data back to [0-255] using `y = (x - mean) / std formula.`
