### ISSUE TITLE
PyTorch -> ONNX -> kmodel | Fatal: inputs are not compatible to broadcast

### ISSUE THREAD

**Issue by yliess86** [kendryte/nncase#176]
Hi, I am currently playing with a **k210** and would like to deploy my own model on the chip. 

I tried to export a custom model from **PyTorch** to **kmodel** without success.
The model is built using **PyTorch 1.6.0** and then converted to **onnx** format with **opcode 11**.
When I try to compile the model using the latest **ncc** linux build, it fails and outputs the following:

```sh
$ ncc compile model.onnx model.kmodel -i onnx -o kmodel -t k210
1. Import graph...
Fatal: inputs are not compatible to broadcast
``` 

The model is tested with **Onnx-runtime** and works like a charm.
Model input is an image of size `(3, 256, 256)`.
Here is the model if you want to check it out [model.onnx](https://bit.ly/30EPlRp).

Thank you for your help, regards.

**Comment by michaelteo** [comment]
I think you might have hit the input shape limit as per https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md

_Input feature maps smaller than or equal to 320x240(WxH) and output features map larger than or equal to 4x4(WxH) and channels are between 1 to 1024 are supported._

And apparently it's a hardware restriction https://github.com/kendryte/nncase/issues/131#issuecomment-629042242

**Comment by KuoEuran** [comment]
@michaelteo Hi, I am new to the k210. However, I meet the error when I use the Model input of  image size (3, 224, 224). I don't know how to solve the problem. If you have any idea, please contact me, thank you.

**Comment by michaelteo** [comment]
@KuoEuran - I am not really an expert :)  

Is it the same error message? Maybe you can check this again: https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md. 
See if your model meets all the constraints. 

This is useful for visualizing Models - https://netron.app/

**Comment by KuoEuran** [comment]
Yes, I have use Netron to see my model, I think there are no layers meet
the hardware restricts. How did you solve error? Just change the first
layer of input ?

Michael Teo ***@***.***> 於 2021年6月26日 週六 上午9:57 寫道：

**Comment by KuoEuran** [comment]
This is my tflite tks
  1624694573886_yolov4-tiny-224-int8.tflite
<https://drive.google.com/file/d/1jthire8wJ1lGEG4vr0cqAi_XFsAvz6Y9/view?usp=drivesdk>


郭育綸 ***@***.***> 於 2021年6月26日 週六 上午10:41 寫道：

**Comment by sunnycase** [comment]
@KuoEuran Can you try v1.0 CI build?

**Comment by zhangyang2057** [comment]
The error "Fatal: inputs are not compatible to broadcast" cannot be reproduced on latest features/upgrade branch.  The onnx model can be built succfully now. But there is a strange issue that the input shape of this onnx model is batch_size * 3 * 256 * 256, batch_size will be imported as -1 by default.

**Comment by zhangyang2057** [comment]
The input shape of model.onnx has dynamic shape  as [batch_size * 3 * 256 * 256]

You can refer to parse_model_input_output function in tests/onnx_test_runner.py to use onnxsim to specify the input shape manually. 
I can build the model.onnx with nncase master branch now.
