### ISSUE TITLE
When I used the nncase to convert tflite model to kmodel ,errors occurs  

### ISSUE THREAD

**Issue by drldgithub20xx** [kendryte/nncase#179]
error: -i blocked
error: -o blocked
error: --dataset blocked
Use -h to see help info
![image](https://user-images.githubusercontent.com/56077621/95882335-2a4a9900-0dac-11eb-81fa-025d779f462c.png)

**Comment by shahbaz-momi** [comment]
you need to follow the input format exactly, so it would be like:

`ncc compile test.tflite test.kmodel -i tflite -o kmodel -t k210 --dataset images`

**Comment by drldgithub20xx** [comment]
> you need to follow the input format exactly, so it would be like:
> 
> `ncc compile test.tflite test.kmodel -i tflite -o kmodel -t k210 --dataset images`

Yes , that's right, thanks for your reply.  确实是这样的，我一开始用错了，谢谢你的提醒
