### ISSUE TITLE
Failed to convert onnx model to kmodel.

### ISSUE THREAD

**Issue by akashdev2016** [kendryte/nncase#182]
Hello, everyone.
I'm trying to convert onnx model to kmodel for k210.
When I use `ncc` tool, it can't import graph of onnx model.
Appreciate, if you can help me.
[sim.zip](https://github.com/kendryte/nncase/files/5444257/sim.zip)

**Comment by zhangyang2057** [comment]
Sorry for so late to reply to you.
I can build your onnx model succfully now. Please use the latest ncc to try again.

**Comment by zhangyang2057** [comment]
For onnx model, you'd better use onnxsim to simplify it.
I can use the latest ncc tool to build the simplified sim.onnx successfully.

No reply for a long time. Close it now.
If you have any problem, please summit a new issue. Thanks.
