### ISSUE TITLE
Fatal: Not supported ONNX opcode: Clip

### ISSUE THREAD

**Issue by LingBlopdreame** [kendryte/nncase#184]
Hi, i' d like to use yolov5s model in my k210. When i use the ncc, i get the problem:

Fatal: Not supported ONNX opcode: Clip

can someone tell me what problems it cause?

**Comment by uniartisan** [comment]
K210 only support the follow ONNX opcodes : 
https://github.com/kendryte/nncase/blob/master/docs/onnx_ops.md

**Comment by evenuo** [comment]
@LingBlopdreame Did you get your yolov5s working on k210?

**Comment by zhangyang2057** [comment]
The Clip op for onnx has been supported in features/upgrade branch.
Please feel free to summit a new issue if you have any problem.
