### ISSUE TITLE
Transposed convolution acceleration

### ISSUE THREAD

**Issue by valentin7121** [kendryte/nncase#191]
Is there support for accelerating the Conv2DTranspose by the KPU?
The [FAQ(English)](https://github.com/kendryte/nncase/blob/master/docs/FAQ_EN.md) says that:
`TransposeConv2D, nncase will replace it with a SpaceToBatch + KPUConv2D + BatchToSpace.`

But, when I compile simply one-layer model:
```
inputs = tf.keras.layers.Input(shape=(128, 128, 1))
x = tf.keras.layers.Conv2DTranspose(filters=32, kernel_size=(3, 3), strides=(1, 1), padding="same")(inputs)
model = tf.keras.models.Model(inputs, x)
```
the Conv2DTranspose still remains the Conv2DTranspose (as I can see in `ir_optimize_3.dot`). No KPUConv2D used.

I have measured inference time on K210 both for `--target=cpu` and `--target=k210` and they equals.

Can I enable Conv2DTranspose acceleration somehow?

**Comment by sunnycase** [comment]
There is a mistake in the document. The `TransposeConv2D` should be `DilatedConv2D`.
