### ISSUE TITLE
ONNX unsupported Shape opcode

### ISSUE THREAD

**Issue by latesh** [kendryte/nncase#193]
Getting the following error while trying to compile ONNX model:

`Fatal: Not supported ONNX opcode: Shape`

I have compiled `ncc` from `aclex-nncase` fork  on `onnx_clip` branch. 

Hope that this could be supported soon 🙂

**Comment by sunnycase** [comment]
Try [onnx-simplifier](https://github.com/daquexian/onnx-simplifier) to simplify your onnx model.

**Comment by zhangyang2057** [comment]
The Shape op for onnx will be supported in a short time.

**Comment by zhangyang2057** [comment]
1. Shape op has been supported.
2. You'd better use [onnx-simplifier ](https://github.com/daquexian/onnx-simplifier) to simplify your onnx model which will eliminate Shape op normally.
