### ISSUE TITLE
Split layer not supported

### ISSUE THREAD

**Issue by shahbaz-momi** [kendryte/nncase#198]
Hello,

Was trying to get Yolov4-tiny compiled to a kmodel, however was running into the issue of the split layer being unsupported. Currently I have it compiled as an onnx model and on the latest branch of the code the rest of the layers seem to be implemented.

Is there any timeline of the split layer being implemented?

**Comment by shahbaz-momi** [comment]
I noticed that the Caffe importer seems to have a Split operator implemented, however neither the onnx or tflite importers have it implemented.

**Comment by sunnycase** [comment]
nncase is now under heavy refactoring. More ops will be supported in May and June.

**Comment by shahbaz-momi** [comment]
Ok makes sense. However I ended up implementing the 2 required layers (Split and Upsample) on my own and the kmodel seems to be compiling and inferring correctly. However I wanted to implement these layers on the K210 as well but noticed that the lib_sipeed_kpu.a seem to be closed source (only library provided, no source). Is there any mechanism for me to manually implement those operations on the K210 as well? Thanks

**Comment by sunnycase** [comment]
If you just implement `Split` and `Upsample` in Caffe importer then you don't need to modify K210 runtime.

**Comment by shahbaz-momi** [comment]
Thanks I'll look into that

**Comment by shahbaz-momi** [comment]
> If you just implement `Split` and `Upsample` in Caffe importer then you don't need to modify K210 runtime.

Even if I were to, I would still need new ops for them in the runtime so I would have to modify it no?
