### ISSUE TITLE
如何转换caffe模型？

### ISSUE THREAD

**Issue by cjnewstar111** [kendryte/nncase#2]
感谢您提供的工具。在readme里面，说是可以用ncc -i caffe *** 来转换caffe的模型。但是我从release下载的工具名字叫toco.exe，而不是ncc。另外使用toco.exe --input_format="caffe"报错，说不支持的格式。请问使用toco.exe如何将caffe模型转化成kmodel模型？其实虽然caffe现在没落了，但是很多企业由于历史原因，计算机视觉这块还在用caffe，所以对caffe模型的支持还是比较重要的。谢谢，盼复。

**Comment by sunnycase** [comment]
解压以后根目录就有ncc.exe，toco.exe在bin目录。

**Comment by cjnewstar111** [comment]
thanks
