### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by Vivianyzw** [kendryte/nncase#20]
Could you please supply a CMakeLists.txt  for compiling your yolo_v2 demo?

when I compiling the project, the error occurred as follows:
`CMake Error: The source directory "X:/kendryte/nncase-master/examples/20classes_yolo/k210/kpu_20classes_example"  does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by sunnycase** [comment]
You should compile it with kendryte standalone SDK.

**Comment by Vivianyzw** [comment]
Thank you ! It can be complied using kendryte standalone SDK.
