### ISSUE TITLE
cmake报错，有部分库下载不了

### ISSUE THREAD

**Issue by E11word** [kendryte/nncase#201]
ERROR: Error downloading file https://raw.githubusercontent.com/google/cctz/8768b6d02283f6226527c1a7fb39c382ddfb4cec/CMakeLists.txt: 'HTTPSConnectionPool(host='raw.githubusercontent.com', port=443):  Max retries exceeded with url: /google/cctz/8768b6d02283f6226527c1a7fb39c382ddfb4cec/CMakeLists.txt (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))'

ortools/7.3@sunnycase/testing: WARN: Package is corrupted, removing folder: /home/xie/.conan/data/ortools/7.3/sunnycase/testing/package/2a90beb0135c6667645e4c6db92f69184d7f1a65
ERROR: Binary package not found: 'ortools/7.3@sunnycase/testing:2a90beb0135c6667645e4c6db92f69184d7f1a65'

**Comment by sunnycase** [comment]
你网络有问题，开代理吧

**Comment by E11word** [comment]
ERROR: Binary package not found: 'ortools/7.3@sunnycase/testing:2a90beb0135c6667645e4c6db92f69184d7f1a65'
CMake Error at cmake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:485 (conan_cmake_install)
  CMakeLists.txt:19 (conan_cmake_run)
下到这里报这个错误了，是不是这个库没有啊？谢谢
