### ISSUE TITLE
编译 Binary package not found  -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by E11word** [kendryte/nncase#202]
ERROR: Binary package not found: 'ortools/7.3@sunnycase/testing:2a90beb0135c6667645e4c6db92f69184d7f1a65'
CMake Error at cmake/conan.cmake:399 (message):
Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:485 (conan_cmake_install)
  CMakeLists.txt:19 (conan_cmake_run)
-- Configuring incomplete, errors occurred!

ERROR: libjpeg/9c@bincrafters/stable: Error in source() method, line 41
        tools.get("{}/files/jpegsrc.v{}.tar.gz".format(self.homepage, self.version), sha256=sha256)
        ConanException: sha256 signature failed for 'jpegsrc.v9c.tar.gz' file.
 Provided signature: 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
Computed signature: 1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730
麻烦帮忙看下这怎么解决？谢谢
请问一下有没有配好的docker环境，能提供一下吗？

**Comment by shahbaz-momi** [comment]
Building in release mode seemed to work for me. You have to manually change the signature though for libjpeg.

**Comment by E11word** [comment]
Thanks, I change the signature though for libjpeg and than cmake success.
compile error:
nncase/third_party/xtensor/include/xtensor/xexpression.hpp:168:88: internal compiler error: Segmentation fault
         xtl::disjunction< std::is_base_of<B<E>, F<E>>, std::is_base_of<B<F<E>>, F<E>>> 
how to solve the problem.

**Comment by shahbaz-momi** [comment]
Hmm which branch are you on?

**Comment by E11word** [comment]
master branch

**Comment by sunnycase** [comment]
Fixed.
