### ISSUE TITLE
Fatal: Not supported tflite opcode: DEQUANTIZE

### ISSUE THREAD

**Issue by laolihaile** [kendryte/nncase#203]
how to fix the issue "Fatal: Not supported tflite opcode: DEQUANTIZE",please

**Comment by t01051** [comment]
hi，I also encountered this problem, which was later solved by using toco tool in the command line
`toco --output_file model.tflite --keras_model_file model.h5  --output_arrays output --input_shapes 1,224,224,3 --out_format TFLITE --inference_type FLOAT --input_type FLOAT --experimental_new_converter=False`

**Comment by laolihaile** [comment]
> 嗨，我也遇到了这个问题，后来通过在命令行中使用toco工具解决了
> `toco --output_file model.tflite --keras_model_file model.h5 --output_arrays output --input_shapes 1,224,224,3 --out_format TFLITE --inference_type FLOAT --input_type FLOAT --experimental_new_converter=False`

I'll try it,THANY YOU very much,!

**Comment by KuoEuran** [comment]
@t01051 I use the tflite.float 16 model to convert kmodel, and I also meet the problem, can you show me how to solve the problem clearly? thank you

**Comment by t01051** [comment]
> @t01051 I use the tflite.float 16 model to convert kmodel, and I also meet the problem, can you show me how to solve the problem clearly? thank you

I guess your parameters are not set correctly.I used NCC V1.0 and the model was built using TensorFlow V2.2. At the beginning of the parameter "-- experimental_new_converter" is not used, the results toco tflite model by converting an error in the NCC tools.This parameter seems to affect the format of the transformation model, which is related to TensorFlow. If you're interested, check out Toco's Readme.
