### ISSUE TITLE
I have problem that is converting tflite to kmodel

### ISSUE THREAD

**Issue by brkktl** [kendryte/nncase#218]
v0.1.0-rc5 is working very good. I can convert all my models but i've got problem in maixpy ide.

![HATA](https://user-images.githubusercontent.com/67025480/119135249-d8a37480-ba46-11eb-9a8d-dde93ba323c7.png)
 
so i need kmodel v3/v4 model son upload v0.2.0-beta4 but not it's not working.

![Screenshot from 2021-05-21 12-36-54](https://user-images.githubusercontent.com/67025480/119134969-7f3b4580-ba46-11eb-9a7a-e77452a52ae7.png)

How can i solve this problem?

**Comment by sunnycase** [comment]
Seems you are using nncase v0.2, the command line has changed.

**Comment by sunnycase** [comment]
Close as inactive.
