### ISSUE TITLE
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1

### ISSUE THREAD

**Issue by laurentopia** [kendryte/nncase#22]
using this https://github.com/kendryte/nncase/releases/tag/v0.1.0-rc5, drag and dropping it in ./ncc
and calling ncc with ./ncc/ncc
I'm getting this error
`Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1`

**Comment by sunnycase** [comment]
Try COREHOST_TRACE=1 ./ncc/ncc

**Comment by sunnycase** [comment]
If you have any questions, please reopen.
