### ISSUE TITLE
multi-output model output order changes on different machaines, dockers.

### ISSUE THREAD

**Issue by xiaxinkai** [kendryte/nncase#235]
Hi, Dear nncase Team

I use ncc to convert multi-output caffe model to kmodel.
I use master branch, commit id:88420d8d667ec0670676c7396958209314ce5bbd.

my multi-output caffe model has 3 outputs: score, bbox, landmark.
I found on my machine, the output order is: score, bbox, landmark.
following is the ncc compile log:
```
SUMMARY
INPUTS
0	Input_0	1x3x160x160
OUTPUTS
0	score	1x1050x2
1	bbox	1x1050x4
2	landmark	1x1050x10
```

But in my docker, the output order is: landmark，bbox，score.
following is the ncc compile log:
```
SUMMARY
INPUTS
0	Input_0	1x3x160x160
OUTPUTS
0	landmark	1x1050x10
1	bbox	1x1050x4
2	score	1x1050x2
```

So I can't get the same model on others' pc or docker.
Is it a bug?

**Comment by sunnycase** [comment]
Will be solved when caffe tests added to this repo.

**Comment by sunnycase** [comment]
This bug should be solved, you can try the latest nncase.
