### ISSUE TITLE
Unsupported image channels: 1

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#239]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported image channels: 1
Aborted (core dumped)

I use nncase 1.0 tool to infer a model, however it always throws the error as shown above. I use default NCHW input layout which is the same as my model specialized. It can compile successfully, but when inferring it will give the above error. I have tried to infer a gray image and a rgb image individually to check if the error is relevant to the number of image channel, but failed. I also try to change the input layout into NHWC, but also failed. Is it a bug?

**Comment by curioyang** [comment]
@annosoo 
Sorry for replying to you so late!
Please confirm whether your model input shape support gray image.
Use opencv to read your image and check it's layout.

OR, upload your model file and a test image for me.
