### ISSUE TITLE
[Solved] Fatal: inputs are not compatible to concat 

### ISSUE THREAD

**Issue by KuoEuran** [kendryte/nncase#246]
Hi, I am using the tflite model convert to kmdoel, but I meet the error of Fatal: inputs are not compatible to concat. My tflite model of input is 1x224x224x3, and I think this is not over the k210 hardware restrict. Does anyone know how to solve the error? thanks

**Comment by KuoEuran** [comment]
@sunnycase Hi, do you have any idea about the error?

**Comment by michaelteo** [comment]
@KuoEuran - This might be useful reference. Looks like the same issue. https://github.com/kendryte/nncase/issues/178

**Comment by KuoEuran** [comment]
@michaelteo  I have looked for it, but I still don't get the solution. Thank for you replying

**Comment by sunnycase** [comment]
Can you provide the tflite?

**Comment by KuoEuran** [comment]
1624694573886_yolov4-tiny-224-int8.tflite
<https://drive.google.com/file/d/1jthire8wJ1lGEG4vr0cqAi_XFsAvz6Y9/view?usp=drivesdk>
Hi,
   Did you find any weird about my tflite file? I use my darknet weights
convert to pb, and convert pb to tflite.I use the code on yolov4 to
tensorflow https://github.com/hunglc007/tensorflow-yolov4-tflite

Please give me some advice, thank you.


sunnycase ***@***.***> 於 2021年6月26日 週六 下午2:51 寫道：

**Comment by KuoEuran** [comment]
> Can you provide the tflite?
This is my tflite 
<https://drive.google.com/file/d/1jthire8wJ1lGEG4vr0cqAi_XFsAvz6Y9/view?usp=drivesdk>
