### ISSUE TITLE
v0.1-rc5 getting "permission denied" [Errno 13] in ubuntu 20.04

### ISSUE THREAD

**Issue by gretzer** [kendryte/nncase#247]
Hey There,

I'm trying to run the tutorial for local training from sipeed:
https://wiki.sipeed.com/soft/maixpy/en/course/ai/train/local.html

I tried it on a standalone ubuntu machine and also on a ubuntu 20.04 virtual machine you get from the microsoft store.

I always get this error:
[ERROR]:  failed: TrainFailReason.ERROR_INTERNAL, node error:[Errno 13] Permission denied: '/home/user/AI-Training/maix_train/instance/../tools/ncc/ncc_v0.1/ncc'

googled for several days but can't sort it out.
I did chmod -R 777 on all the directories... so permission should not be the problem!?!??!

any ideas?

**Comment by sunnycase** [comment]
Please report it to Sipeed.
