### ISSUE TITLE
What is the version of kmodel produced by nncase 1.0 CI?

### ISSUE THREAD

**Issue by Balocre** [kendryte/nncase#252]
I have been trying to compile a model with the nncase continuous integration, I had no problem nor error during compilation. Yet when I try to load the model in MaixPy with `kpu.load(0x300000)` I get :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: [MAIXPY]kpu: load error:2015, ERR_UNKNOWN
```
and `kpu.load_flash(0x00300000, 0, 0, 0x4000)` gives :

```
SPI freq 16384 Hz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: [MAIXPY]kpu: load_flash error:2002, ERR_KMODEL_VERSION: only support kmodel V3/V4 now
```

The model is still the one referenced in y previous issue : https://github.com/kendryte/nncase/issues/248

I am running `maixpy_v0.6.2_54_g897214100_minimum_with_kmodel_v4_support.bin` on my MaixDuino, so V3 and V4 kmodels should be supported.

**Comment by sunnycase** [comment]
KModel V5

**Comment by Balocre** [comment]
Do you know by any chance if MaixPy is gonna support V5 soon? And could you tell me which nis the last nncase version that compiles to V3/4?

**Comment by sunnycase** [comment]
@Balocre Sorry but I don't know, you can open an issue in MaixPy.
|nncase version|kmodel version|
|--|--|
|v0.1~|v3|
|v0.2~|v4|
|v1.0~|v5|

**Comment by Balocre** [comment]
Thanks
