### ISSUE TITLE
cmake failed 

### ISSUE THREAD

**Issue by chenhu66** [kendryte/nncase#260]
**Describe the bug**
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  NAME_MISMATCHED (missing: REQUIRED_VARS VERSION_VAR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
  CMakeLists.txt:44 (find_package)

**To Reproduce**
follow the build process in the doc till the cmake line

**Expected behavior**
cmake successful

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - nncase version: master HEAD
 - Conan version 1.38.0

**Additional context**

**Comment by sunnycase** [comment]
Please upgrade cmake to latest version.
