### ISSUE TITLE
量化失败

### ISSUE THREAD

**Issue by kanglinchen** [kendryte/nncase#264]
**Describe the bug**
量化失败

**To Reproduce**
./ncc.exe compile deepgauge_MobilenetL2_simp.onnx deepgauge_MobilenetL2_simp_quant.kmodel -i onnx -t k210 --input-type uint8 --output-type float32 --quant-type uint8 --dataset samp

**Expected behavior**
量化应该成功

**Origin model and code**
看附件

**Environment (please complete the following information):**
 - OS: Windows
 - nncase version [e.g. v1.0.0.dev24]
 - DL Framework [e.g. TensorFlow 2.5.0]

**Additional context**
看附件
[example.zip](https://github.com/kendryte/nncase/files/6764191/example.zip)

**Comment by sunnycase** [comment]
导出 onnx 的时候请指定一个固定的输入 shape。
