### ISSUE TITLE
About the kmodel testing on pc 

### ISSUE THREAD

**Issue by KuoEuran** [kendryte/nncase#265]
Hi,
    I have a kmodel convert from my tfite life, and I use the ncc infer to generate .bin file. like
![image](https://user-images.githubusercontent.com/70742122/124561680-bd62bc00-de70-11eb-9aa9-7b43c6a3f201.png)
However, I don't know how to test my kmodel which is correct similiar to my pc's result?
Isn't there any methods to do the testing? tks.

**Comment by sunnycase** [comment]
Sorry but I can't exactly understand your issue. You can use Chinese to describe.

**Comment by KuoEuran** [comment]
@sunnycase 感謝您的回覆,我的意思是現在我有轉出kmodel後,但是我該如何去驗證說我的kmodel bounding 出來的結果是正確的? 然後上面那個是我用ncc infer轉出的.bin 檔案,請問該如何在電腦上去驗證我的kmodel bouding的能力?

**Comment by zhen8838** [comment]
请参考[tflite与kmodel输出对比](https://zhen8838.github.io/2019/07/07/tflite-kmodel/)

**Comment by KuoEuran** [comment]
@zhen8838 您好,我有使用這支程式測過,但是在解析wh有問題
![image](https://user-images.githubusercontent.com/70742122/124601229-2dd20300-de9a-11eb-9976-1f2cd650e95a.png)
然後把它註解掉之後,kmodel是有東西的
請問tflite的問題是出在哪?謝謝

**Comment by zhen8838** [comment]
代码并不一定适配的你的模型，你需要根据自己的模型来修改

**Comment by KuoEuran** [comment]
@zhen8838 您好,想請教個問題,我現在試著把我的kmodel 弄上Maxiduino,但目前使用kpu.load_flash會發生
![image](https://user-images.githubusercontent.com/70742122/125158374-5c562380-e1a3-11eb-8156-fde3f095db95.png)
而使用kpu.load從SD卡中讀我的kmodel時會發生
![image](https://user-images.githubusercontent.com/70742122/125158408-86a7e100-e1a3-11eb-9d4c-bb2ce1774fe8.png)
我的模型大小大約5.6MB
請問您有遇到過類似問題嗎?謝謝

**Comment by zhen8838** [comment]
把模型再缩小一些


发自我的iPhone

------------------ Original ------------------
From: KuoEuran ***@***.***&gt;
Date: 周六,7月 10,2021 17:24
To: kendryte/nncase ***@***.***&gt;
Cc: 郑启航 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kendryte/nncase] About the kmodel testing on pc  (#265)





 
@zhen8838 您好,想請教個問題,我現在試著把我的kmodel 弄上Maxiduino,但目前使用kpu.load_flash會發生
 
 而使用kpu.load從SD卡中讀我的kmodel時會發生
 
 我的模型大小大約5.6MB
 請問您有遇到過類似問題嗎?謝謝

**Comment by KuoEuran** [comment]
@zhen8838 您好,因為我看說KPU.LOAD_FLASH的方法可以LOAD比較大的模型,您的意思是指5.6MB的模型是不適用於KPU.LOAD_FLASH?還有就是大概需要縮小到多少呢?謝謝

**Comment by zhen8838** [comment]
这个我不太清楚，你需要问一下sipeed的开发人员


发自我的iPhone

------------------ Original ------------------
From: KuoEuran ***@***.***&gt;
Date: 周一,7月 12,2021 15:39
To: kendryte/nncase ***@***.***&gt;
Cc: 郑启航 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kendryte/nncase] About the kmodel testing on pc  (#265)





 
@zhen8838 您好,因為我看說KPU.LOAD_FLASH的方法可以LOAD比較大的模型,您的意思是指5.6MB的模型是不適用於KPU.LOAD_FLASH?還有就是大概需要縮小到多少呢?謝謝

**Comment by sunnycase** [comment]
Closed as inactive.
