### ISSUE TITLE
images

### ISSUE THREAD

**Issue by kimchicanh** [kendryte/nncase#27]
Hi,

I do not understand images\： quantization dataset images . What is it and how I can get it ???

Thanks

**Comment by sunnycase** [comment]
See https://github.com/kendryte/nncase/issues/17#issuecomment-491663755

**Comment by kimchicanh** [comment]
@sunnycase 
Thanks for your comment so ./images is folder of many quantized images or it is just a config

Thanks

**Comment by sunnycase** [comment]
Some of the training images. See the example https://github.com/kendryte/nncase/tree/master/examples/20classes_yolo/images
