### ISSUE TITLE
Alignment issues on k210

### ISSUE THREAD

**Issue by louareg** [kendryte/nncase#276]
Hello,

I get a "core dump: illegal instruction" in the k210_runtime_module::visit(const kpu_conv2d_options &op) function on the kendrye.

It is raised by an alignment check :     CHECK_WITH_ERR(layer.kernel_calc_type_cfg.data.active_addr % 256 == 0, std::errc::invalid_argument);

What I did is, from the [kendryte-standalone-sdk repo ](https://github.com/kendryte/kendryte-standalone-sdk), I removed the old nncase and used instead the current version. I fixed some memory alignment issues in interpreter::load_model.

 - Compiled on Ubuntu20.04
 - master@nncase  , commit 345f3c6, from Jul 8 13:09
 - running on k210

**Comment by sunnycase** [comment]
What have you fixed?

**Comment by louareg** [comment]
calls to span_reader::get_ref and calls to span_reader::read raised SYSCALL: misaligned load. I replaced them by calls to read_unaligned. I can send you the files if you wish to see the details.

**Comment by sunnycase** [comment]
@louareg You can open a pull request.

**Comment by louareg** [comment]
Done. But so this only fixes the alignment issues for model loading.  k210_runtime_module::visit(const kpu_conv2d_options &op)  still raises  "core dump: illegal instruction"

**Comment by sunnycase** [comment]
@louareg Can you provide the tflite?

**Comment by louareg** [comment]
Sorry i was on holiday. Here it is. Let me know if you need the calibration dataset.
[model.zip](https://github.com/kendryte/nncase/files/6998497/model.zip)

**Comment by kervel** [comment]
Hello,

We are investigating this further. I wonder if there is a documented way to integrate the new nncase in the kendryte standalone toolchain. We discovered the global initializers are not being called the way we do (eg host_tensor_type->data is 0x0 which is only possible when the global constructors are not called). 

Also, the runtime_tensor_impl that is used (host_runtime_tensor_impl) has an empty vtable on the device despite being properly initialized. This makes all virtual function calls crash.

Are we on a dead end trying this ? Did anyone else try to combine the new nncase with the standalone SDK ?

greetings,
Frank

**Comment by sunnycase** [comment]
> 
> 
> Hello,
> 
> We are investigating this further. I wonder if there is a documented way to integrate the new nncase in the kendryte standalone toolchain. We discovered the global initializers are not being called the way we do (eg host_tensor_type->data is 0x0 which is only possible when the global constructors are not called).
> 
> Also, the runtime_tensor_impl that is used (host_runtime_tensor_impl) has an empty vtable on the device despite being properly initialized. This makes all virtual function calls crash.
> 
> Are we on a dead end trying this ? Did anyone else try to combine the new nncase with the standalone SDK ?
> 
> greetings,
> Frank

Just unzip the `runtime-k210.zip` to sdk/lib/nncase/v1
