### ISSUE TITLE
Request for support ONNX opcode 'LSTM'

### ISSUE THREAD

**Issue by jsjeong** [kendryte/nncase#278]
Hi all,

I recently encountered an error message when converting ONNX model to Kmodel.
```
Fatal: Not supported ONNX opcode: LSTM
```
I found #150. Is it still on your roadmap?

Thank you.

**Comment by sunnycase** [comment]
LSTM is supported in #259, but it's only for Caffe now. LSTM for ONNX will be supported later.

**Comment by jsjeong** [comment]
I will gladly wait for it. :pray:
Thank you!
