### ISSUE TITLE
Model with MatMul IR operator leads to std::terminate() on K210

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#288]
I'm experimenting with getting the ONNX model (trained to classify MNIST digits) to work on K210 with all the nice recent updates in nncase and found that all the ops imported seems to work fine during the inference the resulting kmodel on K210 device, except when it contains `Gemm` ONNX operator, which is imported to `MatMul` operator of nncase IR language and some more operators after all the transformations. Maybe, I miss something, so decided to report this, maybe you would notice the problem.

**To Reproduce**
1. ../install/bin/ncc compile mnist_cnn.onnx mnist_cnn_k210.kmodel -i onnx --dataset ../../mnist-sample/ -t k210 --dump-ir --dump-dir testdump
2. Add the resulting kmodel to the [demo program](https://github.com/aclex/k210_sample_program).

**Expected behavior**
Debugging timing output on the UART console.

**Origin model and code**
The models are uploaded to the [demo program](https://github.com/aclex/k210_sample_program), named `mnist_cnn_k210.kmodel` and `mnist_cnn.onnx` for Kmodel and ONNX formats, respectively.

**Environment (please complete the following information):**
 - OS: Gentoo, x86_64
 - nncase version 1.0.0-91413fc-dirty
 - DL Framework Pytorch-1.8.1

**Additional context**
Here's also a snippet on PyTorch to produce the ONNX model like this:

```python
import sys

import torch
from torch import nn

from torchinfo import summary


class Net3(nn.Sequential):
	def __init__(self):
		super().__init__(
			nn.Flatten(),
			nn.Linear(784, 64),
			nn.ReLU()
		)


def main():
	model = Net3()

	dummy_input = torch.randn(1, 1, 28, 28).to(dtype=torch.float32)

	summary(model, input_size=(1, 1, 28, 28))

	torch.onnx.export(
		model,
		dummy_input,
		"mnist_cnn.onnx",
		input_names=["img"],
		output_names=["digit"],
		opset_version=11)


if __name__ == "__main__":
	try:
		main()
	except KeyboardInterrupt:
		sys.exit(1)
```

**Comment by zhen8838** [comment]
@aclex I made a test,but no errors on my `compare-patch` branch. 
The test code and [log file](https://drive.google.com/file/d/1guaErZZQgLZ3A7k5v8Ou8T56HJhxOI1Y/view?usp=sharing):
```python
import pytest
import torch
import torch.nn as nn

from onnx_test_runner import OnnxTestRunner


class Net3(nn.Sequential):
    def __init__(self):
        super().__init__(
            nn.Flatten(),
            nn.Linear(784, 64),
            nn.ReLU()
        )


def _make_module():
    return Net3()


def test_simple(request):
    module = _make_module()
    runner = OnnxTestRunner(request.node.name)
    model_file = runner.from_torch(module, (1, 1, 28, 28))
    runner.run(model_file)

```

**Comment by aclex** [comment]
Yes, it also works fine in CPU inference for me, but fails on K210. So it's very interesting to see your results tomorrow.

By the way, forgot to attach it, here's the UART output from the test program on K210, when it fails:
```bash
input data uploaded
mnist_cnn_k210.kmodel
System start
terminate called without an active exception
W (129021758) SYSCALL: sys_exit called by core 0 with 0x1
```

**Comment by zhen8838** [comment]
Sorry for the late. Now I only have an m1 MacBook, so I lost time on the build RISC-V compiler. I got the same issue, maybe the `stackvm` has something broken. 
I have started looking for problems.

**Comment by zhen8838** [comment]
@aclex Hi, I update the nncase runtime lib in SDK.  Now you can try your model(need recompile with latest nncase).

**Comment by aclex** [comment]
Thank you very much for the fix, it indeed works just fine now with recent updates! Can confirm it working on K210 as well.
