### ISSUE TITLE
WARN: Conv2D_16 Fallback to float conv2d due to weights divergence.

### ISSUE THREAD

**Issue by KuoEuran** [kendryte/nncase#292]
**Describe the bug**
A clear and concise description of what the bug is
我在轉換時發生了 
WARN: Conv2D_16 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_17 Fallback to float conv2d due to weights divergence.
WARN: Conv2D_22 Fallback to float conv2d due to weights divergence.
原本2.8MB的tflite檔案變成了6.1MB的kmodel
我想是我替換成Separable convolutional layer, 但我只替換了兩層layer ,卻有了三層WARN
然後我爬到一篇是說可以設置 --weights-quantize-threshold,但感覺沒有效果
![image](https://user-images.githubusercontent.com/70742122/126036266-e67eb16c-89ad-4218-b1eb-70cce3111ea8.png)
拜託幫忙了,謝謝

**Comment by sunnycase** [comment]
Please attach your origin model.
