### ISSUE TITLE
Fatal: Shape and data size don't match

### ISSUE THREAD

**Issue by laodu233** [kendryte/nncase#293]
**Describe the bug**
在执行以下命令之后
`ncc.exe compile yolo.onnx yolo.kmodel -i onnx -t k210 --dataset train_img`

出现报错：
`Fatal: Shape and data size don't match`

注：yolo.onnx文件是由yolov5s模型的pt格式权重文件转换而来。

**Environment (please complete the following information):**
 - OS: WIN10
 - nncase version [最新的ci版本]
 - DL Framework [e.g. pytorch1.7.0]

**Additional context**
[model.zip](https://github.com/kendryte/nncase/files/6834980/model.zip)
train_img图片集未知原因不能上传
train_img 中共有181张jpg格式的图片，分辨率为1920*1080

**Comment by aclex** [comment]
Done a small investigation, according to `git bisect` it started happening after f339f92af6a2b921f15a57c9b978a8935c9144fb, probably due to changes in `src/importer/onnx/ops/constant.cpp`.

**Comment by zhangyang2057** [comment]
1. This is a constant bug, which will be fixed at https://github.com/kendryte/nncase/pull/295
2. You'd better use onnxsim to simplify your onnx model before using ncc.

**Comment by zhangyang2057** [comment]
Is there any update?

**Comment by aclex** [comment]
I think, it happened to work for me after the update you've mentioned, so I consider it solved now.

**Comment by zhangyang2057** [comment]
No response for a long time.
Close it.
