### ISSUE TITLE
转换caffe模型报错: NnCase.Converter.Model.OutputConnector was not present in the dictionary

### ISSUE THREAD

**Issue by cjnewstar111** [kendryte/nncase#3]

**Comment by cjnewstar111** [comment]
我将一个mobilenet的caffe模型使用该工具转换成k210模型的时候，报错NnCase.Converter.Model.OutputConnector was not present in the dictionary。我的模型应该没有问题，因为我们公司一直用这个模型，最后一层是softmax层，输出类别概率。但是转换的时候报了这个错误，不甚理解

**Comment by sunnycase** [comment]
你能提供一下转换出错的模型吗？

**Comment by sunnycase** [comment]
Closed as no response. If you have any questions, feel free to reopen.
