### ISSUE TITLE
是否支持UpSampling2D 和 Deconvolution ？

### ISSUE THREAD

**Issue by CuberFan** [kendryte/nncase#30]
是否支持UpSampling2D 和 Deconvolution ？ 另外，pooling是否支持kernel=(3,3)的呢？

**Comment by sunnycase** [comment]
1. UpSampling2D 可以用 ResizeNearestNeighbor 或者 ResizeBilinear 代替。
2. Deconvolution 不支持。
3. Pooling 支持任意 kernel size。

**Comment by sunnycase** [comment]
Deconvolution 已在 v0.2.0 beta1 支持。
