### ISSUE TITLE
编译tflite模型显示：shapes must be same, but get [1] and []

### ISSUE THREAD

**Issue by luxianlebron** [kendryte/nncase#302]
**Describe the bug**
编译tflite模型显示：shapes must be same, but get [1] and []

**To Reproduce**
使用以下命令行时报以上错误：
ncc compile lprnet.tflite lprnet.kmodel -i tflite --dataset lpr_quantative_data --inference-type uint8

**Expected behavior**
![image](https://user-images.githubusercontent.com/82278841/127307228-064b4bed-9339-4a06-9fbf-8d2de31630fe.png)

**Origin model and code**
这是我转换的模型 
[lprnet.zip](https://github.com/kendryte/nncase/files/6892246/lprnet.zip)

**Environment (please complete the following information):**
 - OS:  win10
 - nncase version： 0.2.0 beta4
 - DL Framework： tensorflow 2.5

**Comment by luxianlebron** [comment]
希望能得到帮助，谢谢！

**Comment by sunnycase** [comment]
试一下最新版 https://github.com/kendryte/nncase/actions/runs/1070459308

**Comment by luxianlebron** [comment]
> 试一下最新版 https://github.com/kendryte/nncase/actions/runs/1070459308

我使用了最新 ubuntu 版本， 显示了以下错误：
![image](https://user-images.githubusercontent.com/82278841/127448829-94769796-4575-42d4-a606-697f6f4c17df.png)

**Comment by luxianlebron** [comment]
> > 试一下最新版 https://github.com/kendryte/nncase/actions/runs/1070459308
> 
> 我使用了最新 ubuntu 版本， 显示了以下错误：
> ![image](https://user-images.githubusercontent.com/82278841/127448829-94769796-4575-42d4-a606-697f6f4c17df.png)

我使用 --dump-ir 参数生成 .dot 文件，查看之后发现在 tf.reduce_mean 输入输出中发生错误。
![image](https://user-images.githubusercontent.com/82278841/127457580-fc7e3678-f6dc-4b56-8be0-d89f2e8b1079.png)
之后在 reduce_mean 之前加上 transpose ,
![image](https://user-images.githubusercontent.com/82278841/127457722-babec00e-af72-4ef2-b2be-9a8fc287c4fd.png)
最终转换成功

**Comment by zhangyang2057** [comment]
@luxianlebron  There are two bugs about both transpose and reduce mean.  I fixed it,  but there is something wrong when running it with tflite interpreter. Do you train your model successfully?

**Comment by zhangyang2057** [comment]
@luxianlebron The patch has been merged. You can check the test case at tests/transform/test_transpose_reduce_motion_transform.py

If you have any problem, please submit a new issue.

**Comment by luxianlebron** [comment]
> @luxianlebron There are two bugs about both transpose and reduce mean. I fixed it, but there is something wrong when running it with tflite interpreter. Do you train your model successfully?

Thank you for your reply！Because the dataset is large, the model was only trained one epoch to verify whether it can be converted for convenience.

**Comment by luxianlebron** [comment]
> @luxianlebron The patch has been merged. You can check the test case at tests/transform/test_transpose_reduce_motion_transform.py
> 
> If you have any problem, please submit a new issue.

Thank you for your help! The model has been successfully converted
