### ISSUE TITLE
Not supported tflite opcode: EXPAND_DIMS when Conv1D

### ISSUE THREAD

**Issue by noahzhy** [kendryte/nncase#305]
**Describe the bug**
When I convert keras model to kmodel, the `ncc` shows `Fatal: Not supported tflite opcode: EXPAND_DIMS`.
TF-Lite Converter works but add expandsdims operation.

**Origin model and code**
Any keras model with Conv1D operation.

**Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - nncase version: NNCase v0.2.0 Beta4
 - DL Framework: TensorFlow 2.5.0

**Additional context**
To solve with it, just replace Conv1D to Conv2D, the reference [here](https://stackoverflow.com/a/66971484).

**Comment by zhangyang2057** [comment]
@noahzhy Could you upload your tflite model?

**Comment by noahzhy** [comment]
I think it is a common problem that any model with conv1d tensorflow ops.

**Comment by zhangyang2057** [comment]
I use tensorflow 2.4.0 to construct conv1d node in a graph then convert it to tflite,  but there are Reshape and Conv2D ops instead of Expand_DIMS and Conv2D.

**Comment by zhangyang2057** [comment]
with tf 2.5.0, there is still no EXPAND_DIMS op.
![conv1d.png](https://i.loli.net/2021/08/20/nYkG47DLOySTBhQ.png)

**Comment by noahzhy** [comment]
The issue was happened in convert .h5 to .tflite file. The model is refer to this [link](https://stackoverflow.com/questions/66664484/tensorflow-lite-on-arduino-nano-33-ble-didnt-find-op-for-builtin-opcode-expa).

convert code here.
```python
def h5_to_tflite(saved_model_dir, tflite_path='model.tflite'):
    model = tf.keras.models.load_model(saved_model_dir)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    open(tflite_path, "wb").write(tflite_model)
````

error here.
![Snipaste_2021-08-20_18-52-51](https://user-images.githubusercontent.com/15160788/130216484-20ab8552-7d04-4842-b3ec-488cda90b49d.png)

**Comment by zhangyang2057** [comment]
@noahzhy I could reproduce the issue with keras and fix it. Please use the latest nncase to try again.
