### ISSUE TITLE
`vulkan-loader` leads to Conan failure during the configuration

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#309]
New dependency of `vulkan-loader` (if I get it right) seems to failing the Conan part of the project configuration on my system, so no way to build the project at the moment. Apparently it was added with adding Vulkan module skeleton, but I only found this now. 

Here's a tail of the output:
```bash
vulkan-loader/1.2.182: Not found in local cache, looking in remotes...
vulkan-loader/1.2.182: Trying with 'sunnycase'...
vulkan-loader/1.2.182: Trying with 'conan-center'...
ERROR: Failed requirement 'vulkan-loader/1.2.182' from 'conanfile.py'
ERROR: Unable to find 'vulkan-loader/1.2.182' in remotes
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:53 (conan_cmake_run)
```

I believe, it's just some slight misconfiguration somewhere or some issues of my system.

Here's my versions:
Gentoo x86_64, GCC 10.3.0, CMake 3.18.5, Conan 1.36.0

**Comment by sunnycase** [comment]
`conan-center` is deprecated, you should use `conancenter`.

**Comment by aclex** [comment]
Thank you! That worked, `conan-center` was the only default apparently due to the dated version of Conan on my system. Now it works just fine.
