### ISSUE TITLE
About the int8 convert order

### ISSUE THREAD

**Issue by KuoEuran** [kendryte/nncase#311]
Hi, 
    I am using a int8 tflite model to run on k210, unfortunately, it fails. When I use the nncase2.0 beta4 to convert my komdel, I use the int8 tflite file for input. Is the kmodel different to the kmodel which is converted from float32 tflite file? 
     I can use my int8 tflite file convert to int 8 kmodel, however, the float32 tflite file can't convert to int8 kmodel, it will show the error message: Fatal: inputs are not compatible to concat.

**Comment by sunnycase** [comment]
Please describe your issue using the default issue template, thanks.

**Comment by KuoEuran** [comment]
@sunnycase  OK, I have added a new issue
