### ISSUE TITLE
Fatal: Shapes must be same

### ISSUE THREAD

**Issue by BOGUENSONG** [kendryte/nncase#320]
Hello. 

I used latest ncc file for compile my onnx model.
then, error occured 

nncase Command Line Tools 1.0.0.dev426
Copyright 2019-2021 Canaan Inc.
1. Import graph...
Fatal: Shapes must be same:
Slice_171(Slice)[Slice]->Div_172(binary_div)[Binary] has shape mismatch: [1,4420,1]->[1,4420,2]

when i use old version ncc like NNCase v0.2.0 Beta4,  then compile success. 
but use latest ncc,  cannot compile model.

please help.
here is my model 
[onnxmodel.zip](https://github.com/kendryte/nncase/files/6965846/onnxmodel.zip)

**Comment by zhangyang2057** [comment]
This is a bug caused by int64 to int in slice attribute. 
I will fix it soon.

**Comment by zhangyang2057** [comment]
@BOGUENSONG The bug has been fixed. Please use the latest nncase to try again.

**Comment by BOGUENSONG** [comment]
thx :)
