### ISSUE TITLE
onnx 模型转换时，inputs are not compatible to concat

### ISSUE THREAD

**Issue by luxianlebron** [kendryte/nncase#325]
**Describe the bug**
onnx 模型转换kmodel时，inputs are not compatible to concat
![image](https://user-images.githubusercontent.com/82278841/129148721-58fe9af6-7e0d-457f-8ca6-2056351ce0e0.png)

**To Reproduce**
转换时的命令行：./ncc compile /home/luxian/tf/models/lprnet95.onnx /home/luxian/tf/lprnet.kmodel --dataset /home/luxian/tf/lpr_quantitative_data --quant-type uint8 -t k210 -i onnx

**Origin model and code**
模型文件和模型定义代码[model.zip](https://github.com/kendryte/nncase/files/6973292/model.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - nncase version v1.0.0.dev30
 - DL Framework pytorch1.5

**Comment by zhangyang2057** [comment]
1. The onnxruntime with 1.8.0 will report the following error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangyang/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/zhangyang/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from lprnet95.onnx failed:Node (MaxPool_3) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size
`
2. The **MaxPoo**l op in lprnet95.onnx has 3D shape for kernel_shape/pad/strides, but we only support 2D now.

**Comment by luxianlebron** [comment]
> 1. The onnxruntime with 1.8.0 will report the following error
>    `Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/home/zhangyang/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers)   File "/home/zhangyang/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from lprnet95.onnx failed:Node (MaxPool_3) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size `
> 2. The **MaxPoo**l op in lprnet95.onnx has 3D shape for kernel_shape/pad/strides, but we only support 2D now.

Thank you for your reply！

**Comment by zhangyang2057** [comment]
@luxianlebron Close this issue as there are something wrong with the onnx model.
