### ISSUE TITLE
examples下的yolox有bug

### ISSUE THREAD

**Issue by datou666** [kendryte/nncase#359]
按照readme操作存在bug

测试流程如下：
1.下载代码git clone https://github.com/kendryte/nncase.git
git log查看当前commit id=222471b72f004d6d0290d2abfbf8a24fa7870353
![图片1](https://user-images.githubusercontent.com/35911833/131940406-0cc65baf-92da-4ee3-b0e9-d2f5a27a39b0.png)

2.从源码编译cmake .. -G "Visual Studio 16 2019" -A x64 -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Debug，将bin文件夹添加到环境变量Path
3.进入examples/yolox，按照README.md操作
4.编译浮点模型验证模型并推理得到模型结果
```
ncc compile model/yolox_nano_224.onnx k210/yolox_detect_example/yolox_nano_224_float.kmodel -i onnx -t k210 --input-mean 0.48 --input-std 0.225
ncc infer k210/yolox_detect_example/yolox_nano_224_float.kmodel tmp/yolox_nano_float --dataset images --dataset-format image --input-mean 0.48 --input-std 0.225
```
5.解析浮点输出并检查
执行python tools/decoder.py tmp/yolox_nano_float/dog.bin，输出正常。
![图片2](https://user-images.githubusercontent.com/35911833/131940580-69dbe7d4-6747-4fb7-b347-d9a5ef4c1b4c.png)
执行python tools/decoder.py tmp/yolox_nano_float/person.bin，**输出异常**。
![图片3](https://user-images.githubusercontent.com/35911833/131940586-17eb72c8-09cb-4cd6-809f-350916ed71a5.png)

6.编译定点模型验证模型并推理得到模型结果
`ncc compile model/yolox_nano_224.onnx k210/yolox_detect_example/yolox_nano_224.kmodel -i onnx -t k210 --dataset ../20classes_yolo/images --input-mean 0.48 --input-std 0.225`
![图片4](https://user-images.githubusercontent.com/35911833/131940628-b63d3125-1497-49f6-af8e-4fb614fa0fd6.png)
修改代码piecewise_regression.cpp第39行，改为if (std::isnan(p0.y) || std::isnan(p1.y) || std::isinf(p0.y) || std::isinf(p1.y))
重新编译ncc后，再次编译定点模型并推理得到模型结果
`ncc infer k210/yolox_detect_example/yolox_nano_224.kmodel tmp/yolox_nano --dataset images --dataset-format image --input-mean 0.48 --input-std 0.225`

7.解析定点输出并检查
执行python tools/decoder.py tmp/yolox_nano/person.bin，**输出异常**。
![图片5](https://user-images.githubusercontent.com/35911833/131940651-0535554c-a132-4a34-8c7c-4c5ae6a53ec4.png)
执行python tools/decoder.py tmp/yolox_nano/dog.bin，**输出异常**。
![图片6](https://user-images.githubusercontent.com/35911833/131940676-038858fe-29eb-4889-a7af-6163522b48b3.png)

**Environment (please complete the following information):**
 - OS: win10
 - nncase version: commit id=222471b72f004d6d0290d2abfbf8a24fa7870353

**Comment by zhen8838** [comment]
这个应该是量化的问题

**Comment by zhen8838** [comment]
新版本的nncase添加了新的预处理方式,我需要更新一下yolox的例子

**Comment by datou666** [comment]
@zhen8838 ，对于浮点输出，为啥python tools/decoder.py tmp/yolox_nano_float/dog.bin没问题，但是python tools/decoder.py tmp/yolox_nano_float/person.bin的结果不对呢？

**Comment by zhen8838** [comment]
因为更新了新的预处理,原来的写法不起作用了.我会提交一个新的用例.

**Comment by datou666** [comment]
@zhen8838 ，我更新的yolox的代码，python tools/compile.py model/yolox_nano_224.onnx yolox_nano_224_quant.kmodel --legacy --imgs_dir ../20classes_yolo/images/ --target k210，依然还是闪退。安装的是nncase-1.0.0.20210902-cp38-cp38-win_amd64.whl

**Comment by zhen8838** [comment]
我还有一些修改需要提交,等会儿一并pr

**Comment by zhen8838** [comment]
你好,可以尝试一下最新的[binary文件](https://github.com/kendryte/nncase/actions/runs/1211770930). 由于python打包耗时太长,因此你需要手动添加pythonpath 指向 binary文件夹下面的python

**Comment by zhen8838** [comment]
要避免新的pythonpath和之前的nncase whl包存在冲突,需要先把之前版本卸载. 同时pythonpath和ld library path也需要指向binary 文件夹下的lib

**Comment by datou666** [comment]
@zhen8838 ，按照你的方法进行了测试，有些问题请教下：
1.demo的量化
python tools/compile.py model/yolox_nano_224.onnx yolox_nano_224_quant.kmodel --imgs_dir ../20classes_yolo/images/ --legacy --target k210
python tools/simulate.py yolox_nano_224_quant.kmodel ../20classes_yolo/images/dog.bmp
我发现这个是可以正常显示结果的。
但是，我的模型按照这个量化却没法显示正确结果，必须去掉--legacy来量化才能正常显示结果。

2.如果量化的时候加上--no_preprocess，依旧还是会闪退，或许python脚本中可以删除该选项，强制preprocess。

3.如果模型量化的时候不用--legacy，那yolox.cpp代码是否需要更新？

**Comment by zhen8838** [comment]
1. 旷世最新更新了yolox模型,demo模型是老版本的,你用的应该是新版的. 新版的模型输入是BGR, 0~255, 老的模型输入是 RGB 归一化后输入. 可以参考[预处理函数](https://github.com/Megvii-BaseDetection/YOLOX/blob/16ac8536a74a31c6c5070d18cb319acbed319eea/yolox/data/data_augment.py#L222). 我提供的脚本是支持这两个模型的,和yolox官方一致,使用--legacy进行选择.

2. --no_preprocess对于用户来说不需要指定, 那个是我自己用于debug,可以考虑删除. 

3. 目前对于两个版本的模型,我都是统一都输入 RGB 0~255 uint8的图片数据. nncase中设置preprocess之后,会自动在模型输入处插入预处理的算子,因此yolox.cpp应该是不需要更新的,只需要为不同的模型设置正确的预处理方法即可.

**Comment by datou666** [comment]
@zhen8838 ，谢谢解答

**Comment by datou666** [comment]
@zhen8838 ,我在k210开发板上跑yolox例子，打印预测时间：
model: 1538.551 ms , postprocess: 25.251 ms 
我自己的模型打印时间：
model: 1253.404 ms , postprocess: 21.413 ms 

这个预测时间1.2-1.5秒太长了，是正常情况吗？

**Comment by zhen8838** [comment]
大约1000ms是正常的.

1. yolox nano其中有3个pooling层不支持kpu计算
2. 两个分支相加的binary操作没有优化,用的是reference实现.

建议设计类似于20classyolo这样的模型

**Comment by datou666** [comment]
你是指用这个zhen8838/K210_Yolo_framework去训练模型吗，这个工程用的tensorflow1.x，我这边装的是2.x版本，要换成1.x版本的话，cuda/cudnn得重新安装了。

**Comment by zhen8838** [comment]
只需要修改模型的结构,并不依赖于别的代码.  你可以用任何你想用的框架.

**Comment by rogerkuo1981** [comment]
我使用官方的nano模型测试的时候会报错type mismatch: [f32]->[u8]
命令行如下：
PS D:\Python\nncase-master\examples\yolox> python tools/compile.py model/yolox_nano_224.onnx yolox_nano_224_quant.kmodel --imgs_dir ../20classes_yolo/images/ --legacy --target k210
屏幕打印信息及报错信息如下：
15524
1. Import graph...
1.1 Pre-process...
Traceback (most recent call last):
  File "tools/compile.py", line 103, in <module>
    args.test_size, args.legacy, args.no_preprocess)
  File "tools/compile.py", line 77, in main
    compiler.compile()
RuntimeError: Type must be same:
normalize_out_convert[Convert]->dequantize_input[Dequantize] has type mismatch: [f32]->[u8]

**Comment by rogerkuo1981** [comment]
> 我使用官方的nano模型测试的时候会报错type mismatch: [f32]->[u8]
> 命令行如下：
> PS D:\Python\nncase-master\examples\yolox> python tools/compile.py model/yolox_nano_224.onnx yolox_nano_224_quant.kmodel --imgs_dir ../20classes_yolo/images/ --legacy --target k210
> 屏幕打印信息及报错信息如下：
> 15524
> 
> 1. Import graph...
>    1.1 Pre-process...
>    Traceback (most recent call last):
>    File "tools/compile.py", line 103, in 
>    args.test_size, args.legacy, args.no_preprocess)
>    File "tools/compile.py", line 77, in main
>    compiler.compile()
>    RuntimeError: Type must be same:
>    normalize_out_convert[Convert]->dequantize_input[Dequantize] has type mismatch: [f32]->[u8]

使用最新的binary的时候，会报错Fatal: invalid unordered_map<K, T> key，但是如果不加--output-type uint8的时候，可生成kmodel，不过是是f32的
屏幕打印信息和报错信息如下（binary下载的也是最新版本）：
PS D:\nncase-windows-2019-x86_64\bin> ncc.exe compile yolox_nano_224.onnx yolox_nano_224.kmodel -i onnx -t k210 --output-type uint8 --dataset ./img
nncase Command Line Tools 1.0.0-814fb5b
Copyright 2019-2021 Canaan Inc.
1. Import graph...
1.1 Pre-process...
2. Optimize target independent...
3. Optimize target dependent...
4.1. Add quantize annotation...
4.2. Run calibration...
4.2.1 Collecting ranges...
4.3. Quantize graph...
Fatal: invalid unordered_map<K, T> key

**Comment by zhen8838** [comment]
@rogerkuo1981 你好, 我的脚本在814fb5b这个commit之后修改的,因此你需要用开发中的版本.

**Comment by zhen8838** [comment]
https://user-images.githubusercontent.com/26156999/133051242-1aa498df-8f41-4ec9-aeff-0e48c15a0083.mov

**Comment by rogerkuo1981** [comment]
> @rogerkuo1981 你好, 我的脚本在814fb5b这个commit之后修改的,因此你需要用开发中的版本.

非常感谢！！！我发现这个问题了，因为今天这边网络比较卡，没有及时刷新出您的回复，我就顺手把自己发的那个问题给删除了。
删完了以后刷新才发现您的回复，不好意思不好意思
