### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by rogerkuo1981** [kendryte/nncase#373]
下载windows版之后，解压缩有四个文件夹
bin，include， lib, python，直接运行bin下面的ncc没有反应，是需要怎么配置吗？

**Comment by zhen8838** [comment]
你可以参考在ubuntu下的使用方法,进行对应的windows设置:

1. 解压后添加相应的环境变量
```sh
unzip nncase-ubuntu-18.04-x86_64.zip -d nncase-demo
cd nncase-demo
export PYTHONPATH=`pwd`/python:`pwd`/lib:$PYTHONPATH
export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
```

2. 打开python,测试nncase的接口.
```python
>>> import _nncase
>>> _nncase.__version__
'1.0.0-4a33c55'
```
3. 请参考yolox的python接口[使用方法](https://github.com/kendryte/nncase/tree/master/examples/yolox).
