### ISSUE TITLE
k210 freezes when loading yolox model

### ISSUE THREAD

**Issue by chenhu66** [kendryte/nncase#377]
**Describe the bug**
yolox does not work out on k210. 

**To Reproduce**
yolox k210example in nncase git latest and kendryte-standalone-sdk latest develop head

**Expected behavior**
k210 model loaded successfully and an image with bounding box displayed

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu20.04]
 - nncase version [e.g. v1.0.0.dev24]: latest
- kendryte-standalone-sdk: lastest

**Additional context**
hello_world was fine, kpu_20classes_example was fine, too. But yolox didn't work out. Please support. Thank you!

**Comment by chenhu66** [comment]
and my log from serial port:

![image](https://user-images.githubusercontent.com/26198254/133494635-cd1660f1-49de-411b-88f1-4d6f9266d1cc.png)

**Comment by chenhu66** [comment]
log from k210:

![image](https://user-images.githubusercontent.com/26198254/133494979-18524ffc-f2de-4594-9617-4157a2188a78.png)

**Comment by sunnycase** [comment]
Did you update the k210 runtime?
See also https://github.com/kendryte/kendryte-standalone-sdk/issues/126

**Comment by chenhu66** [comment]
i updated it a while ago. And i guess that it's no more up-to-date. Where can I get the latest k210 runtime?

**Comment by sunnycase** [comment]
You should use the k210 runtime with the same commit id as compiler's.
Alternatively you can use v1.0.0beta2 compiler and k210 runtime.

**Comment by chenhu66** [comment]
v1.0.0beta2 compiler and k210 runtime worked out. Perfect!
Please close the issue. Thank you very much!

**Comment by chenhu66** [comment]
Thank you very much!
