### ISSUE TITLE
不支持SparseToDense算子，关于这个问题会有其他比较好的解决方案吗

### ISSUE THREAD

**Issue by ifve** [kendryte/nncase#38]

**Comment by sunnycase** [comment]
你模型中 SparseToDense 算子的具体使用场景是什么？

**Comment by ifve** [comment]
> 你模型中 SparseToDense 算子的具体使用场景是什么？

由于目前使用的框架为torch，所以想将torch模型转成.kmodel模型。具体操作为利用onnx生成.pb的模型再生成.tflite，最后利用nncase转换成.kmodel的模型。在获取到.tflite格式的模型后利用nncase工具进行转换的过程中就会出现不支持该算子的问题。
torch模型为： MoblieNet V2

**Comment by sunnycase** [comment]
普通的 MoblieNet V2 应该没有用到稀疏，能发一下你的 tflite 吗
