### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#390]
**Describe the bug**
I was trying to do some preprocessing with ncc tool when converting onnx model to kmodel. However, upon adding parameter "--preprocess", the error occurred.

**To Reproduce**
here is my ncc command:
./ncc -v compile -i onnx -t k210 model/model.onnx model/model.kmodel --preprocess

here is a simple test model:
 
[model.zip](https://github.com/kendryte/nncase/files/7301119/model.zip)

**Expected behavior**
![图片](https://user-images.githubusercontent.com/37980541/136350972-5580109d-7608-4831-907a-82440025ca71.png)

**Environment (please complete the following information):**
 - OS: Ubuntu20.04
 - nncase version  v1.0.0-5cfcbd7
 - DL Framework  Pytorch 1.9.0

**Comment by annosoo** [comment]
> 
> 
> @annosoo sorry, can't reproduce this bug. can you provide your images dataset ?

here is a simple calibration dataset:
[images.zip](https://github.com/kendryte/nncase/files/7314899/images.zip)

**Comment by zhen8838** [comment]
@annosoo you need add `--input-range "0 255" --input-type uint8` in command line.

**Comment by annosoo** [comment]
> 
> 
> @annosoo you need add `--input-range "0 255" --input-type uint8` in command line.

thanks for your reply. It works!
