### ISSUE TITLE
AttributeError: '_nncase.CompileOptions' object has no attribute 'image_format'

### ISSUE THREAD

**Issue by rogerkuo1981** [kendryte/nncase#392]
**Describe the bug**
转换kmodel报错
D:\python\nncase-master\examples\yolox>python tools/compile.py .\model\yolov5_nano_500_sim.onnx yolov5_nano_500.kmodel --imgs_dir ../20classes_yolo/images/ --legacy --target k210
7724
Traceback (most recent call last):
  File "tools/compile.py", line 103, in <module>
    args.test_size, args.legacy, args.no_preprocess)
  File "tools/compile.py", line 50, in main
    cpl_opt.image_format = 'RGB'  # RGB mean not swap RB
AttributeError: '_nncase.CompileOptions' object has no attribute 'image_format'

**To Reproduce**
python tools/compile.py .\model\yolov5_nano_500_sim.onnx yolov5_nano_500.kmodel --imgs_dir ../20classes_yolo/images/ --legacy --target k210

**Expected behavior**
转换onnx到kmodel

**Origin model and code**

**Environment (please complete the following information):**
 - OS: [Win10 64]
 - nncase version [nncase-1.0.0.20210928-cp37-cp37m-win_amd64]
 - DL Framework [e.g. yolov5 ]

**Additional context**

**Comment by zhen8838** [comment]
@rogerkuo1981 Hi, Now you can checkout to #394 branch test with new script.
