### ISSUE TITLE
Fatal: Length of memory (162) must match product of dimensions (648).

### ISSUE THREAD

**Issue by DF-LeeX** [kendryte/nncase#4]
Convert TFLite model to K210 model.
Type the command:    ncc -i tflite -o k210model ./detect.tflite ./detect.kmodel
An error:   Fatal: Length of memory (162) must match product of dimensions (648).

**Comment by sunnycase** [comment]
Can you provide the `detect.tflite`?

**Comment by DF-LeeX** [comment]
@sunnycase 这个模型我拿来测试用的，应该是这个模型有问题，
我现在需要一个20classes_yolo.pb的模型
我在kendryte-model-compiler 中发现了20classes_yolo.pb模型，怎么才能转换成.kmodel格式呢？

**Comment by sunnycase** [comment]
`20classes_yolo.pb` uses LeakyRelu which nncase doesn't support yet.

**Comment by sunnycase** [comment]
Leaky relu was implemented in [v0.1.0-rc2](https://github.com/kendryte/nncase/releases/tag/v0.1.0-rc2)
