### ISSUE TITLE
RELU也是不支持吗？

### ISSUE THREAD

**Issue by JustinLJun** [kendryte/nncase#40]
@sunnycase 呼叫作者大大， 现在RELU也是不支持吗？
![P9D)%_O1VR(Q{W9XLY%LQJV](https://user-images.githubusercontent.com/29404823/64080013-a9ece400-cd21-11e9-967a-d908fdeac20e.png)

**Comment by minux** [comment]
试过最新版了吗？

**Comment by zhen8838** [comment]
@JustinLJun 
这个是tflite转换的问题,如果你使用`tensorflow`,可以把`relu6`替换成如下:
```python
tf.keras.layers.ReLU(6)
````
然后再使用`toco`转换后即可通过编译.

**Comment by Narduzzi** [comment]
Is there a workaround for this issue?
I am trying to convert a pretrained .tflite model to kmodel, but this error occurs.
I don't have the training data and therefore cannot retrain the model.

**Comment by sunnycase** [comment]
The newest ci build has support the standalone RELU.
