### ISSUE TITLE
onnx文件转换异常：Floating point exception (core dumped)

### ISSUE THREAD

**Issue by szgaozg** [kendryte/nncase#405]
**Describe the bug**
paddle模型转换过来的onnx文件，使用ncc转换成kmodel时出现异常。异常位置：
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/ncc compile -i onnx -t cpu ../../model.onnx model.kmodel'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007fdd324e862b in nncase::ir::normalize_reshape (in_shape=..., new_shape=...) at /home/gaozg/work/nncase/include/nncase/ir/op_utils.h:152
152             result[*non_det_id] = xt::compute_size(in_shape) / shape_size;

**To Reproduce**
Command line or scripts to reproduce the behavior:

**Expected behavior**
ncc compile -i onnx -t cpu ../../model.onnx model.kmodel

**Origin model and code**
[ssdlite_mobilenet_v3_small]

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu20.04]
 - nncase version [e.g. v1.0.0.dev24]
 - DL Framework [e.g. Paddle2.1]

**Additional context**
异常转换onnx文件
[model.zip](https://github.com/kendryte/nncase/files/7350082/model.zip)

**Comment by szgaozg** [comment]
异常的onnx
[model.zip](https://github.com/kendryte/nncase/files/7345155/model.zip)
文件

**Comment by zhangyang2057** [comment]
The dim value of three input shapes should not be -1

**Comment by zhangyang2057** [comment]
Is there any update?

**Comment by zhangyang2057** [comment]
No reply for a long time. Close it.
