### ISSUE TITLE
wheel file and input shape on 

### ISSUE THREAD

**Issue by natxopedreira** [kendryte/nncase#410]
**Describe the bug**
Trying to use --input-shape "1 1 240 320" in ncc compile cause unrecognized token error

**To Reproduce**
ncc compile model/slim-320.caffemodel model/slim-320.kmodel  -i caffe -t k210 --input-prototxt model/slim-320.prototxt --input-shape "1 1 240 320"

**Expected behavior**
to be able to chang the input shape

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.

**Environment (please complete the following information):**
 - OS: xubuntu 20
 - nncase version nncase Command Line Tools 1.0.0-9fd39f9

**Additional context**
I also tried to install last version wheel nncase v1.0.0 rc1 but wheel dont work on xubuntu 20 64b python 3.8.10
[https://github.com/kendryte/nncase/releases/download/v1.0.0-rc1/nncase-1.0.0.20210928-cp38-cp38-manylinux_2_24_x86_64.whl](https://github.com/kendryte/nncase/releases/download/v1.0.0-rc1/nncase-1.0.0.20210928-cp38-cp38-manylinux_2_24_x86_64.whl)
`is not supported wheel on this platform`

**Comment by natxopedreira** [comment]
I manged to compile from ncc from source and when trying to compile the model and changing the shape with 
`--input-shape "1 3 240 320"`

I get the same input shape info as without that parameter
```

SUMMARY
INPUTS
0	input	f32[1,3,320,240]
OUTPUTS
0	boxes	f32[1,768000,4]
1	scores	f32[1,768000,2]
```


Also the converted model is the same size as the caffe one?? 1017.3 Kib while the one kmodel in the repo is 300kb

**Comment by curioyang** [comment]
Nncase does not support rotate image , just support resize your image from 320,240 to 240,320.

**Comment by natxopedreira** [comment]
Sorry but i dont understand what is the difference when do the inference of a rotated image to 240x320 and to rescale a image to 240x320

Can you explain please?

Thanks

**Comment by aaltonenzhang** [comment]
Rotate change h to w and change w to h. Resize change h to h', change w to w', it changes the image aspect ratio. Resize is standard preprocess for lots  of models.

**Comment by natxopedreira** [comment]
Maybe im not explaining myself ok.

Im pre processing the image myself i dont expect nncase to rotate the image i sent for inference, i rotate it previously and sent it rotated to inference.

**Comment by aaltonenzhang** [comment]
@natxopedreira  OK, since our framework doesn't really understand the semantic of the input (you can rotate, resize, or do anything to your image by yourself). And when your image is ready, our preprocess will just resize any shape into the model shape. And in my opinion, generally, a AI model is trained based on unrotated images, the original images shape might be 8000*600, or might be 200*5000, but they are all in unrotated direction, and they were resized into model size (i.e 320*240 or maybe 240*320), so I don't think you should rotate a image by yourself, shape is not a problem except that the image is originally not in right direction.

**Comment by natxopedreira** [comment]
In my case i need the camera to be in portrait because i need the biggest fov in vertical. So my images will be in "portrait" so 240x320 but with the faces straight, not rotated

The model is trained on landscape images 320x240

I think i understand what you say but i feed the image of 240x320 with the "faces straight" for inference but the model later will resize those to match first layer of 320x240 as is how it was trained, so the faces that where ok initially now are totally distorted because it changes the input ratio.

Im wrong ?

Thank you!

**Comment by aaltonenzhang** [comment]
@natxopedreira When you enable our preprocess function, the framework will do letterbox and resize, the effective input ratio is still 24:32, and pad value is around, the new shape with pad is (320,240). If you don't use our preprocess, you should check how the model was trained, you should keep your own preprocess as same as what was done in training step.

**Comment by natxopedreira** [comment]
@aaltonenzhang Ok, got it, so i try to compile the model with preprocess flag enabled

`nncase/build/bin/ncc compile  model/caffe/slim-320.caffemodel model/kmodel/slim-320-preprocess.kmodel -i caffe -t k210 --input-prototxt model/caffe/slim-320.prototxt --input-type uint8  --quant-type uint8  --preprocess --input-range "0 255" --input-shape "1 3 240 320"`


Seems sucess
```
nncase Command Line Tools 1.0.0-4a06ff1b
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...

SUMMARY
INPUTS
0	input	f32[1,3,240,320]
OUTPUTS
0	boxes	f32[1,768000,4]
1	scores	f32[1,768000,2]

MEMORY USAGES
.input	 900.00 KB	(921600 B)
.output	  17.58 MB	(18432000 B)
.data	 271.88 MB	(285081600 B)
MODEL	1017.73 KB	(1042152 B)
TOTAL	 291.33 MB	(305477352 B)
```

But i get a black screen so is crashing.... What im doing wrong when converting?

Note that generated model is arround 1Mb and the one in the repo is 300kb
[https://github.com/kendryte/nncase/tree/master/examples/fast_facedetect](https://github.com/kendryte/nncase/tree/master/examples/fast_facedetect)

I downloaded the prototxt file from original repo
[https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/caffe/model/Slim-320/slim-320.prototxt](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/caffe/model/Slim-320/slim-320.prototxt)

Thanks

**Comment by aaltonenzhang** [comment]
@natxopedreira In fact, I'm not experienced having a test on a real board. So what do you mean of "crashing"? Is this just no output or your system is really breakdown? What do you expected? If you want a detection result, you need to run ncc inference after ncc compile at least.

**Comment by natxopedreira** [comment]
@aaltonenzhang I know.

I just compile and run one of this repo examples on a sipeed board, in that one you provide a compiled kmodel that works
[https://github.com/kendryte/nncase/tree/master/examples/fast_facedetect](https://github.com/kendryte/nncase/tree/master/examples/fast_facedetect)

Replacing the model for the one i compiled and i get a black screen that will means code is crashing, if i get no inference i will see the camera image but i get a black screen, sorry i get no crash message because i don't know how to enable a serial output for debug.

But with provided model works with new model black screen.

Provided model weights 300kb compiled model 1mb

**Comment by aaltonenzhang** [comment]
@natxopedreira I've got no idea now since I don't have reproduce environment now. But I think you could use your PC to have a test instead of using DVP first. Maybe you can find something different in inference step. If you could compile ncc in debug mode by yourself, it must be very helpful. Also, the sample in the repo seems to be very old, the size differences might be normal.

**Comment by natxopedreira** [comment]
@aaltonenzhang ok i compiled on debug, compile the model
Copyright 2019-2021 Canaan Inc.
1. Import graph...
1.1 Pre-process...
 |Dequantize:
 |Normalize:
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...

SUMMARY
INPUTS
0	new_input	u8[1,3,240,320]
OUTPUTS
0	boxes	f32[1,768000,4]
1	scores	f32[1,768000,2]

MEMORY USAGES
.input	 225.00 KB	(230400 B)
.output	  17.58 MB	(18432000 B)
.data	 272.75 MB	(286003200 B)
MODEL	1017.83 KB	(1042256 B)
TOTAL	 291.55 MB	(305707856 B)

**Comment by aaltonenzhang** [comment]
@natxopedreira for sdk, you can ask @zhangyang2057. But I think it's probably not the problem. I think if ncc inference is doing well on Linux PC, there might be something wrong on DVP environment.

**Comment by natxopedreira** [comment]
@aaltonenzhang  Ok i reduced the code to only show camera on lcd, remove all inference parts and load the model and it crash, with supplied model in repo i get the camera on lcd as expected and with compiled model i get black so code is crashing when loading the model.

Note im not doing any inference




```

INCBIN(model, "slim-320-preprocess.kmodel");
kpu_model_context_t task;
volatile uint8_t g_ai_done_flag;
volatile uint8_t g_dvp_finish_flag;
volatile uint8_t g_ram_mux;

static image_t display_image;



static int dvp_irq(void *ctx) {
    if (dvp_get_interrupt(DVP_STS_FRAME_FINISH)) {
        dvp_config_interrupt(DVP_CFG_START_INT_ENABLE | DVP_CFG_FINISH_INT_ENABLE, 0);
        dvp_clear_interrupt(DVP_STS_FRAME_FINISH);
        g_dvp_finish_flag= 1;
    } else {
        dvp_start_convert();
        dvp_clear_interrupt(DVP_STS_FRAME_START);
    }
    return 0;
}


static void io_mux_init(void)
{
    /* Init DVP IO map and function settings */
    fpioa_set_function(42, FUNC_CMOS_RST);
    fpioa_set_function(44, FUNC_CMOS_PWDN);
    fpioa_set_function(46, FUNC_CMOS_XCLK);
    fpioa_set_function(43, FUNC_CMOS_VSYNC);
    fpioa_set_function(45, FUNC_CMOS_HREF);
    fpioa_set_function(47, FUNC_CMOS_PCLK);
    fpioa_set_function(41, FUNC_SCCB_SCLK);
    fpioa_set_function(40, FUNC_SCCB_SDA);

    /* Init SPI IO map and function settings */
    fpioa_set_function(38, FUNC_GPIOHS0 + DCX_GPIONUM);
    fpioa_set_function(36, FUNC_SPI0_SS3);
    fpioa_set_function(39, FUNC_SPI0_SCLK);
    fpioa_set_function(37, FUNC_GPIOHS0 + RST_GPIONUM);

    sysctl_set_spi0_dvp_data(1);

}

static void io_set_power(void)
{
    /* Set dvp and spi pin to 1.8V */
    sysctl_set_power_mode(SYSCTL_POWER_BANK6, SYSCTL_POWER_V18);
    sysctl_set_power_mode(SYSCTL_POWER_BANK7, SYSCTL_POWER_V18);
}






int main(void)
{
    /* Set CPU and dvp clk */
    sysctl_pll_set_freq(SYSCTL_PLL0, 800000000UL);
    sysctl_pll_set_freq(SYSCTL_PLL1, 160000000UL);
    sysctl_pll_set_freq(SYSCTL_PLL2, 45158400UL);
    uarths_init();

    io_mux_init();
    io_set_power();
    plic_init();

    /* LCD init */
    printf("LCD init\n");
    lcd_init();
    lcd_set_direction(DIR_YX_LRUD); //DIR_YX_LRDU
    lcd_clear(BLACK);



    /* model load */
    if (kpu_load_kmodel(&task, model_data) != 0)
    {
        printf("\nmodel init error\n");
        while (1);
    }

    /* DVP init */
    printf("DVP init\n");

    dvp_init(8);
    dvp_set_xclk_rate(24000000);
    dvp_enable_burst();
    dvp_set_output_enable(0, 1);
    dvp_set_output_enable(1, 1);
    dvp_set_image_format(DVP_CFG_RGB_FORMAT);

    dvp_set_image_size(320, 240);
    ov2640_init();

    display_image.pixel= 2;
    display_image.width= 320;
    display_image.height= 240;
    image_init(&display_image);

    //dvp_set_ai_addr((uint32_t)kpu_image.addr, (uint32_t)(kpu_image.addr + 320 * 240), (uint32_t)(kpu_image.addr + 320 * 240 * 2));
    dvp_set_display_addr((uint32_t)display_image.addr);
    dvp_config_interrupt(DVP_CFG_START_INT_ENABLE | DVP_CFG_FINISH_INT_ENABLE, 0);
    dvp_disable_auto();

    /* DVP interrupt config */
    printf("DVP interrupt config\n");
    plic_set_priority(IRQN_DVP_INTERRUPT, 1);
    plic_irq_register(IRQN_DVP_INTERRUPT, dvp_irq, NULL);
    plic_irq_enable(IRQN_DVP_INTERRUPT);

    /* enable global interrupt */
    sysctl_enable_irq();



    printf("system start\n");
    
    while (1)
    {

        g_dvp_finish_flag= 0;
        dvp_clear_interrupt(DVP_STS_FRAME_START | DVP_STS_FRAME_FINISH);
        dvp_config_interrupt(DVP_CFG_START_INT_ENABLE | DVP_CFG_FINISH_INT_ENABLE, 1);

        while (g_dvp_finish_flag == 0) {};

        lcd_draw_picture(0, 0, 320, 240, (uint32_t *)display_image.addr);

    }

    return 0;
}
```

**Comment by aaltonenzhang** [comment]
@natxopedreira Sorry I didn't have time to follow this issue for a while. Today I found that you have actually got the key problem before. The reason why you get 1M size kmodel is because you didn't specify the "dataset" argument for calibration, so the framework won't do quantize and a float kmodel is generated. The board is probably not capable to run such kmodel, maybe it's a cpu issue or a ram issue for your crash, which is expected. But for my environment, there is another compile issue later, you can have a try  to specify "dataset " first, if there is something wrong, you can create another issue, that is probably not related the discussion here.

**Comment by natxopedreira** [comment]
ok, i will give that a try
