### ISSUE TITLE
Cannot compile .tflite model (Fatal: Invalid tensor type)

### ISSUE THREAD

**Issue by Myphos** [kendryte/nncase#420]
**Describe the bug**
ncc always aborts with the error message when I try to compile a .tflite model that I exported with [YOLOv5](https://github.com/ultralytics/yolov5). 

> nncase Command Line Tools 1.0.0-fec915fb
Copyright 2019-2021 Canaan Inc.
> 1. Import graph...
Fatal: Invalid tensor type

**To Reproduce**
I did the following:
- Trained a yolov5n network and exported it into the attached .tflite file in  [best-fp16.zip](https://github.com/kendryte/nncase/files/7409110/best-fp16.zip). It's a network with a 1x256x320x3 input tensor and a 1x5040x6 output tensor. 
- Then I tried to compile it with 
`ncc compile ./best-fp16.tflite yolo.kmodel -i tflite -t k210 --input-layout NHWC`
but it fails with the error message above.

I think the model should be convertible but maybe you can help me figure out how to convert it.  

**Origin model and code**
The .tflite file above is a network that's from the YOLOv5 repository that is trained with 

`python3 train.py --data data/GlobalWheat2020.yaml --imgsz 320 --batch-size 1 --epochs 5 --single-cls --workers 8 --weights '' --cfg models/yolov5n.yaml`

and exported to .tflite with 

`python3 export.py --weights runs/train/exp/weights/best.pt --data data/GlobalWheat2020.yaml --imgsz 240 320 --simplify --include tflite --batch-size 1`

**Environment:**
 - OS: Ubuntu 20.04.3 LTS
 - nncase version 1.0.0-fec915fb
 - DL Framework Tensorflow 2.6.0

**Comment by qiujianchen** [comment]
I want to follow your step to train yolov5n.pt on my own datasets.But I can't convert best.pt to tflite. So I want to ask how did you convert? Thank you !

Step:
python train.py --weights yolov5n.pt --cfg models/yolov5n.yaml --data data/mydata.yaml --epochs 5 --batch-size 4 --imgsz 320
python export.py --weights runs/train/exp/weights/best.pt --data data/my_datasets_4.yaml --imgsz 240 320 --simplify --batch-size 1 --include tflite

Error Message :
TensorFlow saved_model: export failure: name 'SPPF' is not defined
TensorFlow Lite: starting export with tensorflow 2.3.0...
TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'

Environment:
pytorch==1.7.0
tensorflow==2.3.0

**Comment by qiujianchen** [comment]
@Myphos 
I want to follow your step to train yolov5n.pt on my own datasets.But I can't convert best.pt to tflite. So I want to ask how did you convert? Thank you !

Step:
python train.py --weights yolov5n.pt --cfg models/yolov5n.yaml --data data/mydata.yaml --epochs 5 --batch-size 4 --imgsz 320
python export.py --weights runs/train/exp/weights/best.pt --data data/my_datasets_4.yaml --imgsz 240 320 --simplify --batch-size 1 --include tflite

Error Message :
TensorFlow saved_model: export failure: name 'SPPF' is not defined
TensorFlow Lite: starting export with tensorflow 2.3.0...
TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'

Environment:
pytorch==1.7.0
tensorflow==2.3.0

**Comment by qiujianchen** [comment]
@Myphos
I want to follow your step to train yolov5n.pt on my own datasets.But I can't convert best.pt to tflite. So I want to ask how did you convert? Thank you !

Step:
python train.py --weights yolov5n.pt --cfg models/yolov5n.yaml --data data/mydata.yaml --epochs 5 --batch-size 4 --imgsz 320
python export.py --weights runs/train/exp/weights/best.pt --data data/my_datasets_4.yaml --imgsz 240 320 --simplify --batch-size 1 --include tflite

Error Message :
TensorFlow saved_model: export failure: name 'SPPF' is not defined
TensorFlow Lite: starting export with tensorflow 2.3.0...
TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'

Environment:
yolov5==v6.0
pytorch==1.7.0
tensorflow==2.3.0

**Comment by qiujianchen** [comment]
@Myphos
I want to follow your step to train yolov5n.pt on my own datasets.But I can't convert best.pt to tflite. So I want to ask how did you convert? Thank you !

Step:
python train.py --weights yolov5n.pt --cfg models/yolov5n.yaml --data data/mydata.yaml --epochs 5 --batch-size 4 --imgsz 320
python export.py --weights runs/train/exp/weights/best.pt --data data/my_data.yaml --imgsz 240 320 --simplify --batch-size 1 --include tflite

Error Message :
TensorFlow saved_model: export failure: name 'SPPF' is not defined
TensorFlow Lite: starting export with tensorflow 2.3.0...
TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'

Environment:
pytorch==1.7.0
tensorflow==2.3.0

**Comment by qiujianchen** [comment]
@Myphos 
Hi, I want to ask you that can you convert best-fp16.tflite to yolo.kmodel successfully?  I follow your step to train yolov5n.pt on my own dataset and convert it to .tflite, but I can't convert it with INT8 quantization. I use best-pt16.tflite to .kmodel, and have the same problem with you. If yes, I want to know how big is your kmodel, and whether it can be deployed to K210?
您好，我想咨询一下您是否已经成功转化了kmodel模型？为了得到轻量化的模型，我按照你的方法在我自己的数据集上训练了yolov5n.pt模型，并且在yolov5项目中转化为tflite，但是我无法量化为int8。然后我将tflite模型转为kmodel，遇到了和您一样的问题，想咨询一下您是否已经解决了？如果是的话，我想咨询一下您最后生成的.kmodel模型有多大，能否成功烧入到K210开发板上并运行？谢谢！
