### ISSUE TITLE
caffe model can't transfer to kmodel

### ISSUE THREAD

**Issue by lishengxie** [kendryte/nncase#423]
**Describe the bug**
I try to transfer my caffe model to kmodel through nncase, but I got a error as follows:
![f19c3d321fb495422e4ee0a74efdd6a](https://user-images.githubusercontent.com/46114762/139581881-672106b5-f1eb-4bca-90e7-9d63c821851e.png)

**To Reproduce**
I use the command as follows:
```./ncc compile model/LSTM.caffemodel model/LSTM.kmodel --input-prototxt model/LSTM.prototxt  -i caffe -t k210 --dataset train --dataset-format raw```

**Origin model and code**
My caffe model have a prototxt as follows:
```
layer {
  name: "clips"
  type: "Input"
  top: "clips"
  input_param {
    shape {
      dim: 50
      dim: 1
    }
  }
}
layer {
  name: "input_1"
  type: "Input"
  top: "input_1"
  input_param {
    shape {
      dim: 50
      dim: 1
      dim: 257
    }
  }
}
layer {
  name: "lstm_1"
  type: "LSTM"
  bottom: "input_1"
  bottom: "clips"
  top: "lstm_1"
  recurrent_param {
    num_output: 200
  }
}
layer {
  name: "lstm_2"
  type: "LSTM"
  bottom: "lstm_1"
  bottom: "clips"
  top: "lstm_2"
  recurrent_param {
    num_output: 200
  }
}
layer {
  name: "time_distributed_1"
  type: "InnerProduct"
  bottom: "lstm_2"
  top: "time_distributed_1"
  inner_product_param {
    num_output: 300
    bias_term: true
  }
}
layer {
  name: "leaky_re_lu_1"
  type: "ReLU"
  bottom: "time_distributed_1"
  top: "leaky_re_lu_1"
}
layer {
  name: "time_distributed_2"
  type: "InnerProduct"
  bottom: "leaky_re_lu_1"
  top: "time_distributed_2"
  inner_product_param {
    num_output: 300
    bias_term: true
  }
}
layer {
  name: "leaky_re_lu_2"
  type: "ReLU"
  bottom: "time_distributed_2"
  top: "leaky_re_lu_2"
}
layer {
  name: "time_distributed_3"
  type: "InnerProduct"
  bottom: "leaky_re_lu_2"
  top: "time_distributed_3"
  inner_product_param {
    num_output: 257
    bias_term: true
  }
}
layer {
  name: "time_distributed_4"
  type: "InnerProduct"
  bottom: "leaky_re_lu_2"
  top: "time_distributed_4"
  inner_product_param {
    num_output: 257
    bias_term: true
  }
}
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - nncase version nncase v1.0.0 beta2
 - DL Framework caffe 1.0.0

**Additional context**
My caffe model is transfered from a keras model which is has the architecture as follows:
![1635681982(1)](https://user-images.githubusercontent.com/46114762/139582324-23a4f9a0-4e75-41af-bbea-a139870e5028.jpg)

**Comment by aaltonenzhang** [comment]
Hi @lishengxie, could you please upload your LSTM.caffemodel? I'll try to reproduce your issue to see what happend.

**Comment by lishengxie** [comment]
https://github.com/lishengxie/nncase_caffe This is my caffe model and keras model, thank you very much!

**Comment by aaltonenzhang** [comment]
@lishengxie Hi, sorry I didn't have time to follow this before. Do you know how to generate or update the ncc executable file? If so, I have some experimental modification on my own forked repo, you can have a try. Here is my modification: https://github.com/aaltonenzhang/nncase/commit/98badf410c9a18c628edfd7b6c156fc96326792a
