### ISSUE TITLE
Fatal: Allocator has ran out of memory

### ISSUE THREAD

**Issue by JimHans** [kendryte/nncase#433]
Hi there, I'm using nncase 1.0.0.20211029 and Python-3.8 on ubuntu 20 (wsl 2.0).
And I struggled to coverte my tflite model (from tensorflow 2.7) to kmodel but failed. 
The error is showed as "Fatal: Allocator has ran out of memory".
Besides, the command typed in is  "./ncc compile ~/model/model.tflite ~/model/1.kmodel -i tflite -t k210 --dataset ~/dataset --preprocess --input-range "0 255" --input-shape "1 3 240 240"

And my model is shown as below:
_________________________________________________________________
 Layer (type)                Output Shape              Param 
=================================================================
 conv2d (Conv2D)             (None, 238, 238, 32)      896

 max_pooling2d (MaxPooling2D  (None, 119, 119, 32)     0
 )

 conv2d_1 (Conv2D)           (None, 117, 117, 64)      18496

 max_pooling2d_1 (MaxPooling  (None, 58, 58, 64)       0
 2D)

 conv2d_2 (Conv2D)           (None, 56, 56, 64)        36928

 flatten (Flatten)           (None, 200704)            0

 dense (Dense)               (None, 8)                 1605640

=================================================================
Total params: 1,661,960
Trainable params: 1,661,960
Non-trainable params: 0
_________________________________________________________________

**Comment by sunnycase** [comment]
Please read FAQ.
