### ISSUE TITLE
最新版的nncase 转换后的模型，测试的时候可以，放到k210后不行

### ISSUE THREAD

**Issue by Nagisakurumi** [kendryte/nncase#434]
我用nncase.Simulator() 测试的时候 需要我自己 resize_padding 才能识别 我C语言中写的 目前不能识别 下面输入kpu_run_model的图片格式 是否需要和nncase.Simulator() 的一样

模型转换的时候我设置了 input_range = [0, 1] swapRB = true mean  还有std 
实际上使用nncase.Simulator() 进行测试的时候 我手动对输入图片进行了 resize_padding 但是不需要归一化和 -mean /std 就可以整正确识别。
但是放到210 后 使用 kpu_run_model 后使用 kpu_get_output 拿到的结果 都是很小的值.和测试的时候并不一致

**Comment by Qinka** [comment]
你最后是如何解决的？？

**Comment by zhen8838** [comment]
他是因为做了手动预处理,但是k210端没有做.  主要就是得保证k210上输入到模型中的数据格式得和simulator相同.
