### ISSUE TITLE
sdk infer error: Invalid argument

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#452]
**Describe the bug**
I was trying to run a quantized model on k210 board, the model which can work well when using ncc to infer. However, when I  use sdk to infer the model with the same input, an error happened. I am not sure whether there is a bug in sdk or I config kpu incorrectly in code., and I have used the lastest ncc and runtime-k210 in master branch, here is the detailed info about error.
```
[02m[..e/ops/kpu_conv2d.cpp:191 (visit)]
[0m[36mlayer.kernel_calc_type_cfg.data.active_addr % 256 == 0[0m = [01mfalse[0m ([32mbool[0m)
error: Invalid argument
```
**To Reproduce**
here is my ncc compile command
`./ncc compile -i onnx -t k210 model.onnx model.kmodel --dataset images --preprocess --input-shape "1 1 28 28" --input-range "0 1" --input-type uint8`

**Expected behavior**
the error should not happen.

**Origin model and code**
here is a simple test onnx cnn model and corresponding bin input
[model.zip](https://github.com/kendryte/nncase/files/7603338/model.zip)
[u8.zip](https://github.com/kendryte/nncase/files/7603339/u8.zip)

here is a simple calibration dataset
[images.zip](https://github.com/kendryte/nncase/files/7603340/images.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu20..04
 - nncase version v1.0.0-00e7944
 - runtime-k210 00e7944

**Comment by sunnycase** [comment]
Did you align your kmodel data array with 256 bytes?

**Comment by annosoo** [comment]
I load kmodel with incbin, the main code is
```
INCBIN(model, "model.kmodel");
kpu_load_kmodel(&task, model_data)
```
just as example, do I need to add something?
In addition, the kmodel can be loaded successfully, but the above error happened when calling kpu_run_kmodel function.

**Comment by annosoo** [comment]
I checked my incbin header file again and found the issue is indeed aroused by the alignment, thanks!
