### ISSUE TITLE
sdk infer result is inconsistent with ncc infer result when using ncc to build single-channel model with mean and std preprocessing

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#455]
**Describe the bug**
I tried to run a single-channel model converted by ncc on k210, the model which is added with mean and std preporcessing when using ncc to compile. Howerver, I got inconsistent result with ncc when using sdk infer, and I  found that the result is right when using three-channel model with mean and std preprocessing.

**To Reproduce**
here is my ncc compile command
`./ncc compile -i onnx -t k210 model.onnx model_uint8.kmodel --dataset images --preprocess --input-shape "1 1 28 28" --input-range "0 1" --input-type uint8 --mean 0.1307 --std 0.3081`

**Expected behavior**
sdk infer result should be consistent with ncc infer

**Origin model and code**
here is my simple single-channel model and u8 bin input
[model.zip](https://github.com/kendryte/nncase/files/7615275/model.zip)
[u8.zip](https://github.com/kendryte/nncase/files/7615276/u8.zip)
here is a simple calibration dataset
[images.zip](https://github.com/kendryte/nncase/files/7615279/images.zip)

**Environment (please complete the following information):**
 - OS:  Ubuntu20.04
 - nncase version v1.0.0-00e7944
 - runtime-k210 00e7944

**Comment by annosoo** [comment]
here is my k210 test code
[issue#455.zip](https://github.com/kendryte/nncase/files/7622634/issue.455.zip)

**Comment by curioyang** [comment]
#514 Support gray image for preprocess.  If you don't want to compile the project, wait for nncase-1.4.0.
You'd better use python to compile kmodel.
Here is the guide.[https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md](url)

You need to use compile config such as :

> ----preprocess option----
preprocess:True
swapRB:False
input_shape:[1, 1, 28, 28]
mean:[0.1307, 0.1307, 0.1307]
std:[0.3081, 0.3081, 0.3081]
input_range:[0, 1]
input_type:uint8
input_layout:NCHW
output_layout:NCHW
letterbox_value:0.0
