### ISSUE TITLE
例子中的yolo.tflite文件是如何训练的

### ISSUE THREAD

**Issue by w910820618** [kendryte/nncase#46]
你好，我想请教你一下yolo.tfilte文件你是怎么训练的？我现在想要训练自己的yolo模型，但是担心训练完的模型，相互转换的时候会出问题。方便的话，你能提供一下代码吗？万分感谢。

**Comment by lijutsang** [comment]
https://www.instructables.com/id/Object-Detection-With-Sipeed-MaiX-BoardsKendryte-K/

**Comment by lijutsang** [comment]
参考：https://www.instructables.com/id/Object-Detection-With-Sipeed-MaiX-BoardsKendryte-K/
