### ISSUE TITLE
tflite to kmodel conversion error

### ISSUE THREAD

**Issue by abhi-84** [kendryte/nncase#469]
Hi all
I have created darknet model weights using yolov4-tiny. Then darknet model is converted to TensorFlow and then to tflite (int8 quantized).
Now when I am converting model to kmodel using "tflite2kmodel.sh" script, it throws an error!

 Fatal: Layer Pad is not supported: Only paddings of [[0,0],[1,1],[1,1],[0,0]] is supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer Pad is not supported: Only paddings of [[0,0],[1,1],[1,1],[0,0]] is supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertPad(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 129
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 99
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)

**get_nncase.sh** -- ncc is latest version!

#!/bin/bash
mkdir -p ncc
mkdir -p workspace
mkdir -p images
mkdir -p log
cd ncc
wget https://github.com/kendryte/nncase/releases/download/v0.1.0-rc5/ncc-linux-x86_64.tar.xz
tar -Jxf ncc-linux-x86_64.tar.xz
rm ncc-linux-x86_64.tar.xz
echo "download nncase ok!"

How to resolve this issue?

**Comment by abhi-84** [comment]
I have also tried with fp16 version of tflite model, still same issue!

**Comment by sunnycase** [comment]
v0.1.0 is deprecated, please use the latest release.

**Comment by abhi-84** [comment]
what should be the instruction with the latest release as it says "ncc-linux-x86_64.tar.xz" is not available?

**Comment by sunnycase** [comment]
Please refer to https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md

**Comment by abhi-84** [comment]
can you please guide me on what steps I need to run in order to get desired files so that I could convert tflite model to kmodel?
I am using Ubuntu 18.04. I am trying docker but that's pretty slow to download.

Shall I try this? 
root@f74598de4a02:/mnt# pip3 install nncase_github/nncase-1.0.0.20211029-cp38-cp38-manylinux_2_24_x86_64.whl

After downloading, do I need to build? Instruction?

Thanks

**Comment by sunnycase** [comment]
You can follow the example https://github.com/kendryte/nncase/tree/master/examples/yolox
While the example uses onnx but tflite is almost the same.

**Comment by abhi-84** [comment]
I have tried to replace onx model with tflite model but it asks for nncase, which I dont have yet. import nncase fails!
Can't install nncase on ubuntu18.04. pip3 command does not work on Ubuntu 18.04. It say "ERROR: nncase-1.0.0.20211029-cp38-cp38-manylinux_2_24_x86_64.whl is not a supported wheel on this platform."

not sure about docker. it breaks the connection and pretty slow download speed!

**Comment by abhi-84** [comment]
I have managed to download docker and when I execute docker, I get root prompt. Now, when I try to run existing yolox sample example,  it throws "No module nncase error!" Why? I can import nncase on python3 interpreter terminal but why compile.py cud not import it and work? Where I am going wrong?

root@b18c05e30ce7:/mnt/nncase/examples/yolox# ls
CMakeLists.txt  Figure_1.png  README.md  cpu  demo.jpg  images  k210  model  tools
root@b18c05e30ce7:/mnt/nncase/examples/yolox# python3 tools/compile.py model/yolox_nano_224.onnx yolox_nano_224_quant.kmodel --imgs_dir ../20classes_yolo/images/ --legacy
Traceback (most recent call last):
  File "tools/compile.py", line 7, in <module>
    import nncase
ModuleNotFoundError: No module named 'nncase'

**Comment by abhi-84** [comment]
After downloading docker image, do I need to build nncase using https://github.com/kendryte/nncase/blob/master/docs/build.md?
I think nncase should be preinstalled in docker. In that case, when I go to yolox example and try to run compile.py file, why it throws "nncase not found"

**Comment by sunnycase** [comment]
> I have tried to replace onx model with tflite model but it asks for nncase, which I dont have yet. import nncase fails! Can't install nncase on ubuntu18.04. pip3 command does not work on Ubuntu 18.04. It say "ERROR: nncase-1.0.0.20211029-cp38-cp38-manylinux_2_24_x86_64.whl is not a supported wheel on this platform."
> 
> not sure about docker. it breaks the connection and pretty slow download speed!

You should upgrade your pip.

**Comment by abhi-84** [comment]
While installing nncase, I am getting following error. I have tried multiple times, reinstalled docker image and nncase directory from local still same issue

Waiting 5 seconds to retry...
WARN: xtensor/0.21.5: requirement nlohmann_json/3.7.3 overridden by your conanfile to nlohmann_json/3.9.1 
WARN: spdlog/1.8.2: requirement fmt/7.1.2 overridden by your conanfile to fmt/7.1.3 
libjpeg/9d: WARN: Package binary is corrupted, removing: 75e99b627c196b65c439728670655ec3c366b334
libjpeg/9d: WARN: Build folder is dirty, removing it: /root/.conan/data/libjpeg/9d/_/_/build/75e99b627c196b65c439728670655ec3c366b334
libjpeg/9d: WARN: Trying to remove corrupted source folder
libjpeg/9d: WARN: This can take a while for big packages
ERROR: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz
ERROR: libjpeg/9d: Error in source() method, line 41
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/mnt/build/CMakeFiles/CMakeOutput.log".

**Comment by sunnycase** [comment]
You don't need to build by yourself. Just upgrade your pip and `pip install nncase-xxx.whl`.

**Comment by abhi-84** [comment]
root@9d321f025ce5:/mnt# /usr/bin/python3 -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 632 kB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@9d321f025ce5:/mnt# pip install nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl
WARNING: Requirement 'nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl' looks like a filename, but the file does not exist
ERROR: nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.

**Comment by abhi-84** [comment]
> You don't need to build by yourself. Just upgrade your pip and `pip install nncase-xxx.whl`.

I am following https://github.com/kendryte/nncase/blob/master/docs/build.md for Docker.

**Comment by abhi-84** [comment]
> While installing nncase, I am getting following error. I have tried multiple times, reinstalled docker image and nncase directory from local still same issue
> 
> Waiting 5 seconds to retry... WARN: xtensor/0.21.5: requirement nlohmann_json/3.7.3 overridden by your conanfile to nlohmann_json/3.9.1 WARN: spdlog/1.8.2: requirement fmt/7.1.2 overridden by your conanfile to fmt/7.1.3 libjpeg/9d: WARN: Package binary is corrupted, removing: 75e99b627c196b65c439728670655ec3c366b334 libjpeg/9d: WARN: Build folder is dirty, removing it: /root/.conan/data/libjpeg/9d/_/_/build/75e99b627c196b65c439728670655ec3c366b334 libjpeg/9d: WARN: Trying to remove corrupted source folder libjpeg/9d: WARN: This can take a while for big packages ERROR: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz ERROR: libjpeg/9d: Error in source() method, line 41 tools.get(**self.conan_data["sources"][self.version]) ConanException: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz CMake Error at cmake/conan.cmake:522 (message): Conan install failed='1' Call Stack (most recent call first): cmake/conan.cmake:759 (old_conan_cmake_install) CMakeLists.txt:60 (conan_cmake_run)
> 
> -- Configuring incomplete, errors occurred! See also "/mnt/build/CMakeFiles/CMakeOutput.log".

pip install conan cmake solved this problem and now, build successful!

**Comment by sunnycase** [comment]
> root@9d321f025ce5:/mnt# /usr/bin/python3 -m pip install --upgrade pip Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (21.2.4) Collecting pip Downloading pip-21.3.1-py3-none-any.whl (1.7 MB) |████████████████████████████████| 1.7 MB 632 kB/s Installing collected packages: pip Attempting uninstall: pip Found existing installation: pip 21.2.4 Uninstalling pip-21.2.4: Successfully uninstalled pip-21.2.4 Successfully installed pip-21.3.1 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv root@9d321f025ce5:/mnt# pip install nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl WARNING: Requirement 'nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl' looks like a filename, but the file does not exist ERROR: nncase-1.1.0.20211203-cp36-cp36m-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.

You should firstly download the wheel from release page.

**Comment by abhi-84** [comment]
I am able to generate kmodel for onx model but getting segmentation fault with tflite conversion, with both uint8 and fp16

root@300647e50fcc:/mnt/examples/yolox# python3 tools/compile.py model/yolov4-tiny-416-int8.tflite yolov4_tiny.kmodel --legacy
36
1. Import graph...
1.1 Pre-process...
Segmentation fault (core dumped)
root@300647e50fcc:/mnt/examples/yolox# python3 tools/compile.py model/yolov4-tiny-416-int8.tflite yolov4_tiny.kmodel --legacy
40
1. Import graph...
1.1 Pre-process...
Segmentation fault (core dumped)

**Comment by sunnycase** [comment]
Use float32 tflite

**Comment by abhi-84** [comment]
> Use float32 tflite
Same issue!

root@300647e50fcc:/mnt/examples/yolox# python3 tools/compile.py model/yolov4-tiny-416.tflite yolov4_tiny.kmodel --legacy
45
1. Import graph...
1.1 Pre-process...
Segmentation fault (core dumped)

**Comment by sunnycase** [comment]
Please upload your tflite and we'll do futher investigation.

**Comment by abhi-84** [comment]
I suspect image size could be issue. 
I am using yolov4 tiny where the database image size is 416x416 whereas convert.py file would be using 224x224? What do you think?
But I have changed image size in convert.py, still it does not work

**Comment by abhi-84** [comment]
tflite file

**Comment by abhi-84** [comment]
Any update?

**Comment by abhi-84** [comment]
> Please upload your tflite and we'll do futher investigation.

Any update on this investigation?

**Comment by curioyang** [comment]
@abhi-84 Our tflite currently does not support SPLIT, and whether the script you are using is'example/yolox/..', the script is for the onnx framework, we will fix your problem in the near future

**Comment by abhi-84** [comment]
is there any way available to convert tflite model to kmodel otherwise?

**Comment by abhi-84** [comment]
Can you help me to execute this example
https://github.com/kendryte/nncase/tree/master/examples/20classes_yolo 

In this example, how to use this command? Where is compile file?
~/nncase/ncc compile model/20classes_yolo.tflite k210/kpu_20classes_example/yolo.kmodel -i tflite -o kmodel -t k210 --dataset images

**Comment by abhi-84** [comment]
@curioyang Can you please check and comment? Thanks

**Comment by aaltonenzhang** [comment]
@abhi-84 you should specify "--input-layout NHWC" for ncc command for 20_classes_yolo

**Comment by abhi-84** [comment]
> 

I got this error while running my tflite model using 20_classes_yolo example

root@77a79633cbf5:/mnt/examples/20classes_yolo# ncc compile model/yolov4-tiny-224.tflite k210/kpu_20classes_example/yolov4.kmodel -i tflite --input-layout NHWC -t k210 --dataset labelled_images 
nncase Command Line Tools 1.0.0-6b1bee22-dirty
Copyright 2019-2021 Canaan Inc.
1. Import graph...
Fatal: Unsupported tflite opcode: SPLIT

**Comment by abhi-84** [comment]
> @abhi-84 Our tflite currently does not support SPLIT, and whether the script you are using is'example/yolox/..', the script is for the onnx framework, we will fix your problem in the near future

Any timelines?

**Comment by curioyang** [comment]
> > @abhi-84 Our tflite currently does not support SPLIT, and whether the script you are using is'example/yolox/..', the script is for the onnx framework, we will fix your problem in the near future
> 
> Any timelines?

Recommend to use python to call nncase

**Comment by curioyang** [comment]
You can refer to this to compile your model. [https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-float32-model-for-tflite](url)

**Comment by abhi-84** [comment]
> k210/kpu_20classes_example/yolov4.kmodel -i tflite --input-layout NHWC -t k210 --dataset labelled_images

I am still getting same error!

root@aec33618e830:/mnt/examples# python3 yolov4_tflite.py
1. Import graph...
Traceback (most recent call last):
  File "yolov4_tflite.py", line 38, in <module>
    main()
  File "yolov4_tflite.py", line 27, in main
    compiler.import_tflite(model_content, import_options)
RuntimeError: Unsupported tflite opcode: SPLIT

**Comment by curioyang** [comment]
@abhi-84 wait for the PR#491 merge

**Comment by abhi-84** [comment]
Hi @curioyang 

After using docker image, I am building using https://github.com/kendryte/nncase/blob/master/docs/build.md 
Here, I got conam version issue so I uninstalled conam and installed conam again using pip.

Now while building, I am getting following error:

Downloading conan_sources.tgz
libjpeg/9d: Configuring sources in /root/.conan/data/libjpeg/9d/_/_/source
WARN: xtensor/0.21.5: requirement nlohmann_json/3.7.3 overridden by your conanfile to nlohmann_json/3.9.1 
WARN: spdlog/1.8.2: requirement fmt/7.1.2 overridden by your conanfile to fmt/7.1.3 
gsl-lite/0.37.0: WARN: This conanfile has no build step
ERROR: libjpeg/9d: Error in source() method, line 41
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file. 
 Provided signature: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee  
 Computed signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
CMake Error at cmake/conan.cmake:529 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:766 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/mnt/build/CMakeFiles/CMakeOutput.log".

**Comment by abhi-84** [comment]
While building from the source for Ubuntu 18.04, I get the following error:

ERROR: flatbuffers/2.0.0: Cannot load recipe.
Error loading conanfile at '/home/abhishek/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py': Unable to load conanfile in /home/abhishek/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py
  File "/home/abhishek/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py", line 74
    tools.get(**self.conan_data["sources"][self.version],
                                                        ^
SyntaxError: invalid syntax

CMake Error at cmake/conan.cmake:529 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:766 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/abhishek/nncase/build/CMakeFiles/CMakeOutput.log".

**Comment by abhi-84** [comment]
@curioyang can you please check and comment. Thank you

**Comment by abhi-84** [comment]
@sunnycase can you please check on the error and comment.

**Comment by curioyang** [comment]
@abhi-84 I'm sorry to reply you so late. Please wait nncase-1.3. There is not enough capacity to handle this compilation problem now.

**Comment by abhi-84** [comment]
> @abhi-84 I'm sorry to reply you so late. Please wait nncase-1.3. There is not enough capacity to handle this compilation problem now.

Would this issue be resolved in nncase-1.3? When shall I expect that to release? Thanks

**Comment by curioyang** [comment]
> 

Next month.

**Comment by curioyang** [comment]
> > @abhi-84 I'm sorry to reply you so late. Please wait nncase-1.3. There is not enough capacity to handle this compilation problem now.
> 
> Would this issue be resolved in nncase-1.3? When shall I expect that to release? Thanks

Next month.
