### ISSUE TITLE
Fatal: Not supported tflite opcode: LOGISTIC

### ISSUE THREAD

**Issue by hothanh** [kendryte/nncase#47]
Hello guys,
we just try to convert our tflite model and got this error:
Fatal: Not supported tflite opcode: LOGISTIC
In the readme, LOGISTIC is one of the ops supported by the toolkit. I had tried on both pre-release v0.2.0 and release v0.1.5 rc5 but got same error,
Hope to receive feedback from you guys soon,
Thanks in advance

**Comment by sunnycase** [comment]
You can use the newest release https://github.com/kendryte/nncase/releases/tag/v0.2.0-alpha2

**Comment by sunnycase** [comment]
It means the feature map size is to large to run on KPU. The input and output feature maps (8bit) of one convolution layer should fit the limit of 2MB (KPU decicated memory size). You can decrease the spatial size or/and channels count.

**Comment by hothanh** [comment]
Thanks again @sunnycase 
we had tried with older version of ncc (v0.1.0 rc5) and got these two last output lines

**Comment by sunnycase** [comment]
The old ncc has a bug when processing conv2d with stride=2, it fold strided_slice with kpu_conv2d incorrectly which make the output of the conv2d on borders slightly differrent from tensorflow's implementation.
The new ncc has fixed the bug, it add a pad before the conv2d which makes the conv2d requries more KPU memory.

**Comment by hothanh** [comment]
Hello @sunnycase 
We had managed to fix the out of memory issue by reducing the input size from 260x260 to 160x160. the converted kmodel is flashed to flash address 0x300000, but we got this error after trying to call kpu.load(0x300000) method:
v=1263354956, flag=4, arch=0, layer len=1, mem=1926400, out cnt=127
err: we only support V3 now, get V1263354956
[MAIXPY]kpu: kpu_model_get_size  error
Do you have any feedback on this
Thanks

**Comment by sunnycase** [comment]
We only offically support kendryte standalone SDK. Your problem is related to MAIXPY.  You can contact Sipeed for more support.

**Comment by hothanh** [comment]
Hi @sunnycase ,
you are right, this is going far from what the thread meant to be :). I'll come to Sipeed as you suggestion. Thanks again for all your priceless support, It's meant a lot
Cheers!
