### ISSUE TITLE
Can't transfer onnx model to k210 kmodel

### ISSUE THREAD

**Issue by lishengxie** [kendryte/nncase#471]
**Describe the bug**
I get an error when trying to convert onnx model to k210 kmodel
![@J8YVIGB6`EC5T48GP3$G$6](https://user-images.githubusercontent.com/46114762/145517050-95088e8d-0fc4-4b33-b3b8-7e165bdc4a90.png)
I can run the onnx model successfully using **onnxruntime**

**To Reproduce**
I use the transfering code from github repo https://github.com/kendryte/nncase/blob/master/docs/USAGE_ZH.md

**Origin model and code**
![image](https://user-images.githubusercontent.com/46114762/145518364-d91a0532-c10d-4a4c-ad54-e1a835792138.png)
This is my network and model file, Thanks!
https://github.com/lishengxie/nncase_caffe/blob/main/enhance_net.onnx
https://github.com/lishengxie/nncase_caffe/blob/main/enhance_net.pth

**Environment (please complete the following information):**
 - nncase version 1.1.0.20211203
 - Pytorch 1.10.0
 - onnx 1.9.0

**Comment by zhangyang2057** [comment]
Matmul in nncase only supports 2D inputs. 
Could you please change your input shape as 2D to try again?

**Comment by lishengxie** [comment]
However, the input to the LSTM layer need to be 3D shape
I have tried another test network which is as follows:
![image](https://user-images.githubusercontent.com/46114762/145753804-d55a8176-30e6-4c7d-81cf-d66ec7427550.png)
The model for this work is https://github.com/lishengxie/nncase_caffe/blob/main/rnn.onnx
I can transfer this model to k210 kmodel successfully.

**Comment by lishengxie** [comment]
The linear Layer in the second network will be transfered to Gemm in onnx. While in the first network, it will be transfered to Matmul&Add. I don't know where the difference is. Thanks!
