### ISSUE TITLE
Can't gencode summary infos

### ISSUE THREAD

**Issue by IRONICBo** [kendryte/nncase#473]
onnx env
```
onnx                    1.8.1
onnx-simplifier         0.3.2
onnxoptimizer           0.2.3
onnxruntime             1.6.0
```
Try to convert my onnx model, but it can't print any summary message. kmodel can't load to k210 too.
![image](https://user-images.githubusercontent.com/47499836/145577181-dc1b98d2-c9d0-4a31-9b97-0207c7284beb.png)
My model is below
[2021_classifier-opt-shape.onnx.zip](https://github.com/kendryte/nncase/files/7692801/2021_classifier-opt-shape.onnx.zip)
Thanks!

**Comment by curioyang** [comment]
@IRONICBo I cannot reproduce your problem. 
`SUMMARY
INPUTS
0       input.1 f32[1,3,224,224]
OUTPUTS
0       251     f32[1,2]

MEMORY USAGES
.input   588.00 KB      (602112 B)
.output    8.00 B       (8 B)
.data    882.00 KB      (903168 B)
MODEL      1.80 MB      (1885280 B)
TOTAL      3.23 MB      (3390568 B)`
Maybe you should update your nncase version or onnx version.
`onnx                    1.9.0
onnx-simplifier         0.3.6
onnxoptimizer           0.2.6
onnxruntime             1.8.0`

**Comment by curioyang** [comment]
@IRONICBo If it can't solve your problem，please reopen this issue and provide more information.
