### ISSUE TITLE
Output node shape does not honor stride - 'Fatal: Allocator has ran out of memory' 

### ISSUE THREAD

**Issue by tjmc** [kendryte/nncase#48]
Create a graph with input node 256x256x3, an output node 128x128x32, 3x3 kernel, and **stride=2** [Example tflite attached - detect.tflite.zip](https://github.com/kendryte/nncase/files/3790490/detect.tflite.zip)

<img width="433" alt="graph" src="https://user-images.githubusercontent.com/388934/67885202-5f5ecc80-fb04-11e9-8274-7405917d5f4b.png">

nncase fails with `Fatal: Allocator has ran out of memory`

Result: The output node has shape: `m_data = {1, 32, 256, 256}`
Expected: Output node shape: 1x32x128x128

GDB log:
> (gdb) b /home/tj/nncase/src/scheduler/freelist.cpp:69                                                                                                                                                         
> Breakpoint 1 at 0x5555556738ed: file /home/tj/nncase/src/scheduler/freelist.cpp, line 69. 
> (gdb) run compile test/detect.tflite test/out.kmodel -i tflite --dataset test/test_000_0000000.png
> Starting program: /home/tj/nncase/out/bin/ncc compile test/detect.tflite test/out.kmodel -i tflite --dataset test/test_000_0000000.png
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7ffff5714700 (LWP 17532)]
> [New Thread 0x7fffecf13700 (LWP 17533)]
> [New Thread 0x7ffff4f13700 (LWP 17534)]
> [New Thread 0x7fffeffff700 (LWP 17535)]
> [New Thread 0x7fffef7fe700 (LWP 17536)]
> [New Thread 0x7fffeeffd700 (LWP 17537)]
> [New Thread 0x7fffee7fc700 (LWP 17538)]
> 
> Thread 1 "ncc" hit Breakpoint 1, nncase::scheduler::freelist::reserve (this=0x5555562a0090, size=2097152) at /home/tj/nncase/src/scheduler/freelist.cpp:69
> 69                  throw std::runtime_error("Allocator has ran out of memory");
> (gdb) backtrace
> #0  nncase::scheduler::freelist::reserve (this=0x5555562a0090, size=2097152) at /home/tj/nncase/src/scheduler/freelist.cpp:69
> 1  0x0000555555673760 in nncase::scheduler::freelist::allocate (this=0x5555562a0090, size=2097152) at /home/tj/nncase/src/scheduler/freelist.cpp:42
> 2  0x0000555555672973 in nncase::scheduler::memory_allocator::allocate (this=0x5555562a0080, size=2097152) at /home/tj/nncase/src/scheduler/memory_allocator.cpp:68
> 3  0x000055555566af2b in nncase::scheduler::allocation_context::allocate_default (this=0x7fffffffd710, conn=...) at /home/tj/nncase/src/scheduler/scheduler.cpp:50
> 4  0x000055555566b2d6 in nncase::scheduler::<lambda(nncase::ir::node&)>::operator()(nncase::ir::node &) const (__closure=0x7fffffffd600, node=...) at /home/tj/nncase/src/scheduler/scheduler.cpp:82
> 5  0x000055555566bd03 in nncase::ir::relay_ir_visitor<nncase::ir::dfs_ir_visitor, nncase::scheduler::schedule(tcb::span<nncase::ir::output_node*>, nncase::scheduler::allocation_context&, std::vector<nncase::ir::node*>&)::<lambda(nncase::ir::node&)> >::visit(nncase::ir::node &) (this=0x7fffffffd5c0, node=...) at /home/tj/nncase/src/ir/include/ir/visitor.h:67
> 6  0x0000555555d4bf6d in nncase::ir::dfs_ir_visitor::visit_strategry (this=0x7fffffffd5c0, node=...) at /home/tj/nncase/src/ir/visitor.cpp:66
> 7  0x0000555555d4bf2e in nncase::ir::dfs_ir_visitor::visit_strategry (this=0x7fffffffd5c0, node=...) at /home/tj/nncase/src/ir/visitor.cpp:61
> 8  0x0000555555d4bf2e in nncase::ir::dfs_ir_visitor::visit_strategry (this=0x7fffffffd5c0, node=...) at /home/tj/nncase/src/ir/visitor.cpp:61
> 9  0x0000555555d4bf2e in nncase::ir::dfs_ir_visitor::visit_strategry (this=0x7fffffffd5c0, node=...) at /home/tj/nncase/src/ir/visitor.cpp:61
> 10 0x0000555555d4bd37 in nncase::ir::ir_visitor::visit (this=0x7fffffffd5c0, outputs=...) at /home/tj/nncase/src/ir/visitor.cpp:31
> 11 0x000055555566b895 in nncase::scheduler::schedule (outputs=..., context=..., compute_sequence=std::vector of length 1, capacity 1 = {...}) at /home/tj/nncase/src/scheduler/scheduler.cpp:123
> 12 0x00005555555d5905 in (anonymous namespace)::gencode (target=..., graph=..., options=...) at /home/tj/nncase/src/cli/compile.cpp:212
> 13 0x00005555555d7234 in compile (options=...) at /home/tj/nncase/src/cli/compile.cpp:265
> 14 0x00005555555a1222 in main (argc=8, argv=0x7fffffffe408) at /home/tj/nncase/src/cli/cli.cpp:38
> (gdb) f 3
> 3  0x000055555566af2b in nncase::scheduler::allocation_context::allocate_default (this=0x7fffffffd710, conn=...) at /home/tj/nncase/src/scheduler/scheduler.cpp:50
> 50              auto &node = allocator->second->allocate(size);
> (gdb) p conn        
> $1 = (nncase::ir::output_connector &) @0x55555629adc0: {<nncase::ir::base_connector> = {owner_ = @0x55555629ab10, name_ = "output", type_ = nncase::dt_uint8, shape_ = {static alignment = 8,
>       m_allocator = {<__gnu_cxx::new_allocator<unsigned long>> = {<No data fields>}, <No data fields>}, m_begin = 0x55555629ae10, m_end = 0x55555629ae30, m_capacity = 0x55555629ae30, m_data = {1, 32, 256,
>         256}}}, connections_ = std::vector of length 1, capacity 1 = {0x555556299ce0}, memory_type_ = nncase::mem_k210_kpu}
> (gdb) c
> Continuing. 
> Fatal: Allocator has ran out of memory
> [Thread 0x7fffedffb700 (LWP 17596) exited]
> [Thread 0x7fffeffff700 (LWP 17592) exited]
> [Thread 0x7ffff7fd4740 (LWP 17586) exited]
> [Thread 0x7fffee7fc700 (LWP 17595) exited]
> [Thread 0x7fffeeffd700 (LWP 17594) exited]
> [Thread 0x7fffef7fe700 (LWP 17593) exited]
> [Thread 0x7ffff4f13700 (LWP 17591) exited]
> 

Maybe related: https://github.com/kendryte/nncase/issues/47#issuecomment-547018266

**Comment by sunnycase** [comment]
For align with tensorflow' implementaion, ncc has two choices.
1. Add a pad before the conv2d, in that the input shape becomes 1x32x258x256.
2. Do 1x32x256x256 conv2d on KPU and strided_slice with stride=2 on CPU

But KPU has a limitation which the height can't be larger than 256, the 1st choice is'nt available.
The 2nd choice requires more KPU memory might cause KPU OOM.

Suggested solution:
Add a Pad with [[0,0],[1,1],[,1,1],[0,0]] (NHWC) before the conv2d and set the padding of conv2d to 'valid'.

**Comment by tjmc** [comment]
Thanks! Adding a pad and using 'valid' solved the problem.
