### ISSUE TITLE
Cannot install wheel package

### ISSUE THREAD

**Issue by qiujianchen** [kendryte/nncase#481]
I download the nncase-1.1.0.20211203-cp38-cp38-win_amd64.whl from release software page, and install it in my computer through command "pip". However, when I copy the demo code to Pycharm and run it, it failed. So I want to ask how to solve this problem.
"ImportError: DLL load failed while importing _nncase: 找不到指定的模块。"
我下载了wheel包并用pip指令安装，但是安装完以后无法导入，想寻求解决办法。

**Comment by qiujianchen** [comment]
I download the nncase-1.1.0.20211203-cp38-cp38-win_amd64.whl from release software page, and install it in my computer through command "pip". However, when I copy the demo code to Pycharm and run it, it failed. So I want to ask how to solve it.
"ImportError: DLL load failed while importing _nncase: 找不到指定的模块。"
我下载了wheel包并用pip指令安装，但是安装完以后无法导入，想寻求解决办法。

**Comment by sunnycase** [comment]
Please refer to #451

**Comment by qiujianchen** [comment]
thanks a lot
