### ISSUE TITLE
How generate detect.kmodel

### ISSUE THREAD

**Issue by c4esp** [kendryte/nncase#486]
**Describe the bug**
It is not possible to generate the detect.kmodel defined in:
https://github.com/kendryte/kendryte-standalone-demo/blob/develop/face_detect/kfpkg/detect.kmodel

**To Reproduce**
No clue about you generate this kmodel

**Expected behavior**
Some idea how generate this model

**Origin model and code**
https://github.com/kendryte/kendryte-standalone-demo/tree/develop/face_detect

**Environment (please complete the following information):**
Whatever

**Additional context**
Thanks in advance.

**Comment by zhen8838** [comment]
this model is not open source, you can refer the examples/20class_yolo
