### ISSUE TITLE
paddle是否能转换成kmodel

### ISSUE THREAD

**Issue by qiujianchen** [kendryte/nncase#494]
参考PaddlePi文档，我使用paddle框架运行YOLOv3Tiny模型，但是无法完成模型转换，报错：Fatal: Dimensions must be equal.
想询问在现有的所有版本中是否支持将paddle模型转换成kmodel模型？

参考网址：
https://aistudio.baidu.com/aistudio/projectdetail/61305
https://aistudio.baidu.com/aistudio/projectdetail/122277?channelType=0&channel=0

![G39KFI$J 9H$DPUY %1QX D](https://user-images.githubusercontent.com/71818703/147745369-fd6d71e2-cc6a-46cb-9d57-d04d2525503e.png)

**Comment by zhen8838** [comment]
如果使用最新版本ncc,需要先将paddle paddle模型转换为onnx模型,然后再导入. 
如果你使用paddle paddle以前的教程,那么就请使用老版本的paddle paddle与老版本的ncc.

**Comment by qiujianchen** [comment]
好的
我是参考paddlePi上的教程来训练自己的目标检测数据集，训练模型为YOLOv3Tiny。但是我训练并固化后，想要用ncc_0.1.0的版本转换模型，却出现以上错误，想咨询一下有没有解决办法？
错误：Fatal: Dimensions must be equal.
Paddle项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/61305 （PaddlePi文档提到的tiny-yolo模型项目网址，按照cell运行程序，但无法fork）
https://aistudio.baidu.com/aistudio/projectdetail/122277?channelType=0&channel=0（找的类似的项目，可以训练，但是无法转换）

**Comment by zhen8838** [comment]
如果你执行的是`https://aistudio.baidu.com/aistudio/projectdetail/61305`的代码出错,那可能他本来就错了.
我建议你参考yolox example中如何编译onnx模型,把你的YOLOv3Tiny导出为onnx模型再编译.

**Comment by qiujianchen** [comment]
您好，我还想请教一下，官方examples中的20class_yolo是通过什么方式训练得到的模型，能提供模型训练的项目地址或者是项目训练的具体流程吗？

**Comment by zhen8838** [comment]
那个是没有开源的，你可以参考nncase主页上训练yolo的项目。

**Comment by qiujianchen** [comment]
@zhen8838 
由于paddle训练效果不佳，所以放弃了，改用yolox项目来训练模型，并量化为kmodel。其检测效果还行。
所以还想再问一下，如果要将yolox模型部署到K210开发板上，实现像20classes_yolo那样实时读取摄像头进行检测，应该如何部署？example中的yolox项目中，似乎没有看到ov2640等头文件？这是不是意味着yolox训练的模型量化后按照README方法无法完成实时目标检测？

**Comment by zhen8838** [comment]
嗯，yolox的速度比较慢，需要你修改一下模型，他里面有一部分无法完全量化到kpu上，最好就是参考20class yolo的结构去修改模型，后面摄像头推理就把两个例子和起来即可。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: qiujianchen ***@***.***&gt;
发送时间: 2022年1月11日 00:03
收件人: kendryte/nncase ***@***.***&gt;
抄送: 郑启航 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[kendryte/nncase] paddle是否能转换成kmodel (Issue #494)





 
@zhen8838
 由于paddle训练效果不佳，所以放弃了，改用yolox项目来训练模型，并量化为kmodel。其检测效果还行。
 所以还想再问一下，如果要将yolox模型部署到K210开发板上，实现像20classes_yolo那样实时读取摄像头进行检测，应该如何部署？example中的yolox项目中，似乎没有看到ov2640等头文件？这是不是意味着yolox训练的模型量化后按照README方法无法完成实时目标检测？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
