### ISSUE TITLE
Cannot convert tflite to kmodel with 0.2.0 Alpha2.

### ISSUE THREAD

**Issue by tsycnh** [kendryte/nncase#50]
I'm trying to compile a tflite to kmodel with the newest release. 
`./ncc.exe compile ./mnist.tflite ./mnist.kmodel -i tflite -o kmodel`

However got a dataset Error.
`Fatal: Invalid dataset, should contain one file at least`

Here is the tflite file and the origin keras h5 file:

链接: https://pan.baidu.com/s/1Vd0mUqcjTa-1z4PxYEAe9Q 提取码: ihw6

**Comment by sunnycase** [comment]
So it says you don't have a valid dataset.

**Comment by tsycnh** [comment]
I just want to convert the model, why do I need a dataset?

**Comment by sunnycase** [comment]
If you want uint8 inferrence, nncase need a calibration dataset to quantize activations.
If you want float inferrence, you shoud pass `--inference-type float` in the cmdline and you don't need to provide a dataset.

**Comment by tsycnh** [comment]
thanks. the float mode works for me. 
However what kind of the calibration dataset should looks like? Will you add some tutorial about the uint8 mode?

**Comment by sunnycase** [comment]
There is an example https://github.com/kendryte/nncase/tree/master/examples/20classes_yolo/images
The calibration dataset is a subset of your training dataset.
