### ISSUE TITLE
请问是否可以转换不是自己训练的模型

### ISSUE THREAD

**Issue by DeqingSun** [kendryte/nncase#500]
你好，
我最近在尝试把别人训练好的模型放到K210上跑。根据我的理解，nncase需要训练的数据集来做量化，把浮点运算优化成整形运算。但是如果是别人[训练好的模型](https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection_lite.tflite)，那么数据集什么的都是没有的，只有一个tflite文件。请问在这种情况下是否可能转换模型？

谢谢

**Comment by zhen8838** [comment]
量化还是需要数据集的，Google的模型应该也是在一些标准数据集上训练的吧，你可以从一些开源数据集中收集图片来进行量化。

**Comment by sunnycase** [comment]
不一定需要训练的数据集，也可以是部署场景的数据

**Comment by DeqingSun** [comment]
非常感谢。
我在尝试转化的时候遇到了```Fatal: Not supported tflite opcode: DEQUANTIZE``` 错误。但是我用netron打开tflite文件后，里面的运算都是浮点。而常量全部都是DEQUANTIZE输入的。
<img width="336" alt="Screen Shot 2022-01-12 at 1 12 15 AM" src="https://user-images.githubusercontent.com/1385273/149074129-41fbc34b-9fa7-4b32-afc5-4dd090106487.png">
请问这种类型的模型可否在K210上运行，需要做哪些改动？

**Comment by curioyang** [comment]
@DeqingSun Not support quant model. You'd better use float32 model.
