### ISSUE TITLE
Paddle模型准换成ONNX模型后，再进行Kmodel模型准换时报错

### ISSUE THREAD

**Issue by dhbhf** [kendryte/nncase#508]
在1. Import graph...时出现了错误，错误如下：  
  compiler.import_onnx(model_content,import_options)
RuntimeError: Can't pull input data for <Concat_0> : only constant initialization is supported

请问，这错误是什么原因导致的呢？模型输入类型是[1,1,32,32]

**Comment by dhbhf** [comment]
而onnx模型是可以推理成功的，模型类型是MobileV1网络

**Comment by sunnycase** [comment]
用 onnxsim 优化过吗？

**Comment by dhbhf** [comment]
非常感谢，优化过后就可以了
