### ISSUE TITLE
MaixPy support for KModel V5?

### ISSUE THREAD

**Issue by JishinMaster** [kendryte/nncase#512]
Dear all, 
There have not been many updates to MaixPy recently, which is still locked to V4 model.
Since all of the required components are not open source, the community cannot help bring support for V5 to MaixPy.

Is this support planed?
What software stack is recommanded to fully use the K210 chip?

**Comment by sunnycase** [comment]
Hi, the official K210 SDK is https://github.com/kendryte/kendryte-standalone-sdk.
For MaixPy, you should open an issue at https://github.com/sipeed/MaixPy.
