### ISSUE TITLE
libjpeg/9d Conan recipe has 'old' checksum

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#524]
Due to repeated re-packaging of `libjpeg/9d` for an unknown reason, checksums of the released archives keep changing (please, see https://github.com/conan-io/conan-center-index/issues/8921 for details). It basically fails the configuration with something like
```bash
libjpeg/9d: Configuring sources in /mnt/src/packages/kendryte/nncase/build/.conan/data/libjpeg/9d/_/_/source
ERROR: libjpeg/9d: Error in source() method, line 41
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file. 
 Provided signature: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee  
 Computed signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
```

According to the output, Conan grabs the recipe from `sunnycase` repository:
```bash
libjpeg/9d: Not found in local cache, looking in remotes...
libjpeg/9d: Trying with 'sunnycase'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libjpeg/9d: Downloaded recipe revision 0
```

Could you please fix the checksum in the recipe there? I believe, this commit can be just ported: https://github.com/conan-io/conan-center-index/pull/8924.

Thank you!

**Comment by sunnycase** [comment]
Updated.

**Comment by aclex** [comment]
Thank you very much! Now it works fine for me.
