### ISSUE TITLE
TransposeConv Support

### ISSUE THREAD

**Issue by magicsch** [kendryte/nncase#53]
Hi Kendryte Team,
we would like to know if you are planning to support operation "TransposeConv" and if yes, could you tell us when you will release?

Regards

Mesut

**Comment by sunnycase** [comment]
The next release (v0.2.0 alpha3) will include `TransposeConv` and it's quantized version. If things go well, it will before the end of the month.

**Comment by magicsch** [comment]
ok great, thank you for your fast reply and good luck :)

**Comment by sunnycase** [comment]
TransposeConv (float version) is supported in v0.2.0 beta1 release.

**Comment by magicsch** [comment]
great, thank you!
