### ISSUE TITLE
problem with converting tflite audio model to kmodel 

### ISSUE THREAD

**Issue by mhsh68y** [kendryte/nncase#532]
hi guys
can anyone help me to convert tflite audio model to kmodel?

**Comment by curioyang** [comment]
@mhsh68y Upload your model.

**Comment by mhsh68y** [comment]
i uploaded tflite and h5 model and data set to below link:
[https://drive.google.com/file/d/1-44Omge-qkOQNQwYgV_ynaMX-dZra2sV/view?usp=sharing](url)

Please teach me how to convert tflite to kmodel.

**Comment by mhsh68y** [comment]
> 



> @mhsh68y Upload your model.

i uploaded tflite and h5 model and data set to below link:
[https://drive.google.com/file/d/1-44Omge-qkOQNQwYgV_ynaMX-dZra2sV/view?usp=sharing](https://github.com/kendryte/nncase/issues/url)

Please teach me how to convert tflite to kmodel.

**Comment by curioyang** [comment]
@mhsh68y  [https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-float32-model-for-tflite](url)
