### ISSUE TITLE
试了不同版本的nncase，输出为1x1大小的卷积层都是分配在CPU上计算完成，而不是分配到KPU上计算。导致耗时较多。这是一个bug还是为什么呢？

### ISSUE THREAD

**Issue by wei8171023** [kendryte/nncase#533]
试了不同版本的nncase，输出宽和高为1x1大小的卷积层都是分配在CPU上计算完成，而不是分配到KPU上计算。导致耗时比较多！
这是一个编译器的bug还是为什么呢？不知道你们有没有遇到过这种情况呢？
谢谢！

**Comment by sunnycase** [comment]
改成MatMul就可以，feature<4x4的卷积KPU原生不支持，软件也未做优化。

**Comment by wei8171023** [comment]
谢谢！我换成全连接了，nncase会转为pad+kpu conv2d+crop!
