### ISSUE TITLE
Can anyone help me to know how to use nncase for converting a caffe model to .kmodel

### ISSUE THREAD

**Issue by Pacifist-99** [kendryte/nncase#536]
I'm not able to use nncase because I cannot find any instructions

**Comment by zhen8838** [comment]
You can refer to the [documentation](https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-float32-model-for-caffe)

**Comment by Ahamednabeen** [comment]
> You can refer to the [documentation](https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-float32-model-for-caffe)

what am I supposed to do with the 'caffe wheel package' .Am I supposed to install it or does it need to be installed?
Can you please help

**Comment by zhen8838** [comment]
yes, you need install caffe package .


发自我的iPhone

------------------ Original ------------------
From: Ahamednabeen ***@***.***&gt;
Date: 周五,3月 11,2022 18:24
To: kendryte/nncase ***@***.***&gt;
Cc: 郑启航 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [kendryte/nncase] Can anyone help me to know how to use nncase for converting a caffe model to .kmodel (Issue #536)





  
You can refer to the documentation
  
what am I supposed to do with the 'caffe wheel package' .Am I supposed to install it or does it need to be installed?
 Can you please help
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pacifist-99** [comment]
> yes, you need install caffe package . 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Ahamednabeen ***@***.***&gt; Date: 周五,3月 11,2022 18:24 To: kendryte/nncase ***@***.***&gt; Cc: 郑启航 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [kendryte/nncase] Can anyone help me to know how to use nncase for converting a caffe model to .kmodel (Issue #536) You can refer to the documentation what am I supposed to do with the 'caffe wheel package' .Am I supposed to install it or does it need to be installed? Can you please help — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;



> > You can refer to the [documentation](https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-float32-model-for-caffe)
> 
> what am I supposed to do with the 'caffe wheel package' .Am I supposed to install it or does it need to be only pasted inside nncase folder? Can you please help



> yes, you need install caffe package . 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Ahamednabeen ***@***.***&gt; Date: 周五,3月 11,2022 18:24 To: kendryte/nncase ***@***.***&gt; Cc: 郑启航 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [kendryte/nncase] Can anyone help me to know how to use nncase for converting a caffe model to .kmodel (Issue #536) You can refer to the documentation what am I supposed to do with the 'caffe wheel package' .Am I supposed to install it or does it need to be installed? Can you please help — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

![kendrite](https://user-images.githubusercontent.com/82760727/157863541-e43fab41-5a0a-4e79-9bf3-9af82e1b5587.png)
There is two files in the folder . I am not sure how to install caffe wheel package .
Can you please help on this

**Comment by zhen8838** [comment]
`pip install kendryte_caffe`
