### ISSUE TITLE
Is it possible to convert PoseNet TFLite Model to kmodel?

### ISSUE THREAD

**Issue by elloza** [kendryte/nncase#54]
I'm referring to this model or other variants:

[Model employed in Coral Edge](https://github.com/google-coral/project-posenet/blob/master/models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite)

I'm a pretty new user of this platform and I would appreciate so much a little bit of guidance on this :)  How I could check it if this would work?

Maybe using [this](https://github.com/lutzroeder/netron) for checking the operations?

Thank you so much in advance!

**Comment by sunnycase** [comment]
You should use a normal float tflite which is converted from a tf graph def or saved model or keras model. Edge tpu optimized tflite is not supported because it fold all supported ops to a single `edgetpu-custom-op`.
You can use netron to check the model structure.
