### ISSUE TITLE
CMake Error at cmake/conan.cmake:73 while building nncase from source

### ISSUE THREAD

**Issue by Pacifist-99** [kendryte/nncase#540]
**Describe the bug**
When running the command '' cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE'' I'm keep getting the error 
![ncc](https://user-images.githubusercontent.com/82760727/157844452-3a9ed62d-2750-4366-98c8-39a71528b415.png)
 I have tried different versions of cmake and conan but still not able to solve the issue
ERROR MESSAGE:
CMake Error at cmake/conan.cmake:73 (message):
  Please specify in command line CMAKE_BUILD_TYPE
  (-DCMAKE_BUILD_TYPE=Release)
Call Stack (most recent call first):
  cmake/conan.cmake:245 (_conan_detect_build_type)
  cmake/conan.cmake:765 (conan_cmake_settings)
  CMakeLists.txt:60 (conan_cmake_run)

-- Configuring incomplete, errors occurred!
See also "/home/inavan/nncase/build/CMakeFiles/CMakeOutput.log".

**To Reproduce**
Command line or scripts to reproduce the behavior:

 
**Environment
 -  Ubuntu18.04
 - cmake == 3.18
 - conan ==1.42.0

**Comment by sunnycase** [comment]
set $BUILD_TYPE

**Comment by Ahamednabeen** [comment]
![nncase](https://user-images.githubusercontent.com/82760727/157856256-cde0b763-4747-4e7f-a798-9cab079dd335.png)
Got this error after setting Buildtype
Can you please help to solve this issue

**Comment by sunnycase** [comment]
https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter

**Comment by Pacifist-99** [comment]
thanks it worked

**Comment by Pacifist-99** [comment]
> https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter

I have built nncase
but I'm not able to import nncase in python program .
Is there any steps I am missing?

**Comment by Pacifist-99** [comment]
> https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter

BUILD_TYPE=Debug
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
make -j8
cmake --install . --prefix ../install
I have successfully all of the above commands

**Comment by Pacifist-99** [comment]
> https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter

BUILD_TYPE=Debug
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
make -j8
cmake --install . --prefix ../install
I have successfully run all of the above commands

Installed all dependencies and setup environment 
but still not able to import nncase

Can you please help

**Comment by sunnycase** [comment]
Refer to
https://github.com/kendryte/nncase/blob/master/.github/workflows/compiler-test.yml#L58
https://github.com/kendryte/nncase/blob/master/.github/workflows/compiler-test.yml#L99
