### ISSUE TITLE
The LSTM model cannot run correctly in k210 chip

### ISSUE THREAD

**Issue by XS30** [kendryte/nncase#541]
**Describe the bug**
Hi,
My kmodel cannot be used correctly, and I cannot locate the cause of the error.
When I run the (kpu_get_output) function, the returned infer result is shown in the following figure.
我的KMODEL无法正确使用，并且我无法定位错误原因.
当我运行（kpu_get_output）函数时，返回的推理结果如下图所示

(this should be incorrect, but both the run function and the get_output function return code 0 correctly, which means it has run correctly)
(这应该是不正确的，但是run函数与get_output函数都正确返回了0，代表其已正确运行)

In order to solve this problem, I haven't slept for two days, but I still can't find the cause of this error. Please help me. Thank you
为了解决这个问题，我已经两天没有睡觉了，但是我仍然无法找到引起这个错误的原因，希望您能帮助我，谢谢

In the LSTM model, my data shape is [1,1,556]（Test data in Data1.h file）
在LSTM模型中，我的数据shape是[1,1,556]（测试数据在Data1.h）

(see attachment for source file, kmodel, onnx and test data)
(源文件、kmodel、onnx、测试数据见附件)

It should be noted that when I try to use multiple serial port tools, there will be coding errors, so I provide hex code.
需要说明的是：我尝试使用多个串口工具，均会出现编码错误，所以我提供HEX代码。
![image](https://user-images.githubusercontent.com/51533985/158036562-a3df15b1-ef84-4011-8c35-1c5448ea947e.png)

**To Reproduce**
Command line or scripts to reproduce the behavior:

![image](https://user-images.githubusercontent.com/51533985/158036569-3ec6e1a6-c9ff-48b4-aac7-1c8ca2afff4e.png)

“,9y?捼?runtime_function[0;33mW (994916068) SYSCALL: sys_exit called by core 0 with 0x0
[0m”

HEX output
“2C 39 79 3F 92 DA D8 3C 72 75 6E 74 69 6D 65 5F 66 75 6E 63 74 69 6F 6E 01 01 1B 5B 30 3B 33 33 6D 57 20 28 39 39 34 39 31 36 30 36 38 29 20 53 59 53 43 41 4C 4C 3A 20 73 79 73 5F 65 78 69 74 20 63 61 6C 6C 65 64 20 62 79 20 63 6F 72 65 20 30 20 77 69 74 68 20 30 78 30 0D 0A
1B 5B 30 6D 0A ”

When I change the test data from float to double, the output variable outputs as follows
当我将测试数据从float换为double格式，output变量输出如下
"谌!?Ln?runtime_function“
Hex output
"DA C8 21 3F 4C 6E 3F 72 75 6E 74 69 6D 65 5F 66 75 6E 63 74 69 6F 6E "

When all programs are completed, the chip will automatically print the following code
当全部程序运行完成后，芯片会自动打印以下代码
Among them, 994916068 seems to be the clock cycle spent by the program, and 33MW represents power?
其中994916068似乎程序花费的时钟周期，33mW代表功率？
"0;33mW (994916068) SYSCALL: sys_exit called by core 0 with"

**Expected behavior**

Maybe you can help me find the cause of the problem, such as data format, code, etc.Please
也许你能帮我找到问题的原因，比如数据格式、代码等等

If I can solve this problem, I will publish the complete process on CSDN (40W visits) and GitHub to help k210 develop more and more complete materials.
如果我能解决这次的问题，我会将完整的流程发布在CSDN（访问量有40w）与Github，协助K210开发资料越来越完整。

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.
See Annex
[LSTM_file.zip](https://github.com/kendryte/nncase/files/8238660/LSTM_file.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu18.04]
 - nncase version [e.g. v1.0.0.dev24]
 - DL Framework [e.g. TensorFlow 2.5.0]

Window 10
nncase 1.4
Pytorch 1.9
Kendryte-Standalone-SDK 0.5.6
Toolchain-win-i386-8.2.0-20190409

**Additional context**

**Comment by curioyang** [comment]
@XS30 Please upload your full project so that we can verify it

**Comment by NhutTien0905** [comment]
Hi @curioyang, I am also working with LSTM. Can you tell me your model works for what

**Comment by zhen8838** [comment]
@NhutTien0905 The K210 kpu can not accelerate the LSTM. You can only use nncase 1. X to compile an LSTM model running on the K210 CPU.

**Comment by NhutTien0905** [comment]
> @NhutTien0905 The K210 kpu can not accelerate the LSTM. You can only use nncase 1. X to compile an LSTM model running on the K210 CPU.

Thank you so much. Can I ask you a question? Do you know which model can replace LSTM and can run on K210?
