### ISSUE TITLE
Not able to convert caffemodel to kmodel

### ISSUE THREAD

**Issue by Pacifist-99** [kendryte/nncase#543]
**Describe the bug**
After i run the script to convert caffemodel to model ,I am getting the following error
**ERROR**
python convert.py 
1. Import graph...
2. Optimize target independent...
**Segmentation fault (core dumped)**

**Origin model and code**
import nncase
def read_model_file(model_file):
    with open(model_file, 'rb') as f:
        model_content = f.read()
    return model_content

def main():
    target = 'k210'

    # compile_options
    compile_options = nncase.CompileOptions()
    compile_options.target = target
    compile_options.dump_ir = True
    compile_options.dump_asm = True
    compile_options.dump_dir = 'tmp'

    # compiler
    compiler = nncase.Compiler(compile_options)

    # import_options
    import_options = nncase.ImportOptions()

    # import
    caffemodel = read_model_file('gender_net.caffemodel')
    prototxt = read_model_file('gender_deploy.prototxt')
![Screenshot from 2022-03-14 13-50-55](https://user-images.githubusercontent.com/82760727/158132465-1c124b3e-9f3a-4d86-abfe-1fc40431f851.png)

    compiler.import_caffe(caffemodel, prototxt)

    # compile
    compiler.compile()

    # kmodel
    kmodel = compiler.gencode_tobytes()
    with open('test.kmodel', 'wb') as f:
        f.write(kmodel)

if __name__ == '__main__':
    main()

**Environment (please complete the following information):**
 -  Ubuntu18.04
 - nncase                  1.4.0.20220303
 - DL Framework  [TensorFlow 2.5.0]

Can you please help me with this.

**Comment by Pacifist-99** [comment]
I have tried different versions of nncase and I also built nncase in another system .But still getting the same error. Can you please help to solve it?

**Comment by aaltonenzhang** [comment]
@Pacifist-99 I have simply take a look at the caffe model, the reason why you convert fail is because there are a few of Ops we haven't implemented yet now, and this will be added later.

**Comment by sunnycase** [comment]
Please firstly convert to onnx.
