### ISSUE TITLE
Not able to build nncase

### ISSUE THREAD

**Issue by Pacifist-99** [kendryte/nncase#545]
i am getting the following error When running the command '' cmake .. -DCMAKE_BUILD_TYPE=Debug
ERROR: flatbuffers/2.0.0: Cannot load recipe.
Error loading conanfile at '/home/inavan/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py': Unable to load conanfile in /home/inavan/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py
  File "/home/inavan/.conan/data/flatbuffers/2.0.0/_/_/export/conanfile.py", line 74
    tools.get(**self.conan_data["sources"][self.version],
                                                        ^
SyntaxError: invalid syntax

CMake Error at cmake/conan.cmake:529 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:766 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)

-- Configuring incomplete, errors occurred!
See also "/home/inavan/nncase/build/CMakeFiles/CMakeOutput.log".

Platform:
OS :Ubuntu 18.04
cmake == 3.18
conan ==1.42.0

**Comment by zhen8838** [comment]
Maybe conan version too high, my conan version is 1.38.0. Or you can try with [docker image](https://github.com/kendryte/nncase/blob/master/docs/build.md#docker)
