### ISSUE TITLE
Whats the ncc infer commands tell

### ISSUE THREAD

**Issue by yashhema** [kendryte/nncase#55]
Hello,
I converted the tflite model into kmodel. Now I wanted to test , if it works or not . 
I used the ncc.exe infer  mymodel.kmodel myout  --dataset mytestphotos   --input-mean 0 --input-std 1.0

It create a bin file corresponding to each image, what is that bin file telling ? Was the object detected or not ?
Can you please explain
regards

**Comment by sunnycase** [comment]
It's your model's output. For an instance, if your output node is an conv2d, the bin is the output tensor of float32 in NCHW layout.

**Comment by yashhema** [comment]
Hello
From where I can get the NCHW layout, I want to verify the output to know if my model worked or not
________________________________

**Comment by zhen8838** [comment]
bin file is model output array, you can use :
```python
ncc_result=np.fromfile('xxx.bin')
# NOTE ncc_result is NCHW layout array
```
