### ISSUE TITLE
int8 quantization don't reduce the size of the model

### ISSUE THREAD

**Issue by Charlie839242** [kendryte/nncase#553]
**Describe the bug**
I used the following compile options to convert the onnx model to kmodel. However, the size of the two models are the same so I am wondering whether the model is quantized successfully.
```
  compile_options = nncase.CompileOptions()
  compile_options.target = target
  compile_options.quant_type = 'int8'
  compile_options.w_quant_type = 'int8'
  compile_options.input_type = 'int8'
  compile_options.output_type = 'int8'
  compile_options.dump_ir = True
  compile_options.dump_asm = True
  compile_options.dump_dir = 'tmp'
```

**Expected behavior**
I expect the kmodel size to be much smaller.

**Environment (please complete the following information):**
 - OS: Win 10
 - nncase version 1.4.0.2]

**Comment by sunnycase** [comment]
Please upload your origin model.

**Comment by curioyang** [comment]
@Charlie839242 https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-uint8-model-for-tflite You need to set ptq_options

**Comment by curioyang** [comment]
@Charlie839242 If any questions, reopen the issue.
