### ISSUE TITLE
" kpu_image[0].pixel = 1” in yolox example  ,i thinks it;s wrong 

### ISSUE THREAD

**Issue by chunyexixiaoyu** [kendryte/nncase#554]
**Describe the bug**
Memory allocation error ,i thinks "kpu_image[0].pixel = 3",because the  input bin size is not matching the memory
**To Reproduce**
Command line or scripts to reproduce the behavior:
174 line main.c in /home/xiaoyu/code/k210/nncase/examples/yolox/k210/yolox_detect_examplejiu/main.c
**Expected behavior**

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu18.04]
 - nncase version [e.g. v1.0.0.dev24]
 - DL Framework [e.g. TensorFlow 2.5.0]

**Additional context**

**Comment by zhen8838** [comment]
Yes, You are right! I didn't notice the problem here before.
