### ISSUE TITLE
Fatal: Unsupported image channels: 192

### ISSUE THREAD

**Issue by maziyi234** [kendryte/nncase#568]
(tensorflow) F:\code\nncase\examples\20classes_yolo>"F:\code\nncase\examples\20classes_yolo\ncc_win_x86_64\ncc.exe" compile model/yolov3.tflite k210/kpu_20classes_example/yolo.kmodel -i tflite -o kmodel -t k210 --dataset images2
1. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...
Fatal: Unsupported image channels: 192               ] 0% 0s

你好，我在yolov3中tfliite转K210模型得时候，出现了以上问题，我测试例程得时候没问题，但是用自己训练出来的模型，有问题，tflite模型可以测试，另外，我如何将yolov3能加载到MAIX DOCK板卡上呢

**Comment by curioyang** [comment]
输出数据layout错了吧

**Comment by maziyi234** [comment]
> "F:\code\nncase\examples\20classes_yolo\ncc_win_x86_64\ncc.exe" compile model/yolov3.tflite k210/kpu_20classes_example/yolo.kmodel -i tflite -o kmodel -t k210 --dataset images2

这个我应该怎么改呢

**Comment by curioyang** [comment]
> 

用最新的nncase  python的方式吧， ncc很久不更新了

**Comment by curioyang** [comment]
@maziyi234  https://github.com/kendryte/nncase/blob/master/docs/USAGE_EN.md#compile-uint8-model-for-tflite If any questions, reopen the issue.
