### ISSUE TITLE
kmodel doesn't work on Maix BiT or Grove AI HAT

### ISSUE THREAD

**Issue by experimentech** [kendryte/nncase#57]
Any kmodel generated by any version of v0.2 doesn't work.
Using the most recent MicroPython, loading from MicroSD and loading from flash yields the same result.
`
ValueError: [MAIXPY]kpu: load error:2
`

Attempting to use the kpu_20classes_example (kfpkg.kfpkg) results in the following output to UART:

```
flash init
          LCD init
                  system start

                              model init error

```
So the premade image cant be used either.

I have tried various methods of building various models based off examples and tutorials and the result is the same for using micropython. My models are 2MiB or under. I have tried with both the full and minimal micropython releases.

Worth noting is all tutorials I found use the 0.1 syntax. I have also found mention other people having models which don't work unless built with 0.1.

ncc compile finishes building a kmodel without error, and ncc infer happily spits out a directory full of bin files. However the kmodel doesn't seem to work on the actual hardware.

**Comment by sunnycase** [comment]
You should contact Sipeed. We conly officially support kendryte standalone SDK.
AFAIK maixpy currently doesn't support nncase v0.2.0.

**Comment by experimentech** [comment]
Oh! I wasn't aware of this. Thank you for saying it explicitly.
