### ISSUE TITLE
Process finished with exit code -1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by xiaotai99** [kendryte/nncase#570]
在windous下用的是说明里面的“[编译uint8量化tflite模型](https://github.com/kendryte/nncase/blob/master/docs/USAGE_ZH.md#%E7%BC%96%E8%AF%91uint8%E9%87%8F%E5%8C%96tflite%E6%A8%A1%E5%9E%8B)”脚本，target=k510时，出现RuntimeError的错误；改成k210后能够运行脚本，但是出现下面的情况，不能顺利生成kmodel，请问大家该怎么解决呀

1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
4.1. Add quantize annotation...
4.2. Run calibration...
4.2.1. Collecting ranges...

Process finished with exit code -1073740940 (0xC0000374)

版本是nncase-1.5.0.20220331-cp37-cp37m-win_amd64.whl

**Comment by sunnycase** [comment]
请按照issue模板填写信息。
