### ISSUE TITLE
转换一个十分简单的模型，但是在第一步后无任何输出，甚至没有报错信息

### ISSUE THREAD

**Issue by sky-vocality** [kendryte/nncase#589]
因为没有任何报错信息，我根本就无法定位任何错误所在

 - OS: win10
 - nncase version  v0.2.0

以下是我的模型和命令行截图
![B2B`W`6S@FD0Y41GF_S_AIG](https://user-images.githubusercontent.com/51026842/168223618-a3c991d7-d317-467d-b2a4-cb1ab9c6b1cc.jpg)
![00 MHBUF$ZW3N8A5X0M 0S0](https://user-images.githubusercontent.com/51026842/168223772-ca08622f-c252-4525-a103-91046b772ced.jpg)

**Comment by zhen8838** [comment]
用最新的nncase, 调python接口去编译模型. 参考https://github.com/kendryte/nncase/blob/master/docs/USAGE_ZH.md

**Comment by sky-vocality** [comment]
十分感谢，在使用nncase1.6.0的python接口后模型可以正常变换，因为有些工具还是用的较老版本的nncase，需要作者或者用户进行再次升级或更改。issue close.
