### ISSUE TITLE
some drawboxes information error with nncase latest version and kendryte sdk-develop on github

### ISSUE THREAD

**Issue by xautzxc** [kendryte/nncase#59]
[k210-yolo3](https://github.com/zhen8838/K210_Yolo_framework/blob/e5350c0166e1c9d9acb63166c31a17c514b31f04/yolo3_frame_test_public_maixpy/main.c)
[kpu](https://github.com/kendryte/kendryte-standalone-demo/tree/develop/kpu)
I use these two examples to implement people detection based on tiny-yolo3. In the old Kendryte SDK and nncase-0.1.0-rc5, it can run successfully,shown in the figure1, but in the new version, there is some errors in region_layer_run function, and the questions is shown in the figure2.Is there a good suggestion for this situation?
figure1
![figure1](https://user-images.githubusercontent.com/30285313/69898848-6abe4580-1399-11ea-9959-276551516155.jpg)
figure2
![figure2](https://user-images.githubusercontent.com/30285313/69898853-727dea00-1399-11ea-9563-9ed7b9cd68fe.jpg)

**Comment by sunnycase** [comment]
Can you describe more details? What's your code, input, command lines and output step by step.
