### ISSUE TITLE
nncase1.6编译tflite到k510模型，报错RuntimeError: unary_rsqrt not implemented

### ISSUE THREAD

**Issue by wei8171023** [kendryte/nncase#593]
**Describe the bug**
nncase1.6编译k510模型，报错RuntimeError: unary_rsqrt not implemented

**To Reproduce**
无论是编译float32kmodel还是uint8kmodel 都报同样的错误。
但是编译k210的正常无错。

**Origin model and code**
原始tflite模型为[MobileFaceNet.tflite](https://github.com/wei8171023/LightFaceNet/blob/master/output/ckpt_best/mobilefacenet_best_ckpt/MobileFaceNet.tflite)

**Environment (please complete the following information):**
 - OS: Ubuntu20.04]
 - nncase 1.6
 - DL Framework  TensorFlow1.14

使用的编译转化脚本：[tflite2kmodel.py](https://github.com/wei8171023/LightFaceNet/blob/master/output/ckpt_best/mobilefacenet_best_ckpt/tflite2kmodel.py)

请问是我的模型问题还是什么问题呢？谢谢

**Comment by wei8171023** [comment]
请问官方人员能出来解答一下吗？谢谢

**Comment by curioyang** [comment]
@wei8171023 onnx'的import没支持这个op, 这两天会加

**Comment by wei8171023** [comment]
@

> @wei8171023 onnx'的import没支持这个op, 这两天会加

@curioyang 我用的是tflite模型啊？ 什么onnx？

**Comment by curioyang** [comment]
@wei8171023 抱歉，因为其它原因看错了你这个问题， 目前已经修复了，待PR merge你可以试试

**Comment by wei8171023** [comment]
> @wei8171023 抱歉，因为其它原因看错了你这个问题， 目前已经修复了，待PR merge你可以试试

在nncase1.7版本里面修复了吗？

**Comment by curioyang** [comment]
> 在nncase1.7版本里面修复了吗？
没有，下个版本

**Comment by curioyang** [comment]
已经加入新版本中，发布后试试

**Comment by wei8171023** [comment]
> 已经加入新版本中，发布后试试

我用v1.7.1nncase 编译还是报错，和之前报的unary_rsqrt not implemented错误一样，不过出现的时间不一样了！请问这是为什么呢？
1. Import graph...
1.1 Pre-process...
 |Dequantize:
 |Normalize:
2. Optimize target independent...
3. Optimize target dependent...
Traceback (most recent call last):
  File "tflite2kmodel_uint8_k210.py", line 104, in <module>
    main()
  File "tflite2kmodel_uint8_k210.py", line 96, in main
    compiler.compile()
RuntimeError: unary_rsqrt not implemented

**Comment by curioyang** [comment]
> > 已经加入新版本中，发布后试试
> 
> 我用v1.7.1nncase 编译还是报错，和之前报的unary_rsqrt not implemented错误一样，不过出现的时间不一样了！请问这是为什么呢？
> 
> 1. Import graph...
>    1.1 Pre-process...
>    |Dequantize:
>    |Normalize:
> 2. Optimize target independent...
> 3. Optimize target dependent...
>    Traceback (most recent call last):
>    File "tflite2kmodel_uint8_k210.py", line 104, in 
>    main()
>    File "tflite2kmodel_uint8_k210.py", line 96, in main
>    compiler.compile()
>    RuntimeError: unary_rsqrt not implemented

你这个是编510还是210

**Comment by curioyang** [comment]
@wei8171023 我这边能编译啊， 你更新510的版本了么？

**Comment by wei8171023** [comment]
> @wei8171023 我这边能编译啊， 你更新510的版本了么？
什么的版本？nncase现在是1.7.1版本了

**Comment by wei8171023** [comment]
> @wei8171023 我这边能编译啊， 你更新510的版本了么？

你那边的使用nnacse的编译脚本能发一下吗？我看看我这有什么不一样的。谢谢

**Comment by curioyang** [comment]
https://github.com/kendryte/nncase/releases/download/v1.7.1/nncase-k510-v1.7.1.tgz
我用你的脚本试过了 ，能编译出来kmodel的，你安装这个510的whl以后再试试
