### ISSUE TITLE
maxpool没用被KPU加速

### ISSUE THREAD

**Issue by junze6** [kendryte/nncase#595]
我的**onnx**转**kmodel**，使用**netron**打开**ir_target_dep_after_quant**，**maxpool**的代替操作为**ReduceWindow2D**,上采样**F.interpolate**的代替操作为**ResizeImage**.
### 我的nncase版本1.6.0.20220505

**Comment by wei8171023** [comment]
个人看法：你的maxpool是在哪个算子后面的啊？

**Comment by junze6** [comment]
我把最大池化改成卷积了，**k210**模型运行耗费**1s**左右时间，这是什么原因，下面是导出的模型图片
![model](https://user-images.githubusercontent.com/92426895/169280648-7d45d3a7-b0ef-4c4b-951d-f56fd023cc89.png)

**Comment by junze6** [comment]
主干网络用的是**shufflenetv2**,是因为分支太多的原因吗

**Comment by wei8171023** [comment]
> 主干网络用的是**shufflenetv2**,是因为分支太多的原因吗

请问你这个图是从哪里找到啊？

**Comment by junze6** [comment]
**nncase**编译时打开**dump-ir**,产生的文件夹**ir_target_dep_after_quant**里的**main.nnir.pb**用**netron**打开

**Comment by curioyang** [comment]
@junze6 上传一下你的模型

**Comment by junze6** [comment]
模型

[model.zip](https://github.com/kendryte/nncase/files/8735067/model.zip)

**Comment by curioyang** [comment]
@junze6 你是不是用的 op profile功能看的运行时间

**Comment by junze6** [comment]
不是，我是在`k210`运行时打印运行模型的时间
`       uint64_t time_last = sysctl_get_time_us();
        kpu_run_kmodel(&task, kpu_image.addr, DMAC_CHANNEL5, ai_done, NULL);
        while(!g_ai_done_flag) //等待
            ;
        uint64_t time_now = sysctl_get_time_us();
        printf("run time:%lu us\n",time_now-time_last);`

**Comment by curioyang** [comment]
首先很抱歉过了这么久才回复你@junze6。
这个模型时间主要是花在了transpose，如下图这个结构，你可以优化一下
![image](https://user-images.githubusercontent.com/39184746/180177429-da5dfe1a-3123-4dc3-b107-e38187dde654.png)
concat的dim设置为0， 只需要一个bitcast将后两维合起来应该就能满足你这个功能
[A]1，96，7，10  --dim=0-->2[A,B],96,7,10-->bitcast-->2[A,B],96,70
[B]1，96，7，10 /
结合后面gather来用的话， 中间甚至不需要任何bitcast和transpose， concat输出2，96，7，10； gather直接从这里取就好了

**Comment by curioyang** [comment]
如果还有什么问题的话再打开issue.
