### ISSUE TITLE
How to generate kmodel for non image data

### ISSUE THREAD

**Issue by hrshovon** [kendryte/nncase#6]
Hello, I am using nncase to generate k210model from tflite model. But it requires some images to be present in some folder. But My model is not for image data. It will take reading from other sensors and make decision. Model is a fully connected model(no conv layer) with input shape (1,4).
How do I convert it to kmodel?

**Comment by sunnycase** [comment]
Currently nncase only support image datasets. Can you describe your dataset format in detail? Maybe this feature will be available in future releases.

**Comment by hrshovon** [comment]
Thank you for such quick reply.
it is generic numeric data. I was actually trying the iris dataset. which
is 1d. 4 columns per data, all floating point.

Best Regards,
SM Hasanur Rashid

**Comment by sunnycase** [comment]
Currently code in master branch has a new param to accept raw dataset. You can specify `--dataset-format raw` to test it. You can get prebuilt binaries at `https://ci.appveyor.com/project/sunnycase/nncase/build/artifacts`.

**Comment by andriyadi** [comment]
I wonder how to use dataformat-raw. Meaning, how to format data for the dataset. Please advice.

**Comment by andriyadi** [comment]
Anyone?

**Comment by shamanez** [comment]
Same problem, What is the shape of input data placeholder? [Batch_Size, H,W]?

**Comment by sunnycase** [comment]
@hrshovon @andriyadi @shamanez If you don't use quantized kernels, you can ignore the `dataset` option and specifiy `--inference-type float`. See the iris example https://github.com/kendryte/nncase/tree/master/examples/iris.

**Comment by andriyadi** [comment]
@sunnycase big thanks for the example and readme. Will try and report the result.

**Comment by sunnycase** [comment]
If you have any questions, please reopen.
