### ISSUE TITLE
nncase crashes at infer due to division by zero.

### ISSUE THREAD

**Issue by jkbmtx** [kendryte/nncase#60]
Hello,
 
during some experiments with classifying network I stumbled upon an issue where, if provided some pictures as a reference, the quantization process (I think) emits incorrect weights to division layer. It happens, when I provide a blank image, which, I guess results in a very small output of the network (its a single neuron at the end). This probably makes some weight very small, so during quantization it truncates to zero, which is not validated. I did not check exactly in the code, this is just speculation on my behalf.

As a side note, I would suggest adding some description about how the dataset is being used during quantization, as it seems to have a very big effect on end result, thus we should provide proper data for this process.

```
(gdb) r
Starting program: /home/kuba/sw/nncase/out/bin/ncc infer model.kmodel ./output --dataset ./images/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
u one channel 
[New Thread 0x7ffff6a80700 (LWP 26528)]
[New Thread 0x7fffeffff700 (LWP 26529)]
[New Thread 0x7ffff627f700 (LWP 26530)]
[New Thread 0x7ffff5a7e700 (LWP 26531)]
[New Thread 0x7ffff527d700 (LWP 26532)]
[New Thread 0x7ffff4a7c700 (LWP 26533)]
[New Thread 0x7fffef7fe700 (LWP 26534)]
KPUConv2D: 38.582ms
KPUConv2D: 124.915ms
KPUConv2D: 118.973ms
KPUConv2D: 109.989ms
Transpose: 0.647001ms
Dequantize: 0.015553ms
MemoryCopy: 0.026985ms
Quantize: 0.053624ms
QuantizedMatMul: 2.02588ms
QuantizedMatMul: 0.005028ms
Dequantize: 0.002193ms
Unary: 0.002223ms
Unary: 0.013567ms
Quantize: 0.001844ms
QuantizedBinary: 0.002767ms

Thread 1 "ncc" received signal SIGFPE, Arithmetic exception.
0x00005555558a409a in nncase::runtime::neutral::<lambda(auto:21, auto:22)>::operator()<int, int>(int, int) const (__closure=0x7fffffffc9c0, a=0, b=0) at /home/kuba/sw/nncase/src/runtime/neutral/neutral_ops.cpp:116
116	                binary([](auto a, auto b) { return (a + b / 2) / b; });
(gdb) print b
$1 = 0

```

Thank you for any feedback.

**Comment by sunnycase** [comment]
Can you attach your tflite and dataset for debugging?

**Comment by jkbmtx** [comment]
Sure, there you go:
[crash.zip](https://github.com/kendryte/nncase/files/3915542/crash.zip)

**Comment by sunnycase** [comment]
I have compiled the kmodel using your entire image dataset with ncc v0.2.0 beta1 release but did't reproduce your problem.

**Comment by jkbmtx** [comment]
I'm using the latest master, in fact I just pulled some new commits and recompiled the project, and the issue seems to persist for me.

I didnt try the release, I think it couldn't handle some of my layers, maybe it does not contain the bug.

**Comment by sunnycase** [comment]
I have tried the master, and did't reproduce the problem. You don't have to build from source, you can use the prebuilt binaris on the CI.

**Comment by jkbmtx** [comment]
Just to be sure, did you also run the infer on the compiled network? Since this is where the crash occurs.

Good to know that I can get the binaries here, thanks.

**Comment by jkbmtx** [comment]
Sorry, I forgot an important detail, this is how I convert the network:

./ncc_ci compile converted_model.tflite model.kmodel -i tflite -o kmodel -t k210 --dataset images --inference-type uint8 --input-std 0.0039216 --input-mean 0

I think this is why you had different results.

**Comment by sunnycase** [comment]
Why do you use `--input-std 0.0039216` instead of the default value?

**Comment by jkbmtx** [comment]
The network was trained on input in range [0,255], I took this value from [here](https://github.com/kendryte/nncase/blob/master/docs/USAGE.md)

**Comment by sunnycase** [comment]
Your dataset cause the last fc's output varies from like [0, 1e7]. This range is too large for uint8 calculation. You may need to remove some outlier images like black and white...

**Comment by jkbmtx** [comment]
Yup, was thinking it might be the case, but having to adjust some of data point doesnt seem like a proper solution. Is it possible to emit an error/warning when compiler sees a range too big to quantize properly? Also, I think quantization is the most important for conv, since its the only operation that goes to the KPU as far as I know (please, correct me if I am wrong).

The last layers are pretty small, I guess it would make to impact to leave them in float, right? Quantization doesnt seem really necessary there, for just one or couple neurons.

**Comment by sunnycase** [comment]
Sometimes you don't have enough memory to do float fc. So a good solution is reading configuration to let user control what ops need to be quantized. But I don't have much time to write the function currently (pr is wellcome 😊).

**Comment by jkbmtx** [comment]
I will think about it, but I am also time constrained. I suppose no fix/warning is planned at the time?

(By the way, is it likely that in the future Kendryte will release a new chip with more memory/more powerful processing power?)

**Comment by sunnycase** [comment]
1. I think i'm able to add a rule that don't quantize small ops
2. yes

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jkbmtx** [comment]
Cool, thanks.

**Comment by sunnycase** [comment]
You can try this build https://dev.azure.com/sunnycase/nncase/_build/results?buildId=93

**Comment by jkbmtx** [comment]
It seemed to resolve the crashing in this case, thanks, good job.

I do seem to notice another issue there, probably related to figuring out the activation ranges.
It looked like my prediction hit the lower bound of ~0.5, where I would expect ~0.0. 

I checked a simple case, and compared the inference between .tflite and converted kmodel (no quantize). I ran inference with 0-filled array and 255-filled array (the network is trained on such a data). The black image seems consistent for both, but white image has differences - using the original .tflite I found out that the output of the networks behaves as if it was provided an array of [1], not [255]. This seems as if --input-std 0.0039216 would not get into consideration in that case.

Do you think there might an issue there, or am I doing something wrong? If you want to try checking the same, you can use my previous attachments.

**Comment by sunnycase** [comment]
I have tested the float kmodel. The output of the black image is 0.5024328 and the white image is 6.406883e-10. Is that desired?

**Comment by jkbmtx** [comment]
I could reproduce your (valid) result with ncc from master, but not with the build you linked in previous comment. So I guess new master works, and there is an issue on the branch?

Apart from that, I noticed that the result for black image switches from 0.5 to 0.3 when quantized. I know the precision is gonna drop, but I thought I can point it out here just in case.

Thanks for the support.

**Comment by sunnycase** [comment]
This build should be ok https://dev.azure.com/sunnycase/nncase/_build/results?buildId=101
