### ISSUE TITLE
kmodel freezes maixpy

### ISSUE THREAD

**Issue by hrshovon** [kendryte/nncase#636]
I am trying to run a simple 1D model in maixpy. I managed to run the iris model without any issues. But when I am trying to feed my own model, maixpy seems to freeze. 

OS version: Ubuntu 22.04
nncase running in latest docker image
ncc version is 1.0.0-6925ee38

Framework: Tensorflow 2.6.0
The model itself is quite simple, just a 3 layer fully connected network. No convolutions. Input format [1,4], output format [1,2]. Both are float32
Here is what I am doing:
1. Train the model, save it in savedmodel format.
2. Convert it to tflite.
3. Run docker and convert the model using ncc using the following command:
    `ncc compile cartpole_dqn.tflite cartpole_dqn.kmodel -i tflite -t k210 --dataset-format raw --input-type float32`
    Output is 
```
nncase Command Line Tools 1.0.0-6925ee38
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...

SUMMARY
INPUTS
0	serving_default_dense_input:0	f32[1,4]
OUTPUTS
0	StatefulPartitionedCall:0	f32[1,2]

MEMORY USAGES
.input	  16.00 B	(16 B)
.output	   8.00 B	(8 B)
.data	   3.27 KB	(3344 B)
MODEL	   4.53 KB	(4640 B)
TOTAL	   7.82 KB	(8008 B)
```

After that, when I copy the model to SD card and try to load it in maixpy, it freezes.

Am I doing something wrong? I am uploading both my savedmodel format model and tflite model just in case
[Download model from here](https://drive.google.com/file/d/19uxlT5hfSBj5ZBCUXuyVuh4Tc7lEf3u1/view?usp=sharing))

**Comment by sunnycase** [comment]
Maixpy doesn't support nncase 1.x
