### ISSUE TITLE
Error when loading onto Maixpy

### ISSUE THREAD

**Issue by pglen** [kendryte/nncase#64]
The model compiled OK, but when transferring to the MaixPy and attempting to load it, it returns error -3 .. I tried to update the MxPY firmware ... same error .. but now the exception prints garbage where the -3 used to be.

I was able to make the correct kmodel with the older version on NCC, but the older version now complains: Invalid  operation: TensorflowResize

PLS advise

**Comment by sunnycase** [comment]
We only officially support kendryte standalone SDK.
See https://github.com/kendryte/nncase/issues/57#issuecomment-557392592
