### ISSUE TITLE
INCBIN模型时incbin报错，从flash加载时产生coredump

### ISSUE THREAD

**Issue by Gambler9123** [kendryte/nncase#641]
不论运行哪个例子，编译时如果用incbin无法通过编译，如果从flash加载模型，则运行时产生coredump
如图
![N$50E1)JH}PTIF2A XKMD64](https://user-images.githubusercontent.com/58584584/189858112-342b52ba-ae97-469d-88ca-970ed7617fcf.png)
![K(7K9`7D}LPB@CH%D~L18PT](https://user-images.githubusercontent.com/58584584/189858199-5fd71cda-eb30-4764-876d-999c1cb08457.png)

**Comment by curioyang** [comment]
从图一的报错来看用INCBIN的时候是你的kmodel没找到吧，试着放到相同路径下看能否起作用
如果还没法解决的话提供多一点信息，现在的两张图没法找问题

**Comment by Gambler9123** [comment]
是在同一路径下的，可能是用你们的ide的某些特定版本不匹配，我重新配了vscode环境后，使用cmake编译后可通过，换编译环境已解决此问题，谢谢
