### ISSUE TITLE
ncc compile example

### ISSUE THREAD

**Issue by StanislavIr** [kendryte/nncase#644]
**Describe the bug**
Hello. Can't sucсessfully infer kmodel, compiled from example "20classes_yolo.tflite". 

**To Reproduce**
1) Compile .kmodel file from 20classes_yolo.tflite by "./ncc compile -i tflite -t k210 model_tflite/20classes_yolo.tflite model_kmodel/yolo_my.kmodel"
![compile](https://user-images.githubusercontent.com/64311520/190989323-c8b3679a-b7cf-4766-9357-a421f42a2bcd.png)
2) Infer yolo_my.kmodel by "./ncc infer model_kmodel/yolo_my.kmodel result --dataset testset --dataset-format image" 
![infer](https://user-images.githubusercontent.com/64311520/190989720-ac64b3e4-f4e2-4267-b92a-b61d63031ff1.png)
enterring COCO_val2014_000000436511.jpg or dog.bmp (images from nncase/examples/20classes_yolo/images)  returns the same result:
getting Fatal: Unsupported image channels: 1

**Expected behavior**
Successfull infer.

**Origin model and code**
nncase[v1.7.1]/examples/20classes_yolo/model/20classes_yolo.tflite

**Environment (please complete the following information):**
 - OS: Ubuntu20.04
 - nncase version v1.7.1
 - DL Framework -

**Comment by sunnycase** [comment]
Please use the python interface, nncase 1.7 doesn't provide the `ncc` command line tool.
