### ISSUE TITLE
 yolox_nano_224.onnx model predicts incorrectly

### ISSUE THREAD

**Issue by nshorey** [kendryte/nncase#670]
The yolox_nano_224.onnx model present at https://github.com/kendryte/nncase/tree/master/examples/yolox/model
doesn't show correct predictions for an image.

I setup the yolox repo from https://github.com/Megvii-BaseDetection/YOLOX
and ran the yolox_nano_224.onnx model using the onnx_inference.py demo from https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/ONNXRuntime

I used the dog.jpg image from https://github.com/kendryte/nncase/tree/master/examples/yolox/images

The model produces wrong predictions.

Is there a correct copy of the yolox_nano_224.onnx model available? I tried using the latest yolox nano model but its feature maps dont fit in K210 2MB RAM limit.

**Comment by zhen8838** [comment]
maybe the YOLOX code has been updated, you can try with [this branch](https://github.com/zhen8838/YOLOX)

**Comment by nshorey** [comment]
> maybe the YOLOX code has been updated, you can try with [this branch](https://github.com/zhen8838/YOLOX)

Thanks @zhen8838 . The suggested branch works fine and the model predicts correctly.
