### ISSUE TITLE
RuntimeError 没有任何提示

### ISSUE THREAD

**Issue by Nagisakurumi** [kendryte/nncase#671]
BUG : 
Traceback (most recent call last):
  File ".\export.py", line 32, in <module>
    convert.convert()
  File "F:\workspace\python\目标检测\detection\convert_model\convert_base.py", line 112, in convert
    k510model = self.convert_to_k510model(samplify_onnx_model)
  File "F:\workspace\python\目标检测\detection\convert_model\convert_base.py", line 90, in convert_to_k510model
    compiler = nncase.Compiler(compile_options)
RuntimeError

# compile_options
compile_options : (编译参数)
compile_options = nncase.CompileOptions()
compile_options.target = 'k510'
compile_options.input_type = 'float32'  # or 'uint8' 'int8'
compile_options.output_type = 'float32'  # or 'uint8' 'int8'. Only work in PTQ
compile_options.output_range = []  # Only work in PTQ and output type is not "float32"
compile_options.preprocess = True  # if False, the args below will unworked
compile_options.swapRB = True
compile_options.input_shape = self.input_shape  # keep layout same as input layout [1, 3, 320, 320]
compile_options.input_layout = 'NCHW'
compile_options.model_layout = ''  # default is empty. Specific it when tflite model with "NCHW" layout and Onnx(Caffe) model with "NHWC" layout
compile_options.mean = [0, 0, 0]
compile_options.std = [1, 1, 1]
compile_options.input_range = [0, 1]
compile_options.letterbox_value = 0.  # pad what you want
compile_options.dump_ir = True
compile_options.dump_asm = True
compile_options.dump_dir = 'tmp'

compiler = nncase.Compiler(compile_options)

**Comment by sunnycase** [comment]
请按issue模板填写。

**Comment by sunnycase** [comment]
请按issue模板填写。
