### ISSUE TITLE
RuntimeError: unsupported transpose permute

### ISSUE THREAD

**Issue by Nagisakurumi** [kendryte/nncase#672]
**Describe the bug**
转换onnx 模型到kmodel 的时候 在 compiler.compile()的时候报错 提示RuntimeError: unsupported transpose permute。

**To Reproduce**
我使用的转换脚本和我使用的onnx的模型 压缩包
[convert_to_kmodel.zip](https://github.com/kendryte/nncase/files/9897481/convert_to_kmodel.zip)
我使用的命令 ：  python convert_to_kmodel.py --onnx simplify.onnx --kmodel wz.kmodel --target k510 --test_size 320 320

**Expected behavior**
我希望能正常转换onnx模型到kmodel 并且得知这个为什么会出现这个问题，我看官方是支持的这个transpose 操作并且群里说过permute也是支持的，并且yolo的demo中也是运行出现这个同样的错误。

**Origin model and code**
模型和代码都在上述的压缩包中

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu20.04]
 - nncase version [e.g. v1.8.0]
 - DL Framework [e.g. torch v1.12.0]

**Comment by curioyang** [comment]
onnx的模型需要先进行simplify，修改后的脚本
[new_convert_to_kmodel.zip](https://github.com/kendryte/nncase/files/10055175/new_convert_to_kmodel.zip)
同时需要在新版本上才可以正确infer，应该是这个月底的版本（由于目前大环境的影响，可能下月初）

**Comment by Nagisakurumi** [comment]
所以这个修改侯的脚本 需要等新的版本1.0.9发出来之后才能用是吗

**Comment by curioyang** [comment]
是的

**Comment by Nagisakurumi** [comment]
好的
