### ISSUE TITLE
运行自己声音检测的kmodel模型时没有反应，报错

### ISSUE THREAD

**Issue by Gambler9123** [kendryte/nncase#673]
Describe the bug
用c语言运行模型时报错
报错信息如下
terminate called without an active exception
SYSCALL: sys_exit called by core 0 with 0x1

To Reproduce
用于跑声音异常检测的kmodel，在加载过程没有报错,运行过程没有反应

Expected behavior
没有预期输出结果值

**Origin model and code**
model_ToyCar.kmodel

Environment (please complete the following information):
 - OS: k210
 - nncase version v1.7.0
 - DL Framework [TensorFlow 2.6.0]

Additional context
![image](https://user-images.githubusercontent.com/58584584/199143056-b7e50a2b-64c5-4098-a5ad-dd83baad8b75.png)

**Comment by Gambler9123** [comment]
[](url)源码如下，使用sdk，nncase v1编译
[abnormal_sound_detect.zip](https://github.com/kendryte/nncase/files/9908549/abnormal_sound_detect.zip)

**Comment by sunnycase** [comment]
都没有运行到 start run model

**Comment by Gambler9123** [comment]
> 都没有运行到 start run model

已运行，是打印被优化了，无法显示出来。
注释gsl-lite头文件中的fail_fast_terminate函数中的std::terminate的即可正常运行
问题已通过绕过解决，但具体问题和原因未定位到，还请有时间复现，查一下，谢谢

**Comment by curioyang** [comment]
@Nagisakurumi Please upload the ONNX source model!

**Comment by curioyang** [comment]
If you need more help, upload the onnx model and reopen this issue.
