### ISSUE TITLE
can not build nncase

### ISSUE THREAD

**Issue by Ghost169204271** [kendryte/nncase#676]
**Describe the bug**
I can not build nncase from source on my win11, 
nncase version 1.8.0
conan version 1.53.0
cmake 3.24.2
**To Reproduce**
![error](https://user-images.githubusercontent.com/93061659/199712766-d9515534-2b77-45ca-a8f4-eeb33d9494cf.jpg)
[CMakeError.log](https://github.com/kendryte/nncase/files/9928009/CMakeError.log)
[CMakeOutput.log](https://github.com/kendryte/nncase/files/9928010/CMakeOutput.log)

**Comment by cscribano** [comment]
Same problem here!

```
ERROR: flatbuffers/2.0.0: option 'options_from_context' doesn't exist
Possible options are ['shared', 'fPIC', 'header_only']
CMake Error at cmake/conan.cmake:529 (message):
  Conan install failed='1'
```

cmake 3.18.6
gcc 10.0
conan 1.52.0

**Comment by sunnycase** [comment]
Pull the latest master.
