### ISSUE TITLE
Allways SYSCALL : Out of memory!

### ISSUE THREAD

**Issue by Nagisakurumi** [kendryte/nncase#688]
**Describe the bug**
我用nncase1.8.x 生成kmodel模型 total : 3.15MB，然后使用从flash读取的方式读取模型读取模型会直接提示这个错误。
我用nncase1.7.x 生成kmodel模型 total : 3.15MB，然后使用从flash读取的方式读取模型读取模型不会提示这个错误，但是运行一轮识别之后就还是会出现这个错误，我尝试去除我的后期处理代码，依旧报这个错误，我尝试去除kpu_get_output 这个函数的调用，结果不会出现溢出的错误，kpu_run_kmodel这个函数一直都是调用的。。（ps : 我的模型的input_shape : [1, 3, 320, 240], out_shape : [4800, 6]）

**To Reproduce**
[detection.zip](https://github.com/kendryte/nncase/files/9976897/detection.zip)
这个是我的代码和 kmodel ，kmodel 在src/detection/build 中

**Expected behavior**
我想知道问题在哪里，为和会这样，怎么做可以不溢出，是不是输出shape 太大导致的

**Origin model and code**
上面

**Environment (please complete the following information):**
 - OS: win11
 - nncase version v1.7.x and v1.8.x
 - DL Framework torch
 - device : k210

**Comment by curioyang** [comment]
@Nagisakurumi Please upload the ONNX source model!

**Comment by curioyang** [comment]
If you need more help, upload the onnx model and reopen this issue.
