### ISSUE TITLE
 failed: TrainFailReason.ERROR_INTERNAL, convert kmodel fail: output:

### ISSUE THREAD

**Issue by haoshuiwuxiang** [kendryte/nncase#689]
转换模型报错：
2022-11-09 08:55:59,493 - [ERROR]:  convert to kmodel fail
2022-11-09 08:55:59,493 - [ERROR]:  failed: TrainFailReason.ERROR_INTERNAL, convert kmodel fail: output:
b''
error:
b"FailFast:\nCouldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.\n\n   at System.Environment.FailFast(System.String)\n   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()\n   at System.Globalization.GlobalizationMode..cctor()\n   at System.Globalization.CultureData.CreateCultureWithInvariantData()\n   at System.Globalization.CultureData.get_Invariant()\n   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)\n   at System.Globalization.CultureInfo..ctor(System.String, Boolean)\n   at System.Reflection.RuntimeAssembly.GetLocale()\n   at System.Reflection.RuntimeAssembly.GetName(Boolean)\n   at System.Reflection.Assembly.GetName()\n   at System.Diagnostics.Tracing.EventPipeController.GetAppName()\n   at System.Diagnostics.Tracing.EventPipeController..ctor()\n   at System.Diagnostics.Tracing.EventPipeController.Initialize()\n   at System.StartupHookProvider.ProcessStartupHooks()\n"

**Comment by sunnycase** [comment]
Please fill the issue template.
