### ISSUE TITLE
convert to kmodel fail

### ISSUE THREAD

**Issue by haoshuiwuxiang** [kendryte/nncase#690]
**Describe the bug**
使用docker进行训练，生成TensorFlow模型正常。但是转换成kmodel时候，报错。具体报错内容：
convert kmodel fail: output:
b''
error:
b"FailFast:\nCouldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.\n\n   at System.Environment.FailFast(System.String)\n   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()\n   at System.Globalization.GlobalizationMode..cctor()\n   at System.Globalization.CultureData.CreateCultureWithInvariantData()\n   at System.Globalization.CultureData.get_Invariant()\n   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)\n   at System.Globalization.CultureInfo..ctor(System.String, Boolean)\n   at System.Reflection.RuntimeAssembly.GetLocale()\n   at System.Reflection.RuntimeAssembly.GetName(Boolean)\n   at System.Reflection.Assembly.GetName()\n   at System.Diagnostics.Tracing.EventPipeController.GetAppName()\n   at System.Diagnostics.Tracing.EventPipeController..ctor()\n   at System.Diagnostics.Tracing.EventPipeController.Initialize()\n   at System.StartupHookProvider.ProcessStartupHooks()\n"

**To Reproduce**
Command line or scripts to reproduce the behavior:

**Expected behavior**

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.

**Environment (please complete the following information):**
 - OS: Ubuntu20.04
 - nncase version v0.1.0-rc5
 - DL Framework docker+tensorflow 2.1.0

**Additional context**

**Comment by sunnycase** [comment]
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

**Comment by haoshuiwuxiang** [comment]
> export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

谢谢，请问这个是什么意思，在哪里添加
