### ISSUE TITLE
kmodel Simulator is different from the original model

### ISSUE THREAD

**Issue by Nagisakurumi** [kendryte/nncase#692]
**Describe the bug**
在原始模型中输出中添加了Sigmoid 但是转换成kmodel 之后用Simulator  进行模拟 但是输出的结果都是大于1的

**To Reproduce**
Command line or scripts to reproduce the behavior:

**Expected behavior**
希望能符合我的原始输出

**Origin model and code**
[k210.zip](https://github.com/kendryte/nncase/files/9989097/k210.zip)

**Environment (please complete the following information):**
 - OS: win11
 - nncase version [1.7.x]
 - DL Framework [torch]

**Comment by curioyang** [comment]
@Nagisakurumi Please upload the ONNX source model!

**Comment by curioyang** [comment]
If you need more help, upload the onnx model and reopen this issue.
