### ISSUE TITLE
RuntimeError: result out of range 

### ISSUE THREAD

**Issue by nshorey** [kendryte/nncase#694]
**Describe the bug**
I get an error "RuntimeError: result out of range" when I try to run 
python tools/simulate.py yolox_nano_224.kmodel ../20classes_yolo/images/dog.bmp
as described in the README.md at nncase/examples/yolox

**To Reproduce**
Cloned nncase main repo
Move to the folder nncase/examples/yolox
Run the following command
python tools/simulate.py k210/yolox_detect_example/yolox_nano_224.kmodel ../20classes_yolo/images/dog.bmp
The command produces the error "RuntimeError: result out of range"

**Expected behavior**
The command should detect the objects in the image as described in README.md

**Environment (please complete the following information):**
-OS Windows 11
-python 3.10.5
-nncase-1.8.0.20220929

![Screenshot 2022-11-12 170526](https://user-images.githubusercontent.com/116991253/201460005-fee6e55d-9040-4ff3-be14-53c40dd95986.jpg)

**Comment by sunnycase** [comment]
Generate kmodel with latest nncase and simulate with the same version.
