### ISSUE TITLE
C:\ncc-win7-x86_64>ncc -i tflite -o k210model --dataset ./dataset tiny2.tflite tiny2.kmodel Fatal: Layer PAD is not supported

### ISSUE THREAD

**Issue by 1330154737** [kendryte/nncase#7]
Hello, I encountered this error when converting tiny yolo v2, can you provide the workspace of tiny yolo v2, thanks

> Hello, I encountered this error when converting tiny yolo v2, can you provide the workspace of tiny yolo v2, thanks

**Comment by sunnycase** [comment]
See readme that `Pad` is not supported yet.
For workspace please raise an issue at https://github.com/kendryte/tensorflow-workspace.
