### ISSUE TITLE
Change model size

### ISSUE THREAD

**Issue by eraser3112** [kendryte/nncase#70]
The created ".kmodel" was tested with M5stickV.
![py](https://user-images.githubusercontent.com/53464329/71656493-c441d780-2d7e-11ea-98b5-fff525b38cea.jpg)
I don't understand "model w=32, h=32".
Did the model conversion fail?
Or can it be changed on maixpy?
The size of the image used for conversion is 224 x 224.
Please tell me.

**Comment by sunnycase** [comment]
For maixpy, you shold contact Sipeed.
For nncase usage, see https://github.com/kendryte/nncase/blob/master/docs/USAGE.md

**Comment by eraser3112** [comment]
Thank you for your reply.
I have confirmed that nncase has nothing to do with this issue.
Close this issue.
