### ISSUE TITLE
tflite movenet model - segmentation fault

### ISSUE THREAD

**Issue by medamarko** [kendryte/nncase#706]
**Describe the bug**
Could not convert movenet model to kmodel in order to testrun on k210

**To Reproduce**
import nncase

def read_model_file(model_file):
    with open(model_file, 'rb') as f:
        model_content = f.read()
    return model_content

def main():
    model='lite-model_movenet_singlepose_lightning_3.tflite'
    target = 'k210'

    # compile_options
    compile_options = nncase.CompileOptions()
    compile_options.target = target
    compile_options.dump_ir = True
    compile_options.dump_asm = True
    compile_options.dump_dir = 'tmp'

    # compiler
    compiler = nncase.Compiler(compile_options)

    # import_options
    import_options = nncase.ImportOptions()

    # import
    model_content = read_model_file(model)
    compiler.import_tflite(model_content, import_options)

    # compile
    compiler.compile()

    # kmodel
    kmodel = compiler.gencode_tobytes()
    with open('test.kmodel', 'wb') as f:
        f.write(kmodel)

if __name__ == '__main__':
    main()

**Origin model and code**
[If applicable, add orgin model and code to help explain your problem.](https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/3)

**Environment (please complete the following information):**
 - docker image

**Additional context**
Log out from python script is:
1. Import graph...
Segmentation fault

Any help is apretiated.

**Comment by curioyang** [comment]
Maybe the model has quantized.  NNCASE cannot support to import a quantized model. You'd better check it.

**Comment by curioyang** [comment]
if any questions, reopen this issue.
