### ISSUE TITLE
改进后的yolox转为kmodel后无法检测模型，decode时候维度不匹配

### ISSUE THREAD

**Issue by maziyi234** [kendryte/nncase#709]
(pytorch) F:\code\nncase\examples\yolox>python tools/simulate.py  "F:\code\nncase\examples\yolox\yolox_nano_224_quant3.kmodel" "F:\code\nncase\examples\yolox\images\dog.jpg"
30464
30464
Save the image F:\code\nncase\examples\yolox\images\dog.jpg as ./dog.bin!
===============
D:\anaconda\envs\pytorch\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 105, in <module>
    main(args.kmodel, args.test_size, args.img_path,
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 83, in main
    outputs = decode(torch.from_numpy(prediction.to_numpy()), test_size)
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 37, in decode
    prediction = decode_outputs2(prediction, prediction.dtype, np.array(test_size), strides)
  File "F:\code\nncase\examples\yolox\tools\decoder.py", line 45, in decode_outputs2
    outputs[..., :2] = (outputs[..., :2] + grids) * strides
RuntimeError: The size of tensor a (28) must match the size of tensor b (294) at non-singleton dimension 2

您好，我在使用官方的yolox版本转为kmodel后，检测图片没问题，在使用budding版本的yolox时候，转为kmodel后，遇到了如下问题，在解码时候维度不匹配，这个问题有解决的方法嘛，因为两个yolox版本网络结构差别较大，在做解码图像检测时候有点没有思路，求大佬解答

**Comment by curioyang** [comment]
你改了模型，那后处理部分你同样得改啊，报错的原因应该是grids的尺寸和outputs不一样，改grids的生成

**Comment by curioyang** [comment]
这个不属于kmodel的问题，尽量在交流群里找帮助吧
