### ISSUE TITLE
core dump: illegal instruction

### ISSUE THREAD

**Issue by xautzxc** [kendryte/nncase#72]
Environment:
HDK:kd233
SDK:develop version kendryte sdk
run tiny yolo2 for detection.

The program can be downloaded to the board. After a while, the following error will appear.
`main.c` (main.txt) attachted
[main.txt](https://github.com/kendryte/nncase/files/4030086/main.txt)
[buildLog.txt](https://github.com/kendryte/nncase/files/4030122/buildLog.txt)

[INFO] Rebooting... 
--- forcing DTR inactive
--- forcing RTS inactive
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
flash init
LCD init
DVP init
DVP interrupt config
System start
core dump: illegal instruction
Cause 0x0000000000000002, EPC 0x0000000000000400
reg[00](zero ) = 0x0000000080183d30, reg[01](ra   ) = 0x000000008000b3f4
reg[02](sp   ) = 0x00000000801938f0, reg[03](gp   ) = 0x0000000080185690
reg[04](tp   ) = 0x000000008018bd00, reg[05](t0   ) = 0x000000008021a7cc
reg[06](t1   ) = 0x000000008000b47a, reg[07](t2   ) = 0x0000000000000000
reg[08](s0/fp) = 0x0000000000000000, reg[09](s1   ) = 0x0000000000000000
reg[10](a0   ) = 0x0000000000000000, reg[11](a1   ) = 0x0000000000000000
reg[12](a2   ) = 0x0000000000004000, reg[13](a3   ) = 0xffffffffffff0000
reg[14](a4   ) = 0x0000000050000000, reg[15](a5   ) = 0x0000000000000000
reg[16](a6   ) = 0x0000000000000001, reg[17](a7   ) = 0x0000000000000004
reg[18](s2   ) = 0x0000000000000000, reg[19](s3   ) = 0x0000000000000004
reg[20](s4   ) = 0x0000000000000008, reg[21](s5   ) = 0x0000000000000001
reg[22](s6   ) = 0x0000000000000000, reg[23](s7   ) = 0x0000000080193b88
reg[24](s8   ) = 0x0000000000000003, reg[25](s9   ) = 0x0000000000000008
reg[26](s10  ) = 0x0000000000000000, reg[27](s11  ) = 0x0000000000000000
reg[28](t3   ) = 0x00000000ffffffff, reg[29](t4   ) = 0x0000000000000001
reg[30](t5   ) = 0x0000000000000005, reg[31](t6   ) = 0x00000000801af28c
freg[00](ft0 ) = 0x000000003f800000(), freg[00]() = 0x0000000080026f28()
freg[02](ft2 ) = 0x000000003db8a395(), freg[-1073741824]() = 0x0000000080026f38()
freg[04](ft4 ) = 0x000000003f51af87(), freg[-1073741824]() = 0x0000000080026f48()
freg[06](ft6 ) = 0x0000000000000000(), freg[00]() = 0x0000000080026f58()
freg[08](fs0 ) = 0x0000000049742400(), freg[00]() = 0x0000000080026f80()
freg[10](fa0 ) = 0x00000000410ae6f3(), freg[-1073741824]() = 0x0000000080026fb0()
freg[12](fa2 ) = 0x000000003f800000(), freg[00]() = 0x0000000080026fd8()
freg[14](fa4 ) = 0x0000000000000000(), freg[00]() = 0x0000000080026fe8()
freg[16](fa6 ) = 0x0000000000000000(), freg[00]() = 0x0000000080026ff8()
freg[18](fs2 ) = 0x0000000000000000(), freg[00]() = 0x0000000080027020()
freg[20](fs4 ) = 0x0000000000000000(), freg[00]() = 0x0000000080027030()
freg[22](fs6 ) = 0x0000000000000000(), freg[00]() = 0x0000000080027040()
freg[24](fs8 ) = 0x0000000000000000(), freg[00]() = 0x0000000080027050()
freg[26](fs10) = 0x0000000000000000(), freg[00]() = 0x0000000080027060()
freg[28](ft8 ) = 0x0000000000000000(), freg[00]() = 0x0000000080027088()
freg[30](ft10) = 0x0000000000000000(), freg[00]() = 0x0000000080027098()
W (12580746893) SYSCALL: sys_exit called by core 0 with 0x539

**Comment by sunnycase** [comment]
Can you upload the kmodel?

**Comment by xautzxc** [comment]
[my-kmodel.zip](https://github.com/kendryte/nncase/files/4033443/fruit.kmodel.zip)
kendryte demo:
[demo.zip](https://github.com/kendryte/nncase/files/4033449/demo.zip)


I suspect that the biggest possibility is a hardware board problem. First of all, I did not report this error on the SIPEED board. Secondly, a demo I obtained from kendryte is shown in the attachment,this error  be reported.

**Comment by sunnycase** [comment]
I think so, I can't reproduce the issue.
