### ISSUE TITLE
IndexError: The shape of the mask [25, 28] at index 1 does not match the shape of the indexed tensor [25, 7, 28] at index 1

### ISSUE THREAD

**Issue by maziyi234** [kendryte/nncase#720]
在使用自己得yolox模型进行检测时候 维度匹配问题 通过增加stride维度解决了，但是到后续 又出现了以下问题 ，请问这个问题怎么解决呢 
(pytorch) F:\code\nncase\examples\yolox>python tools/simulate.py  "F:\code\nncase\examples\yolox\yolox_nano_224_quant3.kmodel" "F:\code\nncase\examples\yolox\images\dog.jpg"
23800
23800
Save the image F:\code\nncase\examples\yolox\images\dog.jpg as ./dog.bin!
===============
D:\anaconda\envs\pytorch\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
prediction range : <-731.033935546875, 1253.810546875>
Traceback (most recent call last):
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 119, in <module>
    main(args.kmodel, args.test_size, args.img_path,
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 97, in main
    outputs = decode(prediction0, test_size)
  File "F:\code\nncase\examples\yolox\tools\simulate.py", line 39, in decode
    outputs = postprocess(prediction, num_classes, conf_thre, nms_thre)
  File "F:\code\nncase\examples\yolox\tools\decoder.py", line 366, in postprocess
    detections = detections[conf_mask]
IndexError: The shape of the mask [25, 28] at index 1 does not match the shape of the indexed tensor [25, 7, 28] at index 1

**Comment by zhen8838** [comment]
你好, 可能由于上游的yolox代码有改动,导致例子代码出现问题. 可以参考#670 , 使用特定版本进行训练/推理.

**Comment by curioyang** [comment]
@maziyi234 首先这个7表示的是 [目标座标四个点+是否目标置信度+类别置信度+类别]，你看看你的模型是现在只需要哪个属性，把其他的信息去掉就好了。
