### ISSUE TITLE
Using a quantized model with nncase

### ISSUE THREAD

**Issue by tjmc** [kendryte/nncase#73]
I'd like to use an UINT8 quantized model instead of using nncase's quantizer. Is this possible?

I started making changes to tflite_importer.h [Patch here](https://gist.github.com/tjmc/2dc5e57d503834d3f955f81e48e26dfc). I'm wondering if I'm heading in the right direction or if this isn't going to be possible.

```
~/nncase/out$ ./bin/ncc compile ~/models/train_k210.tflite/detect_uint8.tflite /tmp/out.kmodel -I tflite

1. Import graph...
Fatal: Tensor (FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_bias) Expect FLOAT32 tensor but got INT32

```
[Example tflite graph](https://github.com/kendryte/nncase/files/4037914/detect_uint8.tflite.zip)

**Comment by sunnycase** [comment]
Currently nncase doesn't support import a quantized graph.
Your patch is to restore float tensor from uint8 tensor, it works.
But a 'right' way is importing as a `quantized_conv2d` op, and write a pass to transform a `quantized_conv2d` into `kpu_conv2d`.

**Comment by tjmc** [comment]
Thanks!
