### ISSUE TITLE
KPU debug output

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#77]
@sunnycase 
When I run Yolo model with Kendryte KPU.c compiled in debug mode, I get a list of yolo layers and the time taken for execution of each layer. However when I use the Ultra light fast face detector model provided in this example, this data is not appearing, I am not sure why - can you give me some information. The yolo model is the yolov2face detector model from Sipeed and probably converted using a different version of nncase.

layer 0 [K210Conv]: 0.206000 ms
layer 1 [K210Conv]: 0.039000 ms
layer 2 [K210Conv]: 0.514000 ms
layer 3 [K210Conv]: 0.029000 ms
layer 4 [K210Conv]: 0.680000 ms
layer 5 [K210Conv]: 0.053000 ms
layer 6 [K210Conv]: 1.328000 ms
layer 7 [K210Conv]: 0.020000 ms
layer 8 [K210Conv]: 0.704000 ms
layer 9 [K210Conv]: 0.034000 ms
layer 10 [K210Conv]: 1.385000 ms
layer 11 [K210Conv]: 0.016000 ms
layer 12 [K210Conv]: 0.781000 ms
layer 13 [K210Conv]: 0.025000 ms
layer 14 [K210Conv]: 1.522000 ms
layer 15 [K210Conv]: 0.026000 ms
layer 16 [K210Conv]: 1.521000 ms
layer 17 [K210Conv]: 0.026000 ms
layer 18 [K210Conv]: 1.521000 ms
layer 19 [K210Conv]: 0.026000 ms
layer 20 [K210Conv]: 1.521000 ms
layer 21 [K210Conv]: 0.025000 ms
layer 22 [K210Conv]: 0.326000 ms
layer 23 [Dequantize]: 0.404000 ms
KPU: 12.328000 ms
CPU: 0.404000 ms
Model: 12.732000 ms

**Comment by sunnycase** [comment]
You can change the defination `NNCASE_DEBUG` to `1` to see the log.
https://github.com/kendryte/kendryte-standalone-sdk/blob/develop/lib/nncase/nncase.cpp#L24

**Comment by krishnak** [comment]
@sunnycase  Thank you, I did as per your suggestion, I am getting the debug statement output for the layers when the code executes on K210, however I think there is some threading error in the code execution, you may be able quickly suggest what needs to be done to resolve it.

 The total time by the model is printed correctly, however the individual layer execution time is not getting printed correctly, I have tested it on two separate models. In both of them the total time is different, however one random layer gets assigned the total execution time and all other layers have 0 as the execution time.

See below

However when I run "nncase infer" on the same model on a normal computer each layer outputs its execution time.

```
> 
> LCD init
> system start
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> QuantizedConv2D: 1000.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> QuantizedConv2D: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> QuantizedConv2D: 0.000000ms
> Dequantize: 0.000000ms
> Concat: 0.000000ms
> Quantize: 0.000000ms
> KPUUpload: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> QuantizedBinary: 0.000000ms
> KPUUpload: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUUpload: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> Pad: 0.000000ms
> KPUUpload: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> Concat: 0.000000ms
> KPUUpload: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> KPUConv2D: 0.000000ms
> Transpose: 0.000000ms
> MemoryCopy: 0.000000ms
> Dequantize: 0.000000ms
> Concat: 0.000000ms
> Quantize: 0.000000ms
> Reduce: 0.000000ms
> Quantize: 0.000000ms
> QuantizedBinary: 0.000000ms
> Dequantize: 0.000000ms
> Unary: 0.000000ms
> Quantize: 0.000000ms
> Reduce: 0.000000ms
> Quantize: 0.000000ms
> QuantizedBinary: 0.000000ms
> Dequantize: 0.000000ms
> Total: 1000.000000ms
```

**Comment by sunnycase** [comment]
You should use this toolchain `https://github.com/kendryte/kendryte-gnu-toolchain/releases/tag/v8.2.0-20190213`
The newest toolchain has sth wrong with `gettimeofday`.

**Comment by krishnak** [comment]
I am building the code with that tool chain,
Using built-in specs.
COLLECT_GCC=/opt/kendryte-toolchain/bin/riscv64-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/opt/kendryte-toolchain/libexec/gcc/riscv64-unknown-elf/8.2.0/lto-wrapper
Target: riscv64-unknown-elf
Configured with: /mnt/d/Work/Repository/maix-toolchain/riscv-gcc/configure --target=riscv64-unknown-elf --prefix=/opt/kendryte-toolchain --disable-shared --enable-threads=posix --enable-languages=c,c++ --enable-libatomic --with-system-zlib --enable-tls --with-newlib --with-sysroot=/opt/kendryte-toolchain/riscv64-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --src=.././riscv-gcc --enable-checking=yes --disable-multilib --with-abi=lp64f --with-arch=rv64imafc 'CFLAGS_FOR_TARGET=-Os -ffunction-sections -fdata-sections  -mcmodel=medany' 'CXXFLAGS_FOR_TARGET=-Os -ffunction-sections -fdata-sections -mcmodel=medany'
Thread model: posix
gcc version 8.2.0 (GCC)

**Comment by sunnycase** [comment]
There are 2 versions of gcc 8.2.0. You should download from that link.
________________________________

**Comment by krishnak** [comment]
@sunnycase 
![image](https://user-images.githubusercontent.com/1259447/72265659-e1aa5780-3642-11ea-909f-91cbea1ca23a.png)

I downloaded  on Dec 11,2019 from https://kendryte.com/downloads/ - it has the exact file name and file size

I will take your word and download it from github and let you know the result.

**Comment by krishnak** [comment]
Great @sunnycase,  with this toolchain, timings are appearing for each layer in the debug. Thanks.

I am running the ultra_fast face detect example which you have ported. Everything seems to work fine, faces are getting detected however there seems to be some coredump when this method is executed ultra_face_detect, the debug statement gets printed - boxes do get drawn on the faces, but the for loop doesn't complete successfuly. This is consistent for any image that I use.

161, 53
W (808176596) SYSCALL: sys_exit called by core 0 with 0x1

I notice that you have starred the YonghaoHe / A-Light-and-Fast-Face-Detector-for-Edge-Devices 

Are you working on porting it?

In that project I tried to convert the head detection model from MXNET to ONNX ->tflite->kmodel, but it is failing with some slice error at the first conversion itself.

Do you have any suggestion for conversion of MXNET to KModel?

**Comment by krishnak** [comment]
@sunnycase Debug output for nncase layer execution, currently the time printed for execution of individual layers in debug mode  seems to include the printf overhead as well. Is there a way to calculate it without that over head

in NON debug mode - total execution time of kpu_run_model() as calculated in main.c is around 66ms.
in debug mode - the total time for execution printed by debug statement inside nncase.cpp is double that of time taken by non debug mode. This is understandable since the individual layers are all calling a printf.

However what is intriguing is if you add the individual layers execution time it still adds up to the total execution time. i.e the individual layers execution time also seem to add some printf overheads from previous layer's debug output.

**Comment by sunnycase** [comment]
>161, 53
W (808176596) SYSCALL: sys_exit called by core 0 with 0x1

You can try the newest code in the example.

> Debug output for nncase layer execution, currently the time printed for execution of individual layers in debug mode seems to include the printf overhead as well. Is there a way to calculate it without that over head

You can try the newest SDK.

**Comment by krishnak** [comment]
@sunnycase thanks for the changes, All those issues are now gone with your changes however image flickers due to new ultra face detect changes.

NEW issue:  the modified ultra_face_detect is causing LCD to flicker with dark vertical lines, see attached image, if I comment out the ultra_face_detect - the image appears without distortion. Notice the dark vertical lines on the left side. I am also attaching picture with the OLD ultra_face.cpp file, the picture wasn't distorted with that.

 Inference time has improved now to 61ms for slim model, 188ms for RFB model.

![IMG_20200115_230415](https://user-images.githubusercontent.com/1259447/72457791-61742580-37ed-11ea-824b-6f69eeb168cd.jpg)




![IMG_20200115_231409](https://user-images.githubusercontent.com/1259447/72457979-ba43be00-37ed-11ea-9fd1-51f1718585d7.jpg)

**Comment by sunnycase** [comment]
There may be some bugs in ultra_face_detect, I'm investigating it.

**Comment by krishnak** [comment]
@sunnycase 
@sunnycase 
There is a silly error in your github code- the compiler hasn't picked it up - this has been causing the flicker and all the issues. Do you want to try figuring out. It is pretty obvious. I will tell you the answer if you can't figure it out :))

I have fixed it and the flickering and incorrect boxes have disappeared.

```
int ultra_face_detect(float *scores, float *boxes, callback_draw_box callback)
{
    g_detector->clear();
    g_detector->generateBBox(scores, boxes);
    auto &output = g_detector->nms(blending_nms);
    printf("%d\n", (int)output.size());
    for (auto &face : output)
    {
        //printf("%f, %f, %f, %f, %f\n", face.x1, face.x2, face.y1, face.y2, face.score);
        callback((int)roundf(face.x1), (int)roundf(face.y1), (int)roundf(face.x2), (int)roundf(face.y2), face.score);
    }
      
}
```

**Comment by krishnak** [comment]
Closed as it has been fixed by the missing return statement
