### ISSUE TITLE
Ultra fast face detector Model conversion work flow

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#78]
@sunnycase 

Is it possible for you to share how you converted the original model provided by the author in to KModel. As the original model is available in Pytorch/Caffe and ONNX. Did you just use the caffe model to convert?

**Comment by sunnycase** [comment]
See command lines from the readme.
Caffe models come from https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/caffe/model.
