### ISSUE TITLE
Delay in kpu_upload()- nncase.cpp

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#81]
In nncase.cpp when debug is 1, the slim-320.kmodel prints out  60ms as inference time

this is the output from
```
void on_done()
    {
#if NNCASE_DEBUG
        printf("Total: %fms\n", interpreter_.total_duration().count() / 1e6);
#endif

        if (done_callback_)
            done_callback_(userdata_);
    }


```

**I have disabled debug in nncase.cpp, I just measured the time taken to execute `run_kmodel` using the following code**

the output at this stage is 81ms.

There is no time consuming code being executed on the CPU after the `on_upload_done()`

Where do the additional 20ms gets added, as it is  a significant amount of delay.

```
int nncase_run_kmodel(kpu_model_context_t *ctx, const uint8_t *src, dmac_channel_number_t dma_ch, kpu_done_callback_t done_callback, void *userdata)
{
    auto nnctx = reinterpret_cast<nncase_context *>(ctx->nncase_ctx);
    uint64_t time = 0 ,t1 = 0,t2 =0;
    t1 = sysctl_get_time_us();

    int i = nnctx->run_kmodel(src, dma_ch, done_callback, userdata);
    t2 = sysctl_get_time_us();
    time = t2-t1;
    printf("Frame done in %ld ms \n",time/1000);
    fflush(stdout);
    return i;
    //return nnctx->run_kmodel(src, dma_ch, done_callback, userdata);

}
```

**Comment by krishnak** [comment]
On further analysis, it appears the delay occurs before the inference in nncase.cpp
, i.e there are two separate calls to kpu_upload, first one takes 15ms and the second one 2ms. Total 17ms. This is when a single frame is processed.

However when a camera is feeding continuously, this increases to 27ms

Can this be decreased ?

@sunnycase

**Comment by sunnycase** [comment]
There is a bug in DMA hardware occasionally prevent loading data from cache.
You can personally use `kpu_upload_dma` instead of `kernels::k210::kpu_upload` at https://github.com/kendryte/kendryte-standalone-sdk/blob/develop/lib/nncase/nncase.cpp#L95

**Comment by krishnak** [comment]
Thank you, I did that using the following code, the code is not getting formatted properly, not sure why

`
else if (input.memory_type == mem_k210_kpu)
        {
            auto shape = interpreter_.input_shape_at(0);
            //kernels::k210::kpu_upload(src, mem.data(), shape);
            // the following call may crash due to hardware DMA bug - using it to test
            uint64_t start = sysctl_get_time_us ();
            kpu_upload_dma(dma_ch, src, mem.data(), mem.size(), kk_done_callback_, userdata_);
            uint64_t stop = sysctl_get_time_us();
            uint64_t time = stop-start;
            printf("DMA upload took %ld us\n",(time));
            on_upload_done();
            return 0;
        }
`


DMA upload took 18296 us, **this is taking more than the memcpy - memcpy used to take 17ms** for a single frame transfer which increased to 27 when a camera feed is connected.

Is there anything incorrect with my DMA call?

**Comment by sunnycase** [comment]
You should allocate your buffer with `iomem_malloc` , or `kpu_upload_dma` will firstly use memcpy then dma.

**Comment by krishnak** [comment]
Great, now  KPU upload is taking 328μs which is great. The over head is gone. I used to wonder, why DVP was swapping between two memory locations in frame finish call, now I have the answer.

**Comment by krishnak** [comment]
I have found something intriguing @sunnycase , can you please confirm whether you can reproduce this.
1. I run the slim-320.kmodel on the face.jpg  without DMA KPU transfer, it detects 95 faces.
2 I run the same model on the same image, but with DMA KPU transfer, it only detects 89 faces.

I have modified the run_kmodel() method as follows in nncase.cpp

```
 int run_kmodel_kk(const uint8_t *src, dmac_channel_number_t dma_ch, plic_irq_callback_t done_callback, void *userdata)
    {
        userdata_ = userdata;
        plic_irq_callback_t kk_done_callback_ = done_callback;
        interpreter_.dma_ch(dma_ch);

        auto input = interpreter_.input_at(0);
        auto mem = interpreter_.memory_at<uint8_t>(input);
        if (input.memory_type == mem_main)
        {
            std::copy(src, src + mem.size(), mem.begin());
            interpreter_.run(done_thunk, on_error_thunk, node_profile_thunk, this);
            return 0;
        }
        else if (input.memory_type == mem_k210_kpu)
        {
            auto shape = interpreter_.input_shape_at(0);
            //kernels::k210::kpu_upload(src, mem.data(), shape);
            // the following call may crash due to hardware DMA bug - using it to test
            uint64_t start = sysctl_get_time_us ();
            kpu_upload_dma(dma_ch, src, mem.data(), mem.size(), kk_done_callback_, userdata_);
            uint64_t stop = sysctl_get_time_us();
            uint64_t time = stop-start;
            printf("DMA upload took %ld us\n",(time));
            on_upload_done();
            return 0;
        }

        return -1;
    }


```
