### ISSUE TITLE
Detection accuracy of Kmodel compiled using ncc,  is affected by dataset used at the time of conversion

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#83]
I created two different slim-320 kmodels using the same slim-320.caffemodel

One was using
./ncc compile slim-320.caffemodel kkslim.kmodel -i caffe --dataset ./images

images folder has 25 images from the ULFFD repository.

another one was using

./ncc compile slim-320.caffemodel kkslimint2.kmodel -i caffe  --dataset 1.jpg

only one image used from ULFFD repository

both produced model of same file size.

Inference time of both models is the same 61.23ms with CPU @ 400MHz.

Model 1 detects 77 faces from 1.jpg which is available in ULFF github
Model 2 detects 75 faces from 1.jpg 

However **your model** on github detects 95 faces from 1.jpg

All the three models were run with the same thresholds for    
` ultra_face_init(320, 240, 0.3, 0.05, -1);
`
What was the dataset you used to produce your slim-320.kmodel. Can you please share.

This behaviour is visible while converting RFB-320.kmodel as well.

[model2.txt](https://github.com/kendryte/nncase/files/4101091/model2.txt)
[model1.txt](https://github.com/kendryte/nncase/files/4101092/model1.txt)

**Comment by krishnak** [comment]
This is only an issue if int8 quantization is used during ncc compile. And also if some one is converting a model which was not trained by them.

**Comment by wei8171023** [comment]
> This is only an issue if int8 quantization is used during ncc compile. And also if some one is converting a model which was not trained by them.

is it meaning that caffemodel needs to train by ourself?
