### ISSUE TITLE
dataset format with matrix

### ISSUE THREAD

**Issue by zye1996** [kendryte/nncase#84]
Hi,

How should I organize my dataset if I am using matrix for quantization calibration? should I keep each entry as an individual file saved as .npy file or put all entries in one file?

**Comment by krishnak** [comment]
Good question, I too had this issue when I tried to convert a non image model. I just used float as the --inference-type float. This doesn't need the c

After some trial and error with a single layer model which takes a single float value as a parameter, I converted it using these command line arguements
-i tflite  --dataset-format raw --dataset ./y2x.txt
I had the float value in the y2x.txt as 3.0 and the model compiled.
You could try playing with a simple matrix model to test the format if you don't get a reply.

**Comment by zye1996** [comment]
Figured out the solution. Just to take a note here... Save **each data entry** as a single file in binary format using np.array.tofile (using np.save does not work seems this adds a header to file and size changes)
Then use --dataset YourCalibrationDataset --dataset-format raw --input-type float
But seems on inference we need to convert our input data to NCHW manually unlike compiling?
