### ISSUE TITLE
Evaluator for FakePiecewiseLinear is not found

### ISSUE THREAD

**Issue by tjmc** [kendryte/nncase#85]
I'm getting ```Evaluator for FakePiecewiseLinear is not found``` error when I try to compile the attached graph

[detect_piecewise.tflite.zip](https://github.com/kendryte/nncase/files/4105985/detect_piecewise.tflite.zip)

It looks like PiecewiseLinear was added with commit: https://github.com/kendryte/nncase/commit/8678f7fc52debb9cfd36ee5bc63a8b00a6f7abff 

```
./ncc compile detect_piecewise.tflite model.kmodel --dataset /tmp/test_images/ -i tflite
1. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...
Fatal: Evaluator for FakePiecewiseLinear is not found] 0% 0s
```

Using target CPU it works
```
./ncc compile detect_piecewise.tflite model.kmodel --dataset /tmp/test_images/ -I tflite -t cpu
. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...
  [==================================================] 100% 2.121s
  4.5. Quantize graph...
5. Lowering...
6. Generate code...
  Plan buffers...
```

Does the operation need registered in https://github.com/kendryte/nncase/blob/master/src/evaluator/ops/k210/k210_ops.cpp ?

**Comment by sunnycase** [comment]
You can try the newst ncc in the CI.

**Comment by mstoye** [comment]
Did it work in the end?

**Comment by tjmc** [comment]
I used the artifact at [ncc_linux_x86_64](https://dev.azure.com/sunnycase/nncase/_build/results?buildId=122&view=artifacts&type=publishedArtifacts) but I'm still getting

> Fatal: Evaluator for FakePiecewiseLinear is not found] 0% 0s

**Comment by tjmc** [comment]
As a workaround, commenting out
https://github.com/kendryte/nncase/blob/000079ab2206929ed053b48252600a3063879aa1/src/cli/targets/k210/target.cpp#L92
allows the model to compile.

I'm assuming this prevents the fusing of conv + piecewise. I don't know what impact this might have however.

**Comment by sunnycase** [comment]
Currently a new piecewise unary fuser is under development, it will cover this scenario.

**Comment by tjmc** [comment]
Great, Thanks!

**Comment by sunnycase** [comment]
You can try this build: https://dev.azure.com/sunnycase/nncase/_build/results?buildId=129&view=results

**Comment by tjmc** [comment]
The model compiles and infers. I'm seeing some accuracy issues but I'm double checking things on my end.

**Comment by tjmc** [comment]
Looks good. The issue was on my end.
