### ISSUE TITLE
Size of images in the dataset for nncase

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#86]
I'm trying to create an object detection model trained myself using the tutorials out there, no success yet, so wanted to ask — should the images in the dataset passed for `nncase compile` command should have exactly equal size to the input size of the model (like `224x224`) or they can be of arbitrary size, just like the pictures in the training set (of course, given the model has input resize stage)?

I stuck with my model a little, it's created and is loading fine, but detects nothing for now, so I'm trying to find the problem in this little details :)

**Comment by krishnak** [comment]
Just to be clear is your model detecting objects on your computer where you are training?

**Comment by aclex** [comment]
@krishnak Unfortunately, I'm not sure, as I don't have the inference code for PC for the model, to interpret `nncase infer` output. Just making my first steps with it. In general I'm trying to follow [this tutorial](https://www.instructables.com/id/Object-Detection-With-Sipeed-MaiX-BoardsKendryte-K/), but had to change a couple of things to get it work without errors (namely, saving to `tflite` and splitting the dataset), so not sure, if my model is still authentic enough.

**Comment by krishnak** [comment]
I think you will be caught in an end less loop if you try to adapt it to nncase before making it work on tensorflow/keras. Are you just doing a trial to see whether you can successfuly transfer between tf to nncase or are you implementing a serious model. Your tensorflow model detecting the object is a pre-requisite for the nncase model to detect. 

the following might help if you are getting a bin file after your ncc infer
https://github.com/kendryte/nncase/issues/55

**Comment by aclex** [comment]
@krishnak thanks for the reference! Yes, you're right, for now I'm just trying to test and trial of what I can do on K210 in terms of model size and power. I managed to run a pre-trained tinyYOLO models from both MaixPy and C code successfully, the speed in C is very promising for my case (about 32 fps), but now I wanted to train my model from the ground up and optionally check if I could run also some newer models, more recent, than tinyYOLO (Mobilenet-edgetpu looks ideal in terms of performance vs. size compromise to me). But yes, now I'm a little stuck with finding some proved-to-work example to start with. I'm more to PyTorch in general, not so comfortable with TF1 or Keras code to fix things quickly :) But yes, I agree with you, I obviously should try and test the model on the computer before, as quick test seems to fail)

The model I got following the tutorial I try in MaixPy, because it's from nncase-1 (made in Maix_Toolbox). But in general my target is C code.

**Comment by krishnak** [comment]
OK, since you are a pytorch expert you should know, right now the route to kmodel is only via caffe.
i.e Pytorch -> Caffe -> Kmodel, some noble soul has written a Pytorch to ONNX and ONNX to Caffe converter https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/caffe

This model has been already ported to kmodel, it is available in the nncase examples folder, you can start there. 

We should take this conversation away from this issue section, as it is not related to nncase.

**Comment by aclex** [comment]
Yes, I also consider this path, but initially wanted to quickly try something out of the box. Maybe it's worth trying sooner, that I planned.

Oh, yes, absolutely, sorry for little off-topic) But due to not so much information in general, maybe it would be helpful for someone else. I personally found the main part of useful information in the closed issues, very valuable source)

**Comment by krishnak** [comment]
True but there is forum.kendryte.com but mostly its all quiet every where. I have no issue if you want to communicate here :) . What I have realised is that there are still some operations done on CPU and not on KPU, this might reduce the performance of the device. I noticed that in the nn case API image from the camera is fed to the KPU through CPU and not by using DMA - I hope there will be an example as to how this is done using the DMA. This is adding a 27ms over head per frame.  Maixpy have a new release a few minutes ago https://bbs.sipeed.com/t/topic/1790/2 - it is quiet there as well!!, on a side note are you from Brighton?

**Comment by aclex** [comment]
Oh, thank you, didn't know about the forum, never came across it surprisingly) Yes, surely, let's continue there.
From my experience with K210 it looks like there's not particular performance issues in pure C/C++ environment, but things slow down under MaixPy. As for KPU loading — do you mean CPU utilization even when setting KPU memory regions? Nice finding, I've been pretty sure it's DMA.

New MaixPy is nice news! Changelog looks quite promising, will try it shortly. Though SDK is quite stable and feature complete, MaixPy is still very fast way to try things.

Brighton no, not really) I'm just near Moscow, Russia)

**Comment by sunnycase** [comment]
images will be scaled by ncc to the size of your model's input.

**Comment by aclex** [comment]
@sunnycase nice, thanks for clarification! Generally, will it make any harm, if I pass the whole training set as this dataset?

**Comment by sunnycase** [comment]
The dataset will have effect on quantization quality, but it's uncertain.

**Comment by aclex** [comment]
@sunnycase thank you! It's quite clear now.

**Comment by krishnak** [comment]
@aclex you can see here for some discussion which will give some more insight.
https://github.com/kendryte/nncase/issues/60

**Comment by aclex** [comment]
@krishnak Yes, thanks, will look through it as well.
