### ISSUE TITLE
ONNX importer

### ISSUE THREAD

**Issue by aclex** [kendryte/nncase#87]
Thinking of writing one myself, had a quick look at the [onnx](https://github.com/onnx/onnx) code and list of operations, looks quite doable to me. Just wanted to ask: would it be expected or, looking at the [diagram](https://github.com/kendryte/nncase/blob/master/docs/arch.png), maybe there's already something almost complete similar feature planning for release? Just to not waste time on duplicated functionality.

**Comment by sunnycase** [comment]
onnx importer is a planned feature but hasn't started to write, so contribution is wellcome :).
There are some other importers like `tflite` `caffe` `paddle`, you can take them for reference.
https://github.com/kendryte/nncase/tree/master/src/importer
They are used at here https://github.com/kendryte/nncase/blob/master/src/cli/compile.cpp#L120

**Comment by aclex** [comment]
@sunnycase thank you very much for the information and suggestions! I'll then try to work at it) Yes, I've been already taken a look at code structure in this part, it seems to be quite clear, so I wanted to add support of the tflite ops subset as a beginning.

Very high C++ code quality in my opinion, by the way! Thank you! Quite a rare case these days :)

**Comment by sunnycase** [comment]
@aclex I see you have written much code about onnx importer, would you mind making a pull request?

**Comment by aclex** [comment]
@sunnycase yes, indeed, I'm still trying to finish the onnx importer, writing the Python tests now, the same as it is for tflite importer. Surely, I've been planning to submit a pull request as the tests are finished and all pass, just to not introduce any unstable code. But I can make a pull request with the current state later in the evening today, if you prefer so. We can then discuss it while I'm finishing the tests.

**Comment by sunnycase** [comment]
@aclex Sure. Great jobs!

**Comment by zhangyang2057** [comment]
ONNX importer has been merged, so close this issue.
