### ISSUE TITLE
CPU to KPU ops - where to start

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#88]
If one wants to contribute in implementing/porting an op which is currently executed on CPU to KPU, what other background is required other than the knowledge of C/C++.

Can you provide some starting tips and any simple OP that can be worked on to start with.

**Comment by sunnycase** [comment]
nncase use IR system to manage compilation pipelines.
Some passes is used to transform neutral ops into k210 ops (https://github.com/kendryte/nncase/blob/master/src/cli/targets/k210/target.cpp#L82).
You can write more transforms to improve KPU usage.
An example: https://github.com/kendryte/nncase/blob/master/src/transforms/hlir/k210/fake_kpu_conv2d.cpp

**Comment by krishnak** [comment]
So all the stuff below, are fit candidates for KPU transforms?

```
nncase-master/src/transforms/hlir/neutral$ ls
add_quant_checkpoints.cpp     fold_constant.cpp  fold_reshape.cpp    fuse_pad.cpp          quantized_matmul.cpp
dequantize_motion.cpp         fold_pad.cpp       fold_transpose.cpp  quantized_binary.cpp  transpose_motion.cpp
eliminate_dilated_conv2d.cpp  fold_quantize.cpp  fuse_clamp.cpp      quantized_conv2d.cpp

```

**Comment by krishnak** [comment]
What is the difference between  the "Targets" CPU and Neutral? is it some

**Comment by sunnycase** [comment]
neutral is not a target name, it's a set of ops availiable on all targets. All importers import graph to neutral ops.
cpu is a target that doesn't use any platform specific ops such as KPU.

**Comment by sunnycase** [comment]
> 
> 
> So all the stuff below, are fit candidates for KPU transforms?
> 
> ```
> nncase-master/src/transforms/hlir/neutral$ ls
> add_quant_checkpoints.cpp     fold_constant.cpp  fold_reshape.cpp    fuse_pad.cpp          quantized_matmul.cpp
> dequantize_motion.cpp         fold_pad.cpp       fold_transpose.cpp  quantized_binary.cpp  transpose_motion.cpp
> eliminate_dilated_conv2d.cpp  fold_quantize.cpp  fuse_clamp.cpp      quantized_conv2d.cpp
> ```

KPU transforms are located at https://github.com/kendryte/nncase/blob/master/src/transforms/hlir/k210
But k210 target also use netural transforms to optimize the graph.

**Comment by krishnak** [comment]
Other than graph optimization is there any other magic done to speed up execution in K210 targets? My question is from a layman's perspective who don't have an intricate view of compiler optimisation, the CPU/K210/Neutral target question,  stems from the fact from this  [sipeed forum thread](https://bbs.sipeed.com/t/topic/1790) where they claim quantized Matrix multiplication is done in CPU, I really couldn't figure out how part of a model can perform in CPU? The matrix multiplication operation in the mobilenet model is taking around 65ms, the earlier model which I could find from their download link didn't have this operation at all. Is their assertion correct?

**Comment by sunnycase** [comment]
All operations KPU can do are contained in `fake_kpu_conv2d`. Any speed up through KPU should be a transform from neutral ops to subgraphs including `fake_kpu_conv2d`.

For an example, you can transform a matmul(RxC) into pad(to 1xRx4x4) + fake_kpu_conv2d(weights=CxRx1x1) + crop(to 1xCx1x1).

**Comment by sunnycase** [comment]
KPU can only do 1x1 or 3x3 convolution and pooling then activation. The detail hardware information can be found at fake_kpu_conv2d.
Any optimizations should be based on this haredware specification.

**Comment by krishnak** [comment]
OK, makes more sense now. Thanks for the explanation.

**Comment by krishnak** [comment]
If one wants to print out more information on the generated dot files for human inference of the KModel graph which file needs to be looked in to. For ex: Currently the model prints out KPUConv2D in a box, if I want to output the filter size,stride etc where should it be modified.

I looked in to cli/compile.cpp

dump_graph()
where I tried to print node->attributes() it only outputs a 0 in the dot file
How do I access the convolution type and filter size value

**Comment by sunnycase** [comment]
You should use `node_cast` to cast node to conv2d then you can get the convolution attributes.

**Comment by krishnak** [comment]
In order to get node attributes for convolution I have done this Inside compile.cpp

```
       
#include <hlir/visitor.h>
#include <hlir/ops/k210/fake_kpu_conv2d.h>

using namespace nncase::hlir::k210;

if (auto conv = node_cast<fake_kpu_conv2d>(node))


```
I was getting the following compilation error
```

[ 97%] Building CXX object src/cli/CMakeFiles/ncc.dir/compile.cpp.o
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp: In instantiation of ‘void {anonymous}::dump_graph(TGraph&, std::ostream&) [with TGraph = nncase::hlir::graph; std::ostream = std::basic_ostream<char>]’:
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:88:19:   required from ‘void {anonymous}::dump_graph(const compile_options&, TGraph&, std::string_view) [with TGraph = nncase::hlir::graph; std::string_view = std::basic_string_view<char>]’
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:148:44:   required from here
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:56:50: error: no matching function for call to ‘node_cast<nncase::hlir::k210::fake_kpu_conv2d>(std::unique_ptr<nncase::hlir::node>&)’
        if (auto conv = node_cast<fake_kpu_conv2d>(node))
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:29:

```
I switched to llir/visitor.h instead of hlir/visitor.h, now I am getting the following error

```

[ 97%] Building CXX object src/cli/CMakeFiles/ncc.dir/compile.cpp.o
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp: In function ‘void {anonymous}::dump_graph(TGraph&, std::ostream&)’:
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:56:24: error: ‘node_cast’ was not declared in this scope
        if (auto conv = node_cast<fake_kpu_conv2d>(node))
                        ^~~~~~~~~
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:56:24: note: suggested alternative:
In file included from /home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:29:
/home/krishnak/visualstudioworkspace/nncase-master/src/ir/hlir/../include/llir/visitor.h:128:12: note:   ‘nncase::llir::node_cast’
     TNode *node_cast(node &node)
            ^~~~~~~~~
/home/krishnak/visualstudioworkspace/nncase-master/src/cli/compile.cpp:56:49: error: expected primary-expression before ‘>’ token
        if (auto conv = node_cast<fake_kpu_conv2d>(node))
                                                 ^
make[2]: *** [src/cli/CMakeFiles/ncc.dir/build.make:76: src/cli/CMakeFiles/ncc.dir/compile.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: src/cli/CMakeFiles/ncc.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```
I tried using llir namespace to remove this error but its giving lot of other errors. Can you please advise

**Comment by sunnycase** [comment]
`node_cast` accept a `node&`, you should write `node_cast<fake_kpu_conv2d>(*node)`
