### ISSUE TITLE
由caffemodel转kmodel时，程序无输出结果

### ISSUE THREAD

**Issue by mingrui005** [kendryte/nncase#895]
**Describe the bug**
由caffemodel转kmodel时，程序无输出结果

**To Reproduce**
(testcaffe) C:\codes\vsCode\classification>python transformer.py
1. Import graph...

**Expected behavior**
输出.kmodel模型

**Origin model and code**
请于附件中查看

**Environment:**
 - OS: windows10+annaconda python3.8.16
 - nncase version v1.9.0-3473131
 - DL Framework caffe 1.0.0

[Origin model and code.zip](https://github.com/kendryte/nncase/files/11292839/Origin.model.and.code.zip)

**Comment by curioyang** [comment]
caffe支持度较低，推荐使用onnx tflite
