### ISSUE TITLE
The following error occurred while tflite was going to kmodel. Is there any solution?

### ISSUE THREAD

**Issue by jishujun** [kendryte/nncase#9]
Fatal: Exception has been thrown by the target of an invocation.

**Comment by sunnycase** [comment]
Can you upload the tflite model?

**Comment by jishujun** [comment]
Does k210 support direct upload of tflite model？Or show the tflite file to you？

**Comment by sunnycase** [comment]
Show the tflite to me.

**Comment by sunnycase** [comment]
Solved.
