### ISSUE TITLE
onnx文件转换kmodel异常

### ISSUE THREAD

**Issue by superbinary-code** [kendryte/nncase#909]
[PFLD_Ultralight_112_1.zip](https://github.com/kendryte/nncase/files/11392701/PFLD_Ultralight_112_1.zip)
>>> import _nncase
>>> _nncase.__version__
'1.8.0-55be52f'

~/nncase$ python nn_compile.py 
nn_compile.py:19: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in a future release.To silence this warning, please use `helper.tensor_dtype_to_np_dtype` instead.
  input_dict['dtype'] = onnx.mapping.TENSOR_TYPE_TO_NP_TYPE[onnx_type.elem_type]
WARNING: The argument `input_shapes` is deprecated. Please use `overwrite_input_shapes` and/or `test_input_shapes` instead. An error will be raised in the future.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...
WARN: Cannot find a decompiler for section .rdata
WARN: Cannot find a decompiler for section .text

SUMMARY
INPUTS

**Comment by xhuohai** [comment]
从这个log来看没有问题，打印的都是warning。

> WARNING: The argument input_shapes is deprecated. Please use overwrite_input_shapes and/or test_input_shapes instead. An error will be raised in the future.

这个warning是你使用了onnxonnx-simplifier的新版本，可以改成0.3.6.
