### ISSUE TITLE
conan remote: error: unrecognized arguments: https://conan.sunnycase.moe True

### ISSUE THREAD

**Issue by Yhaw** [kendryte/nncase#917]
I am not able to build the latest version on my pc.
I am using ubuntu 20 

cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

conan remote: error: unrecognized arguments: https://conan.sunnycase.moe True
ERROR: Exiting with code: 2
CMake Error at cmake/conan.cmake:1024 (message):
  Conan remote failed='2'
Call Stack (most recent call first):
  CMakeLists.txt:62 (conan_add_remote)

  - OS: [e.g. Ubuntu20.04]
 - nncase version [latest]

**Comment by zhen8838** [comment]
1. the current master is still under development, please use nncase [v1.9](https://github.com/kendryte/nncase/tree/v1.9.0).
2. the conan version should use 1.59.0, about compiling you can refer to our [ci script](https://github.com/kendryte/nncase/blob/v1.9.0/.github/workflows/compiler-build.yml)

**Comment by Yhaw** [comment]
Thank you..

Its able to compile now
..but when I run ncc..
It says no command ncc found.
That's the challenge now.

**Comment by zhen8838** [comment]
please refer compile yolox [example](https://github.com/kendryte/nncase/tree/v1.9.0/examples/yolox)

**Comment by Yhaw** [comment]
Great It worked 
with conan==v1.59 and with nncase release/1.0
Thank you @zhen8838 

Successful compilation and conversion to .kmodel for k210
_**But how am I sure the .kmodel version is v3.**_

**Comment by Yhaw** [comment]
Hello Sorry,

Please how do I convert the model to .kmodel version 3

**Comment by zhen8838** [comment]
[0.1.0](https://github.com/kendryte/nncase/releases/tag/v0.1.0-rc5) => kmodel v3
[0.2.0](https://github.com/kendryte/nncase/releases/tag/v0.2.0-beta4) => kmodel v4
1.0~1.9 => kmodel v5
