### ISSUE TITLE
TFLite permute channel gets placed incorrectly in kmodel graph

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#93]
Attached is the tflite file and corresponding kmodel generated.

In the tensor flow output
```

permute_1 (Permute)             (None, 2, 60, 80)    0           conv2d_11[0][0]                  
__________________________________________________________________________________________________
conv2d_13 (Conv2D)              (None, 60, 80, 4)    516         conv2d_12[0][0]                  
==================================================================================================
```

After compiling to kmodel
```

OUTPUTS
0       Identity        1x4x60x80
1       Identity_1      1x80x2x60
```
[amodel_permute.zip](https://github.com/kendryte/nncase/files/4184617/amodel_permute.zip)

**Comment by sunnycase** [comment]
You don't need the permute that nncase will add a NHWC to NCHW permute after conv2d.

**Comment by krishnak** [comment]
outputfaces = Permute(dims=(3,1,2))(outputfaces)

was resulting in this issue

However I have over come this by doing

outputfaces = Reshape((80*60,-1))(outputfaces)

With this it is transposing it correctly.
