### ISSUE TITLE
inconsistent model inference trained on keras and pure tensorflow

### ISSUE THREAD

**Issue by zye1996** [kendryte/nncase#94]
Hi,

I trained the same MNIST model on the tensorflow and on the keras. 
Then I follow the steps: convert keras to frozen graph->tflite using toco->nncase generate kmodel. I am pretty sure models from two approaches are the same up to tflite conversion. When I tried to deploy those kmodel on the k210, only the model from pure tensorflow works while the keras version did not produce correct output. 

Is training using keras a valid approcah or only tensorflow is supported? I saw there are tutorials training mobilenet on keras and convert the model to the kmodel successfully.

Attached the model structure training using keras and pure tensorflow:
![Screen Shot 2020-02-11 at 9 56 25 PM](https://user-images.githubusercontent.com/28901953/74298998-5d1e2800-4d19-11ea-956d-456c26348d0e.png)

**Comment by krishnak** [comment]
keras 2? Did you use tflite_convert or toco directly?

**Comment by zye1996** [comment]
> keras 2? Did you use tflite_convert or toco directly?

Yes I used keras2. I first converted .h5 model file to .pb frozen graph then used exactly the same command for both .pb files generated from keras and pure TF by using toco and nncase

**Comment by krishnak** [comment]
Can you try saving the h5 files with weights and then use tflite_convert and then nncase.
tflite_convert - I think is a newer version (?)

**Comment by krishnak** [comment]
on a separate note which version of nncase are you using?. Use it from the development tree for best results.
I have converted a sample mathematical equation which can be humanly verified between Keras to nncase, the results are identical to Keras and that of K210.

In my opinion nncase  performs correctly with what ever tflite you offer. you need to checkout the graphs after they are converted by nncase to see whether there is any discrepancy between the two models.
```

ncc compile reducedfiltermodel.tflite reducedfilter.kmodel -i tflite --dataset ~/nncase/images/1.jpg --dump-ir
 dot -Tpdf  ir_optimize_3.dot -o reducedfilter.pdf
```

Will give you theu graph after nncase conversion. You can debug from there on

**Comment by zye1996** [comment]
> Can you try saving the h5 files with weights and then use tflite_convert and then nncase.
> tflite_convert - I think is a newer version (?)

Thank you tflite_convert works perfectly
