### ISSUE TITLE
Why is the last convolution taking more time in k210

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#96]
I am doing some test to optimise the model

First I had 6 convolutions the execution time on KPU is as follows

```
KPUConv2D: | 0.211000ms
KPUConv2D: | 0.269000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 0.098000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 6.690000ms
Dequantize: | 2.341000ms
Total: | 9.807000ms
```
I added two more convolutions to this at the end of the model, so I expect the 6 the convolution to take 6.69ms, but the results are not like that

```
KPUConv2D: | 0.210000ms
KPUConv2D: | 0.268000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 0.099000ms
KPUConv2D: | 0.098000ms
KPUConv2D: | 6.691000ms
Dequantize: | 2.342000ms
Total: | 10.005000ms

```
The 6th convolution is now only showing 0.09ms where as in the previous case it showed 6.69ms

I can only infer that the last convolution timing is incorrect, some other over head is being added to it. Can you please confirm

**Comment by sunnycase** [comment]
Because these KPU layers need to write data to main memory.

**Comment by krishnak** [comment]
Just thinking out loud, can't this be done via DMA to reduce it?

**Comment by sunnycase** [comment]
There is a bug preventing using DMA, the old SDK did it using DMA and now it is fixed by replace with CPU.
