### ISSUE TITLE
Adding shortcut connection increasing convolution time

### ISSUE THREAD

**Issue by krishnak** [kendryte/nncase#97]
I have a very simple test model, I am attaching them as kmodel.

Please consider only the first 3 convolutional layer block. Ignore the second block.

In one model, I have a shortcut for bottleneck connection, in another model I have removed this connection.

The debug time that gets printed for KPU convolution without bottleneck is as below, so for first convolution it takes only 0.21ms which is NORMAL, when I add the skip connection for bottle neck.

It is only performing an ADD operation in CPU. 

However the convolution itself takes 26ms now. Is this how it is supposed to be? Or can this be optimised in nncase? if it is not an nncase issue can you please let me know how to get a better performance for this.
[blaze.zip](https://github.com/kendryte/nncase/files/4202489/blaze.zip)

```
Without bottleneck add in first block

DMA upload took 328 us
KPUConv2D: 0.210000ms
KPUConv2D: 0.519000ms
KPUConv2D: 0.072000ms
KPUConv2D: 7.092000ms
KPUConv2D: 0.184000ms
KPUConv2D: 0.032000ms
KPUConv2D: 6.770000ms
QuantizedBinary: 15.974000ms
Dequantize: 2.342000ms
Total: 33.195000ms
``````

```
With bottle neck ADD

DMA upload took 328 us
KPUConv2D: 26.508000ms
KPUConv2D: 0.042000ms
KPUConv2D: 26.561000ms
QuantizedBinary: 58.699000ms
KPUUpload: 20.367000ms
KPUConv2D: 0.517000ms
KPUConv2D: 0.072000ms
KPUConv2D: 7.090000ms
KPUConv2D: 0.183000ms
KPUConv2D: 0.032000ms
KPUConv2D: 6.769000ms
QuantizedBinary: 14.556000ms
Dequantize: 2.339000ms
Total: 163.735000ms

```

**Comment by krishnak** [comment]
I assume that the Convolution is being done in CPU? forecasting that they have to be shunted back for ADD operation

**Comment by sunnycase** [comment]
KPUConv2D is always executed in KPU.

**Comment by krishnak** [comment]
@sunnycase  You can check the model attached, the Conv2D is the same with and without skip connection, the Conv2D operation increases in time.

**Comment by krishnak** [comment]
Is there any time frame for new hardware release with a fix for DMA bug ? As any nn operation like ADD which involves CPU is getting this 20ms overhead for data transfer to memory

**Comment by sunnycase** [comment]
The reason is same with https://github.com/kendryte/nncase/issues/96#issuecomment-587261892
