### ISSUE TITLE
Problem loading converted kmodel with maixpy IDE

### ISSUE THREAD

**Issue by jshra** [kendryte/nncase#988]
I have an issue while trying to load succesfully flashed model while using maixpy IDE (both script and built-in terminal). I have written a simple and small model for MNIST application. The issue that comes up seems to be connected to conversion process as other models (prebuilt ones) are loading and working succesfully. It is also unlikely to be connected to memory (as model size is less than 250KB), or the model itself as it works fine before converting.

Whenever I try to load a model in script/terminal, using the following code:
import KPU
KPU.load(0x300000)

I get an error saying:
ValueError: [MAIXPY]kpu: load error:2003, ERR_KMODEL_FORMAT: layer_header.body_size <=0

I have been unable to find the reason for this error in both kpu documentation and nncase docs.

I use MaixDock M1 with Kendryte k210,
my maixpy frimware version is v0.6.2_85, I have tried using nncase versions 1.6.0-1.9.0, as the newest one doesn't support k210.
Model was originally wrtitten in tf, converted to tflite using official tflite converter and later with nncase, using example code from USAGE_EN, with parameters (input shape, i/o type) set to same values as in my model. 

I'll be really grateful for any help, as I've been trying to fix this problem for quite a long time now.

I attach the kfpkg file as well as tflite.
[mnist_0x300000.zip](https://github.com/kendryte/nncase/files/11917458/mnist_0x300000.zip)
[mnist.zip](https://github.com/kendryte/nncase/files/11917463/mnist.zip)

**Comment by sunnycase** [comment]
Please refer to https://github.com/kendryte/nncase/issues/512#issuecomment-1031014815.

**Comment by code2k13** [comment]
Getting the same here. Will really help if someone can educate me on how to fix. I am able to create a kmodel from tflite model successfully. But when I try to load it, I get the error: 
ValueError: [MAIXPY]kpu: load error:2003, ERR_KMODEL_FORMAT: layer_header.body_size <=0

Same error if I create and burn a kfpkg  file. Using Maix Dock M1 (K210)

**Comment by code2k13** [comment]
@jshra did you manage to find a solution. Same problem here. There needs to be better documentation.
